### ISSUE TITLE
Question/Bug: Websocket events no longer pushed through after update

### ISSUE THREAD

**Issue by mvniekerk** [eclipse/ditto#1001]
Hello
I've upgraded my K8s hosted instance of Ditto using Helm.

Now websocket events are no longer pushed through after sending START-SEND-EVENTS (the ACK does come through though).

How can I debug what on what container to see what went wrong?

**Comment by thjaeckle** [comment]
You could enable `DEBUG` logging in all services by setting the environment variable `LOG_LEVEL_APPLICATION` to `DEBUG`.

**Comment by mvniekerk** [comment]
Thank you.
Is there a design doc that can help me see which service decided to stop any websocket packets coming through?

**Comment by mvniekerk** [comment]
Gleaning from https://www.eclipse.org/ditto/architecture-overview.html, I see I should first look at concierge service.

**Comment by thjaeckle** [comment]
You should check whether the "authSubjects"/"authContext" you open the WebSocket session with are allowed to receive the emitted events.
The `gateway` logs a `INFO` message: `Creating WebSocket for connection authContext: <....>` when opening a new websocket.
Please check the content of this log message.

The second thing to check would be the `things` service - there you have to increase the log level to `DEBUG` as described before.
For each persisted and published event the `things` service logs a `DEBUG` message: `Persisting Event<...>`.
Please check the content of this log message - this includes a Ditto event containing DittoHeaders.
The `DittoHeaders` contain a `ditto-read-subjects` entry. This entry must contain one of the subjects ( "authSubjects"/"authContext") with which your WebSocket session was created.

**Comment by mvniekerk** [comment]
Thank you @thjaeckle this is very helpful

**Comment by mvniekerk** [comment]
I'm getting java.lang.ClassCastException: akka.util.ByteString$ByteString1C incompatible with java.lang.String on the `thing` microservice

**Comment by mvniekerk** [comment]
I've created another bug report https://github.com/eclipse/ditto/issues/1004 because this one is marked as a question
