### ISSUE TITLE
Enforce data integrity of Features with a Definition

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#107]
In #60 the Feature Definition was added to the Ditto model.
#60 however did not yet enforce that the Properties of a Feature are enforced to follow the types defined in  a Definition.

The idea of this issue is to add another Ditto microservice responsible for validating that the JSON of a Feature's Properties follow its defined Definition.
The Definition is interpreted as coordinates to an Eclipse Vorto "Function Block".

The Ditto team already contributed a [generator to Eclipse Vorto which generates JsonSchema](https://github.com/eclipse/vorto/pull/821) from a Vorto Function Block.

The new Ditto microservice could look up the Function Block at the public Vorto repo "http://vorto.eclipse.org", use its "generator HTTP API" in order to let the Vorto repo generate the JsonSchema and validate changes to a Feature against that JsonSchema.

In order to not always generate the JsonSchema, the generated schemas should be persisted into Ditto's database.

**Comment by danielFesenmeyer** [comment]
Nice idea 👍 

Just one question: When a feature is updated as a whole, the validation microservice does not need to know about the existing state of the feature. But in case of a partial update, the validation microservice would somehow have to know the existing feature state. Why not including validation into the things microservice?

**Comment by thjaeckle** [comment]
We need a separate persistence for the JsonSchemas anyway, so there would be a validation service anyways.
I'd like to keep the philosophy we currently have: If you don't need validation, just don't start the validation service. The Things service should not have to know anything of any other service IMO.

In case of a partial update the generated JsonSchemas just have to be fine grained enough. That way the validation service does not need the complete state of the feature (it does not even need to know about the Things service).

E.g. with following Feature properties example:

```json
{
   "properties": {
      "status": {
         "simple": "foo",
         "complex": {
             "one": 1,
             "on": false,
         } 
      }
   }
}
```

we would need several JsonSchemas which are generated by our Vorto generator:
* properties-schema.json
* properties-status-schema.json
* properties-status-simple-schema.json
* properties-status-complex-schema.json
* properties-status-complex-one-schema.json
* properties-status-complex-on-schema.json

And we would choose the one which matches the partially updated property.

The contributed Ditto generator in Vorto does already a part of that, it generates several JsonSchemas.
But not yet until every leaf of the hierarchy. It would currently only generate (from the example above):
* properties-schema.json
* properties-status-schema.json
* properties-status-simple-schema.json
* properties-status-complex-schema.json
