### ISSUE TITLE
Change return type of `JsonValue.of` to `JsonNumber` for number arguments

### ISSUE THREAD

**Issue by jufickel-b** [eclipse/ditto#1070]
Currently all variants of `JsonValue.of` return a `JsonValue`.
For number arguments, however, it is desirable to obtain a `JsonNumber` without being forced to manually cast.
As `JsonNumber` extends `JsonValue`, changing the method signatures would be a low hanging fruit that improves ditto-json API a bit.

**Comment by jufickel-b** [comment]
Additionally it is worth to think about introducing a `JsonFieldDefinition` for `JsonNumber`.

**Comment by theexplorist** [comment]
@jufickel-b Hi I am an open source enthusiast who contributes to java projects and previous google summer of code student developer, I am looking for new challenge so can you please tell me if I can contribute here?

**Comment by jufickel-b** [comment]
Hi @theexplorist, thanks for reaching out to us. Of course you can contribute here. Before doing so, it is crucial that you have a look at [CONTRIBUTING.md](https://github.com/eclipse/ditto/blob/master/CONTRIBUTING.md) – especially the legal requirements.
