### ISSUE TITLE
curl -X POST ,curl: (7) Failed to connect to ditto.eclipseprojects.io port 443: Connection refused!!

### ISSUE THREAD

**Issue by bachir-abdo** [eclipse/ditto#1074]
when i try to create a new things in  api/2 - online ditto sandbox i got this error "curl: (7) Failed"  : 
curl -X POST "https://ditto.eclipseprojects.io/api/2/things" -H  "accept: application/json" -H  "Authorization: Basic ZGl0dG86ZGl0dG8=" -H  "Content-Type: application/json" -d "{\"definition\":\"com.acme:coffeebrewer:0.1.0\",\"attributes\":{\"manufacturer\":\"ACME demo corp.\",\"location\":\"Berlin, main floor\",\"serialno\":\"42\",\"model\":\"Speaking coffee machine\"},\"features\":{\"coffee-brewer\":{\"definition\":[\"com.acme:coffeebrewer:0.1.0\"],\"properties\":{\"brewed-coffees\":0}},\"water-tank\":{\"properties\":{\"configuration\":{\"smartMode\":true,\"brewingTemp\":87,\"tempToHold\":44,\"timeoutSeconds\":6000},\"status\":{\"waterAmount\":731,\"temperature\":44}}}}}"
**curl: (7) Failed to connect to ditto.eclipseprojects.io port 443: Connection refused**

-----------------------------------

and when i try to create a new things in  api/2 - local ditto i got Bad Gateway : 
curl -X POST "http://localhost:8080/api/2/things" -H  "accept: application/json" -H  "Authorization: Basic ZGl0dG86ZGl0dG8=" -H  "Content-Type: application/json" -d "{\"definition\":\"com.acme:coffeebrewer:0.1.0\",\"attributes\":{\"manufacturer\":\"ACME demo corp.\",\"location\":\"Berlin, main floor\",\"serialno\":\"42\",\"model\":\"Speaking coffee machine\"},\"features\":{\"coffee-brewer\":{\"definition\":[\"com.acme:coffeebrewer:0.1.0\"],\"properties\":{\"brewed-coffees\":0}},\"water-tank\":{\"properties\":{\"configuration\":{\"smartMode\":true,\"brewingTemp\":87,\"tempToHold\":44,\"timeoutSeconds\":6000},\"status\":{\"waterAmount\":731,\"temperature\":44}}}}}"
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

**Comment by thjaeckle** [comment]
Thanks for reporting.

The sandbox at https://ditto.eclipseprojects.io was down - I started it again. Please be aware that this can always be the case, the sandbox is not operated in a "high availability" setup.

Regarding your question of the "502":
* how do you start your Ditto stack?
* did it start successfully?

**Comment by bachir-abdo** [comment]
i start ditto with : docker-compose up -d

**Comment by thjaeckle** [comment]
To quote myself:
> did it start successfully?

You can check that by executing `docker-compose ps`

**Comment by bachir-abdo** [comment]
i check with docker-compose ps and i got :
Name                       Command               State                      Ports
--------------------------------------------------------------------------------------------------------------
docker_concierge_1       /sbin/tini -- java -jar st ...   Up      8080/tcp
docker_connectivity_1    /sbin/tini -- java -jar st ...   Up      8080/tcp
docker_gateway_1         /sbin/tini -- java -Dditto ...   Up      0.0.0.0:8081->8080/tcp,:::8081->8080/tcp
docker_mongodb_1         docker-entrypoint.sh mongo ...   Up      0.0.0.0:27017->27017/tcp,:::27017->27017/tcp
docker_nginx_1           /docker-entrypoint.sh ngin ...   Up      0.0.0.0:8080->80/tcp,:::8080->80/tcp
docker_policies_1        /sbin/tini -- java -jar st ...   Up      8080/tcp
docker_swagger-ui_1      /docker-entrypoint.sh ngin ...   Up      80/tcp, 8080/tcp
docker_things-search_1   /sbin/tini -- java -jar st ...   Up      8080/tcp
docker_things_1          /sbin/tini -- java -jar st ...   Up      8080/tcp
-------------------------------------------------------------------------------------------------------------
 ditto are started successfully i think

**Comment by stmaute** [comment]
Hi @bachir-abdo, 
The command output looks good. 
But it seems the nginx still can not connect to the gateway service.
Can you try the following request and post the output?
`curl -X GET "http://localhost:8081/health" -H "Authorization: Basic ZGl0dG86Zm9vYmFy"`

**Comment by bachir-abdo** [comment]
i try curl -X GET "http://localhost:8081/health" -H "Authorization: Basic ZGl0dG86Zm9vYmFy"
curl: (7) Failed to connect to localhost port 8081: Connection refused

_________________________________

or you mean "http://localhost:8080/health"(8080) i try that too and i got Bad Gateway :
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

**Comment by stmaute** [comment]
it seems that the Ditto cluster can not be formed up.
Can you provide the logs of one container? e.g. gatewy

**Comment by stmaute** [comment]
@bachir-abdo Did you manage to get Ditto running?
