### ISSUE TITLE
How can I save data as a text file?

### ISSUE THREAD

**Issue by bear1004** [eclipse/ditto#1083]
I am now running an example of getting data from Raspberry Pi in the Ditto example. 
I received data from Raspberry Pi by Ditto and succeeded in expressing the data through the web app. However, I couldn't find a way to save the data I received from the web app as a text file. 
Can you help me?

**Comment by thjaeckle** [comment]
Sorry, I don't get your question.
Ditto serves the current state of the digital twin of devices e.g. via an HTTP API.
Simply invoking that API with the correct credentials will give you a JSON representation of that "thing", see the [example in the documentation](https://www.eclipse.org/ditto/basic-thing.html#example).

Just save that one as a text file if you need to ..

**Comment by bear1004** [comment]
Sorry, I am not good at English.
My question is just how to save the data received as a JSON file from the "thing" as a text file. 

I can express the data I received from Ditto through a web app. However, I heard that there is no way to save JSON data in a text file in JavaScript. So I try to save it as a text file when I receive JSON data from "thing" on the ditto server. But I don't know  how place to add the code.

**Comment by thjaeckle** [comment]
Closing as this is a basic JavaScript related question and nothing specific to the Ditto project.
