### ISSUE TITLE
Issue with downloading ditto

### ISSUE THREAD

**Issue by HappyArthur29** [eclipse/ditto#1090]
I have downloaded all the prerequisite files needed and I got this message when I build it. Please advice, and pardon my little to none knowledge of this. I have downloaded Maven 3.8.1, JDK 11.0.11 and dockerhub

C:\Users\USER>mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.096 s
[INFO] Finished at: 2021-06-17T12:20:48+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\USER). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by stmaute** [comment]
Hi @HappyArthur29 ,

it seems you are invoking the mvn command in the wrong directory 

> C:\Users\USER>mvn clean install

After cloning the ditto repo with git you need to switch into the ditto directory and then run `mvn clean install`

Hope this helps you building ditto. 
Otherwise you can use the already existing Docker images from [Docker Hub](https://hub.docker.com/search?q=eclipse%2Fditto&type=image)

**Comment by HappyArthur29** [comment]
> Hi @HappyArthur29 ,
> 
> it seems you are invoking the mvn command in the wrong directory
> 
> > C:\Users\USER>mvn clean install
> 
> After cloning the ditto repo with git you need to switch into the ditto directory and then run `mvn clean install`
> 
> Hope this helps you building ditto.
> Otherwise you can use the already existing Docker images from [Docker Hub](https://hub.docker.com/search?q=eclipse%2Fditto&type=image)
what do you meant by switching the directory into ditto. Do you have an example?

**Comment by stmaute** [comment]
You need to do the following steps in a terminal to build ditto on your local machine:

`git clone https://github.com/eclipse/ditto.git

cd ditto

mvn clean install`

**Comment by HappyArthur29** [comment]
Thank you I got it to download but another issue. I researched it it seems there is some settings I have to change?

[INFO] Eclipse Ditto :: Internal :: Utils :: Health ....... SUCCESS [  5.801 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Tracing ...... SUCCESS [  2.968 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Cluster ...... SUCCESS [ 10.589 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Test ......... SUCCESS [  0.681 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Persistence .. FAILURE [ 20.197 s]
[INFO] Eclipse Ditto :: Base :: Service ................... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Distributed Data SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Pub-Sub ...... SKIPPED
[INFO] Eclipse Ditto :: Things :: API ..................... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Aggregator ... SKIPPED
[INFO] Eclipse Ditto :: Policies :: API ................... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Cache Loaders  SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Conditional Headers SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: JWT .......... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Namespaces ... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Protocol ..... SKIPPED
[INFO] Eclipse Ditto :: RQL ............................... SKIPPED
[INFO] Eclipse Ditto :: RQL :: Model ...................... SKIPPED
[INFO] Eclipse Ditto :: RQL :: parser ..................... SKIPPED
[INFO] Eclipse Ditto :: RQL :: Query ...................... SKIPPED
[INFO] Eclipse Ditto :: Thing Search :: API ............... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Search ....... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Persistent Actors SKIPPED
[INFO] Eclipse Ditto :: Policies :: Service ............... SKIPPED
[INFO] Eclipse Ditto :: Things :: Service ................. SKIPPED
[INFO] Eclipse Ditto :: Connectivity :: API ............... SKIPPED
[INFO] Eclipse Ditto :: Concierge ......................... SKIPPED
[INFO] Eclipse Ditto :: Concierge :: API .................. SKIPPED
[INFO] Eclipse Ditto :: Concierge :: Service .............. SKIPPED
[INFO] Eclipse Ditto :: Connectivity :: Service ........... SKIPPED
[INFO] Eclipse Ditto :: JWT ............................... SKIPPED
[INFO] Eclipse Ditto :: JWT :: Model ...................... SKIPPED
[INFO] Eclipse Ditto :: Gateway ........................... SKIPPED
[INFO] Eclipse Ditto :: Gateway :: Service ................ SKIPPED
[INFO] Eclipse Ditto :: Thing Search :: Service ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:17 min
[INFO] Finished at: 2021-06-17T14:26:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M4:verify (verify) on project ditto-internal-utils-persistence: There are test failures.
[ERROR]
[ERROR] Please refer to D:\ditto-master\ditto-master\internal\utils\persistence\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]

**Comment by stmaute** [comment]
Do you really need to build ditto on your own? Or would it be sufficient to used the existing Ditto Docker images from [Docker Hub](https://hub.docker.com/search?q=eclipse%2Fditto&type=image) 
If you only want to try out Ditto you can use on of the deployment [here](https://github.com/eclipse/ditto/tree/master/deployment)

In your last build there was a test failure. You can try to re-run the mvn command.

**Comment by HappyArthur29** [comment]
If it is easier ill do it.

**Comment by stmaute** [comment]
The easiest way is to use the docker-compose file to start Ditto. See [here](https://github.com/eclipse/ditto/blob/master/deployment/docker/README.md)
You only need docker and docker-compse installed on your machine.

**Comment by HappyArthur29** [comment]
AIGHT

**Comment by HappyArthur29** [comment]
I think it's okay I need to build a ditto myself, cause i'll be using it for another example of ditto. I keep getting this error. I'll try it figure it out thanks for your help man sorry to trouble you


[INFO] Eclipse Ditto :: Internal :: Utils :: Persistence .. FAILURE [ 20.197 s]

**Comment by stmaute** [comment]
Can you provide a bit more logs from the build?

**Comment by HappyArthur29** [comment]
sure here, thank you for the help mate

[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   IndexInitializerIT » ExceptionInInitializer
[ERROR]   MongoReadJournalIT » NoClassDefFound Could not initialize class org.eclipse.di...
[ERROR]   MongoTimestampPersistenceIT » NoClassDefFound Could not initialize class org.e...
[INFO]
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M4:verify (verify) @ ditto-internal-utils-persistence ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Eclipse Ditto 0-SNAPSHOT:
[INFO]
[INFO] Eclipse Ditto ...................................... SUCCESS [  5.999 s]
[INFO] Eclipse Ditto :: Legal ............................. SUCCESS [  0.903 s]
[INFO] Eclipse Ditto :: BOM ............................... SUCCESS [  0.251 s]
[INFO] Eclipse Ditto :: Documentation ..................... SUCCESS [  0.503 s]
[INFO] Eclipse Ditto :: Utils ............................. SUCCESS [  0.380 s]
[INFO] Eclipse Ditto :: Utils :: JSR-305 Extensions ....... SUCCESS [  1.861 s]
[INFO] Eclipse Ditto :: JSON .............................. SUCCESS [ 12.510 s]
[INFO] Eclipse Ditto :: JSON CBOR ......................... SUCCESS [  4.558 s]
[INFO] Eclipse Ditto :: Base .............................. SUCCESS [  0.211 s]
[INFO] Eclipse Ditto :: Base :: Model ..................... SUCCESS [ 15.102 s]
[INFO] Eclipse Ditto :: Policies .......................... SUCCESS [  0.221 s]
[INFO] Eclipse Ditto :: Policies :: Model ................. SUCCESS [ 13.246 s]
[INFO] Eclipse Ditto :: Things ............................ SUCCESS [  0.180 s]
[INFO] Eclipse Ditto :: Things :: Model ................... SUCCESS [ 11.200 s]
[INFO] Eclipse Ditto :: Thing Search ...................... SUCCESS [  0.205 s]
[INFO] Eclipse Ditto :: Thing Search :: Model ............. SUCCESS [  7.092 s]
[INFO] Eclipse Ditto :: Connectivity ...................... SUCCESS [  0.230 s]
[INFO] Eclipse Ditto :: Connectivity :: Model ............. SUCCESS [ 13.699 s]
[INFO] Eclipse Ditto :: Messages .......................... SUCCESS [  0.200 s]
[INFO] Eclipse Ditto :: Messages :: Model ................. SUCCESS [  6.627 s]
[INFO] Eclipse Ditto :: Protocol .......................... SUCCESS [ 14.267 s]
[INFO] Eclipse Ditto :: Base :: API ....................... SUCCESS [  6.124 s]
[INFO] Eclipse Ditto :: Internal .......................... SUCCESS [  0.170 s]
[INFO] Eclipse Ditto :: Internal :: Utils ................. SUCCESS [  0.181 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Config ....... SUCCESS [  5.983 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Metrics ...... SUCCESS [  8.461 s]
[INFO] Eclipse Ditto :: Internal :: Models ................ SUCCESS [  0.220 s]
[INFO] Eclipse Ditto :: Internal :: Models :: Streaming ... SUCCESS [  4.902 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Akka ......... SUCCESS [ 34.037 s]
[INFO] Eclipse Ditto :: Internal :: Models :: ACKs ........ SUCCESS [  9.168 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Cache ........ SUCCESS [  6.497 s]
[INFO] Eclipse Ditto :: Internal :: Models :: Signal Enrichment SUCCESS [ 23.687 s]
[INFO] Eclipse Ditto :: Internal :: Models :: Placeholders  SUCCESS [  5.205 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Health ....... SUCCESS [  6.342 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Tracing ...... SUCCESS [  3.062 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Cluster ...... SUCCESS [ 11.146 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Test ......... SUCCESS [  0.760 s]
[INFO] Eclipse Ditto :: Internal :: Utils :: Persistence .. FAILURE [ 20.339 s]
[INFO] Eclipse Ditto :: Base :: Service ................... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Distributed Data SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Pub-Sub ...... SKIPPED
[INFO] Eclipse Ditto :: Things :: API ..................... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Aggregator ... SKIPPED
[INFO] Eclipse Ditto :: Policies :: API ................... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Cache Loaders  SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Conditional Headers SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: JWT .......... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Namespaces ... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Protocol ..... SKIPPED
[INFO] Eclipse Ditto :: RQL ............................... SKIPPED
[INFO] Eclipse Ditto :: RQL :: Model ...................... SKIPPED
[INFO] Eclipse Ditto :: RQL :: parser ..................... SKIPPED
[INFO] Eclipse Ditto :: RQL :: Query ...................... SKIPPED
[INFO] Eclipse Ditto :: Thing Search :: API ............... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Search ....... SKIPPED
[INFO] Eclipse Ditto :: Internal :: Utils :: Persistent Actors SKIPPED
[INFO] Eclipse Ditto :: Policies :: Service ............... SKIPPED
[INFO] Eclipse Ditto :: Things :: Service ................. SKIPPED
[INFO] Eclipse Ditto :: Connectivity :: API ............... SKIPPED
[INFO] Eclipse Ditto :: Concierge ......................... SKIPPED
[INFO] Eclipse Ditto :: Concierge :: API .................. SKIPPED
[INFO] Eclipse Ditto :: Concierge :: Service .............. SKIPPED
[INFO] Eclipse Ditto :: Connectivity :: Service ........... SKIPPED
[INFO] Eclipse Ditto :: JWT ............................... SKIPPED
[INFO] Eclipse Ditto :: JWT :: Model ...................... SKIPPED
[INFO] Eclipse Ditto :: Gateway ........................... SKIPPED
[INFO] Eclipse Ditto :: Gateway :: Service ................ SKIPPED
[INFO] Eclipse Ditto :: Thing Search :: Service ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:18 min
[INFO] Finished at: 2021-06-17T20:10:40+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M4:verify (verify) on project ditto-internal-utils-persistence: There are test failures.
[ERROR]
[ERROR] Please refer to D:\ditto-master\ditto-master\internal\utils\persistence\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ditto-internal-utils-persistence

**Comment by stmaute** [comment]
It seems the **NoClassDefFound** causes the build to fail.
But it is hard to tell what the problem is without seeing the whole log.
Can you provide the full log after [ERROR] IndexInitializerIT » ExceptionInInitializer?

**Comment by HappyArthur29** [comment]
Running org.eclipse.ditto.internal.utils.persistence.mongo.indices.IndexInitializerIT
20:10:34,628 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [file:/D:/ditto-master/ditto-master/internal/utils/persistence/target/test-classes/logback-test.xml]
20:10:34,749 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:10:34,749 |-INFO in ch.qos.logback.core.joran.action.StatusListenerAction - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
20:10:34,759 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:10:34,769 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
20:10:34,789 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:10:34,839 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:10:34,839 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDERR]
20:10:34,849 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:10:34,849 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.ditto] to INFO
20:10:34,849 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
20:10:34,849 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
20:10:34,859 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDERR] to Logger[ROOT]
20:10:34,859 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:10:34,859 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6540cf1d - Registering current configuration as safe fallback point
2021-06-17 20:10:34,869 INFO  [] o.e.d.i.u.t.m.MongoContainerFactory  - Connecting to docker daemon on <tcp://localhost:2375>.
2021-06-17 20:10:35,563 INFO  [] o.e.d.i.u.t.m.MongoContainerFactory  - Checking if Mongo image <mongo:4.2> needs to be pulled.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.398 s <<< FAILURE! - in org.eclipse.ditto.internal.utils.persistence.mongo.indices.IndexInitializerIT
[ERROR] org.eclipse.ditto.internal.utils.persistence.mongo.indices.IndexInitializerIT  Time elapsed: 5.388 s  <<< ERROR!
java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
Caused by: com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect

**Comment by thjaeckle** [comment]
@HappyArthur29 seems like you don't have Docker installed, or have you?
You will need Docker as well to start Ditto - as [documented](https://www.eclipse.org/ditto/installation-running.html).

I am still wondering why you would like to build Ditto yourself - if you have not done any code adjustments, that's a waste of time.

**Comment by HappyArthur29** [comment]
I do have Docker installed. I install docker engine. Im doing all this because I am a student doing internship, my supervisor just gave  me this piece of work (https://github.com/eclipse/ditto-examples/tree/master/mqtt-bidirectional) and I need to understand and demonstrate it for him.

**Comment by Yannic92** [comment]
Hi @HappyArthur29 ,

from the error you posted, I assume you're using Windows as OS.
The error you see is from some test code within ditto. A mongo DB should be started automatically for some integration testing against a real database.

For this test the OS will be detected and depending on the used OS the code tries to interact with the docker daemon.
On Windows we expect the daemon to be available on localhost:2375.
So now there are two options which could cause your problem:

1. You use WSL2 to build ditto. AFAIK there are issues with WSL2 and this OS detection we implemented. We didn't fix this, yet.
2. You didn't enable your docker daemon to expose itself on port 2375. This is a setting of docker. Just open the docker settings using the docker tray icon and check if you enabled this.

**Comment by HappyArthur29** [comment]
> Hi @HappyArthur29 ,
> 
> from the error you posted, I assume you're using Windows as OS.
> The error you see is from some test code within ditto. A mongo DB should be started automatically for some integration testing against a real database.
> 
> For this test the OS will be detected and depending on the used OS the code tries to interact with the docker daemon.
> On Windows we expect the daemon to be available on localhost:2375.
> So now there are two options which could cause your problem:
> 
> 1. You use WSL2 to build ditto. AFAIK there are issues with WSL2 and this OS detection we implemented. We didn't fix this, yet.
> 2. You didn't enable your docker daemon to expose itself on port 2375. This is a setting of docker. Just open the docker settings using the docker tray icon and check if you enabled this.


Okay thank you I will try it out

**Comment by HappyArthur29** [comment]
> Hi @HappyArthur29 ,
> 
> from the error you posted, I assume you're using Windows as OS.
> The error you see is from some test code within ditto. A mongo DB should be started automatically for some integration testing against a real database.
> 
> For this test the OS will be detected and depending on the used OS the code tries to interact with the docker daemon.
> On Windows we expect the daemon to be available on localhost:2375.
> So now there are two options which could cause your problem:
> 
> 1. You use WSL2 to build ditto. AFAIK there are issues with WSL2 and this OS detection we implemented. We didn't fix this, yet.
> 2. You didn't enable your docker daemon to expose itself on port 2375. This is a setting of docker. Just open the docker settings using the docker tray icon and check if you enabled this.

Damn it actually got me through the error I was stuck on. Thank you!!! but now another issue came up.

[ERROR] Failures:
[ERROR]   ConnectionLoggerRegistryTest.aggregatesLogsRespectsMaximumLogSizeLimit:251
Expecting:
  [ImmutableLogEntry [correlationId=9c8627fa-7f2d-48db-91a8-ca18abd81a90, timestamp=2021-06-25T02:28:47.998372300Z, logCategory=connection, logType=other, logLevel=success, message=Processed message., address=null, thingId=null],
    ImmutableLogEntry [correlationId=53438087-32fd-4c41-bbe9-a5161230f74a, timestamp=2021-06-25T02:28:48.006677400Z, logCategory=connection, logType=other, logLevel=failure, message=Failure while processing message : not specified, address=null, thingId=null],
    ImmutableLogEntry [correlationId=0529ee14-c0ba-4964-bd7b-95dce534ca47, timestamp=2021-06-25T02:28:48.008013500Z, logCategory=connection, logType=other, logLevel=failure, message=Failure while processing message : not specified, address=null, thingId=null],
    ImmutableLogEntry [correlationId=87b82a99-ea26-41ea-babb-a314b603c0cd, timestamp=2021-06-25T02:28:48.010944100Z, logCategory=connection, logType=other, logLevel=failure, message=Failure while processing message : not specified, address=null, thingId=null]]
to not contain sequence:
  [ImmutableLogEntry [correlationId=9c8627fa-7f2d-48db-91a8-ca18abd81a90, timestamp=2021-06-25T02:28:47.998372300Z, logCategory=connection, logType=other, logLevel=success, message=Processed message., address=null, thingId=null]]
but was found at index 0

**Comment by HappyArthur29** [comment]
![Ditto](https://user-images.githubusercontent.com/86036482/123362409-3590ce00-d5a3-11eb-87b6-f9c965ecc0a0.PNG)

**Comment by HappyArthur29** [comment]
![Uploading ditto2.PNG…]()

**Comment by HappyArthur29** [comment]
![ditto2](https://user-images.githubusercontent.com/86036482/123363839-edbf7600-d5a5-11eb-87dc-bb877e2c9257.PNG)

**Comment by stmaute** [comment]
@HappyArthur29 Is this test constantly failing? Did you try to build it another time?

**Comment by HappyArthur29** [comment]
> @HappyArthur29 Is this test constantly failing? Did you try to build it another time?

Yeah it is, I tried out the advice that @Yannic92  told me I turned on dockerhub’s port setting and it worked. I tried it and it still failed.

**Comment by stmaute** [comment]
I wanted to know if the ConnectionLoggerRegistryTest is constantly failing or some other random tests are constantly failing?

**Comment by HappyArthur29** [comment]
> I wanted to know if the ConnectionLoggerRegistryTest is constantly failing or some other random tests are constantly failing?

it is constantly failing, tried 2 times failed two time

**Comment by stmaute** [comment]
Then it seems to be a problem with your machine. We neither have problems with this test on your Build environment nor on our local dev machines.

**Comment by HappyArthur29** [comment]
I see alright thanks a lot will look into it
