### ISSUE TITLE
Question about the expected behavior of using custom auth-subjects

### ISSUE THREAD

**Issue by raujonas** [eclipse/ditto#1092]
Hey there! I've read about the new functionality to create custom auth-subjects (https://www.eclipse.org/ditto/installation-operating.html#openid-connect). I have a question about the expected behavior of this functionality, because my tests do not match my expectations.

What I'm trying to achieve is the usage of groups from keycloak (instead of the sub claim, so that multiple users can easily have access to a thing) which are part of my jwt, for example:
```
 "groups": [
    "b2386a6c-fe10-44d5-82bf-d25e3e4e97b4",
    "91e6a873-d9fe-4eef-928f-b7906db06ec9",
    "cb87a63f-1238-44eb-96cd-3634b1d2df9c",
    "7a580140-f39e-42db-a62c-936e83b55ce5"
  ],
```
I'm also aware of the discussion in #512, that is why I expected that the created policy should have a separate subject for each of the four groups above. However the created policy looks like this (there's only my first group included):
```
{
    "policyId": "myfleet2:60cc403580f0c753aea7110f:Z00SC0000HQ000030",
    "entries": {
        "DEFAULT": {
            "subjects": {
                "keycloak:b2386a6c-fe10-44d5-82bf-d25e3e4e97b4": {
                    "type": "generated"
                }
            },
            "resources": {
                "thing:/": {
                    "grant": [
                        "READ",
                        "WRITE"
                    ],
                    "revoke": []
                },
                "policy:/": {
                    "grant": [
                        "READ",
                        "WRITE"
                    ],
                    "revoke": []
                },
                "message:/": {
                    "grant": [
                        "READ",
                        "WRITE"
                    ],
                    "revoke": []
                }
            }
        }
    }
}
```

I'm starting ditto with the following java parameters:
```
-Dditto.gateway.authentication.oauth.protocol=http 
-Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak.issuer=keycloak.localhost:8090/auth/realms/custom-realm 
-Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak.auth-subjects.0='{{ jwt:groups }}'
```

The question now is, is it possible to have a subject created for each of the groups which are part of the jwt or is this the intended behavior and just a misunderstanding on my side? Or is it just a configuration mistake on my side? In my case the number of groups could be dynamic.

Thank you very much for your help again! :blush: 

Edit: I'm on version 2.0.1

**Comment by thjaeckle** [comment]
Hi @raujonas
The default implicit policy Ditto creates (eg when creating a thing) will always only include the very first subject, even if the authorization context contained more than one subject. 
That way the first could eg be the user ID, additional ones could be groups. By default we always want to grant as few access as possible. 

You can however create the policy by yourself and use any amount of roles you want in there.

**Comment by raujonas** [comment]
Hi @thjaeckle. Thank you very much for the explanation, that was a misunderstanding on my side then! I'm using the following configuration now and it works perfectly with manually updating the policies!
```
-Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak.auth-subjects.0='{{ jwt:sub }}' 
-Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak.auth-subjects.1='{{ jwt:groups }}'
```

This is even better than what I had in mind because now the thing can still be created by a user and I can tell who created it in the future, but also give only read access to some groups with a separate policy entry. Great.

Thanks again! :blush:

**Comment by thjaeckle** [comment]
@raujonas Glad this works for you, thank you for the update 👍
