### ISSUE TITLE
Inconsistencies between API versions when modifying a Thing

### ISSUE THREAD

**Issue by ffendt** [eclipse/ditto#110]
I encountered an Exception when changing API version of the request to modify a Thing (`PUT /things/{thingId}`):

`2018-01-29 07:26:46,057 ERROR [48c77585-47b9-470b-96e8-4f16a055f18a] o.e.d.s.t.u.a.ThingUpdater akka://ditto-cluster/system/sharding/search-updater/3/org.eclipse.ditto%3A8f63f01a-1fc0-4968-a2b1-9cf5ed9de08a - Thing to update in search index had neither a policyId nor an ACL: ImmutableThing [thingId=org.eclipse.ditto:8f63f01a-1fc0-4968-a2b1-9cf5ed9de08a, namespace=org.eclipse.ditto, acl=null, policyId=null, attributes={"a1":"v1"}, features=ImmutableFeatures [features=[ImmutableFeature [featureId=f1, properties={"p1":{"fpk1":"otherValue"}}]]], lifecycle=null, revision=2, modified=null]`

I was able to trace this error back to inconsistent behavior between things and things-search, as things-search sometimes
1. is not able to update a Thing (see aforementioned Exception)
2. updates parts of the authorization that is not updated in the things service

To reproduce the problem, you can create a new Thing using API **x** and update the Thing using API **y**, which results in the following outcome:

| API x (create) | API y (update) | Result in things | Result in things-search|
| ---- | ---- | ---- | ---- |
| 1 | 1 |   👍  |  👍   |
| 1 | 2 | 👍  | ❌ |
|1 | 2 (with ACL in body) |  👍 | :x: |
| 1 | 2 (with policyId in body) |  👍 |  👍 |
|2 | 1 |  👍 |:x:|
|2 | 1 (with ACL in body) |  👍  |  👍 |
| 2 | 2 |  👍 | :x:|
| 2 | 2 (with ACL in body ) |  👍 | :x: |
| 2 | 2 (with policyId in body) |  👍 |  👍 |

The implementation should be changed to result in a consistent and predictable behavior. Since policies in v2 offer way more configuration possibilities, it should also be forbidden to change back from policies to ACL. I would suggest the following outcome:

| API x | API y | Result in things | Result in things-search|
| ---- | ---- | ---- | ---- |
| 1 | 1 |   👍  |  👍   |
| 1 | 2 | ❌  |  -  |
|1 | 2 (with ACL in body) |  ❌ | - |
| 1 | 2 (with policyId in body) |  👍 |  👍 |
|2 | 1 |  👍 (automatically adds policyId to emitted ThingModified Events) | 👍 |
|2 | 1 (with ACL in body) |  👍 (removes ACL and automatically adds policyId to emitted ThingModified Events)  |  👍 |
| 2 | 2 |  👍 (automatically adds policyId to emitted ThingModified Events)  | 👍|
| 2 | 2 (with ACL in body ) |  ❌ | - |
| 2 | 2 (with policyId in body) |  👍 |  👍 |

**Comment by thjaeckle** [comment]
fixed with PR #111 by @ffendt
