### ISSUE TITLE
Can I call by implementing the function I want in ditto?

### ISSUE THREAD

**Issue by bear1004** [eclipse/ditto#1128]
I want to implement a function that sends data by accessing MongoDB running with ditto through ditto. 
Can I implement this function available by calling from another things?

Tell me how I can implement it.

**Comment by thjaeckle** [comment]
Hi @bear1004 
Sorry, I did not understand what you are trying to achieve.
Could you please try to explain in a step-by-step way?

**Comment by bear1004** [comment]
I want to implement the following function I want in ditto.

The first function is to store data received from things in MongoDB.
I found that ditto stores data received as object as URL So this function simply reads the URL and stores it in MongoDB.

I currently have a code implementation that stores in MongoDBin python. But I would like to implement it in ditto API or founction.

The second function returns the latest data.
I want the function to behave like this:
1. Call the same in Unity. (API or other)
2. Return the latest data. (MongoDB or URL)

I would like to implement the following two functions in the form of functions or APIs and call them from outside code or things.

Is it possible? If possible, how can I implement it?

**Comment by thjaeckle** [comment]
Sorry, I still don't understand.
Maybe you can provide e.g. a sequence diagram? https://sequencediagram.org

**Comment by bear1004** [comment]
In a nutshell, is it possible to implement a custom API in ditto?

**Comment by Yannic92** [comment]
To understand what you want to achieve we need to understand what components should be involved and which component uses which API.

For example
> The first function is to store data received from things in MongoDB.
What is things? Where should this function run? Within Ditto?

> found that ditto stores data received as object as URL
No. Ditto stores the twin state as JSON objects in the MongoDB.

I try to make a guess:
You want to achieve that your application calls an HTTP endpoint of ditto with some payload for a twin (thing).
This payload should be stored in Dittos Mongo DB.
Then you want to achieve that your application calls another HTTP endpoint of ditto and gets the latest state of this payload?

Is this what you want to do?

**Comment by bear1004** [comment]
Yes!!

I am composing by referring to example "https://github.com/eclipse/ditto-examples/tree/master/grove-ctrl".
I am doing communication between raspberry pi and unity through ditto. Also, I want to store ditto's past data in MongoDB.

I am trying to send the data we need to ditto and read the data stored in ditto.
Is it correct to read the data sent to ditto through the HTTP call like "/api/2/things/org.eclipse.ditto.example:raspberry" in raspberry pi and unity?

I'm now saving ditto's past data in MongoDB with Python code via that HTTP call. Is the way I'm doing it right?
Currently ditto's API doesn't have the ability to automatically save to MongoDB?

**Comment by Yannic92** [comment]
> Currently ditto's API doesn't have the ability to automatically save to MongoDB?

Dittos main point is storing twin information in a MongoDB and making it accessible via multiple different APIs.
One of these APIs could be the HTTP API.

For example you could store your data in a twin feature by using an `HTTP PUT` to `/api/2/things/org.eclipse.ditto.example:raspberry/features/yourFeatureName` with your JSON data as payload.

Ditto will store this in a MongoDB and makes it accessible to you for example by calling the same endpoint with an `HTTP GET` afterwards.

There is no need (and we strongly advice you not to do this!) to access ditto's MongoDB manually.

If you need more information about our HTTP API feel free to check: https://www.eclipse.org/ditto/http-api-doc.html#/Features

If you want to learn about other APIs of Ditto, like Websocket or different messaging protocols like AMQP, MQTT or Kafka please check: https://www.eclipse.org/ditto/connectivity-overview.html

**Comment by bear1004** [comment]
Thank you!

It seems that only the latest data is currently available.
If i need past data, do i need to create a separate DB to store dittos JSON data?

**Comment by Yannic92** [comment]
Yes, Ditto does only store the latest state. Historical data is out of scope for Ditto.
If you however need historical information I'd suggest to write an application that subscribes to [feature modified events](https://www.eclipse.org/ditto/protocol-specification-things-create-or-modify.html).
You could for example setup an [HTTP  forwarding](https://www.eclipse.org/ditto/connectivity-protocol-bindings-http.html) connection in Ditto which calls an HTTP endpoint of your application with the modification that happened.
That way your application can build up a historical database.

**Comment by bear1004** [comment]
Yannic92 Thanks!!

**Comment by awslabspl** [comment]
@bear1004 

```php
$importedFunction = new \Path\To\Class'
$importedFunction->importedFunctionName();
```

**Comment by bear1004** [comment]
@awslabspl 

Where do I put that code?

**Comment by awslabspl** [comment]
@bear1004 ideal position of code (s) like this is just after your main class's opening.

**Comment by bear1004** [comment]
@awslabspl 

sorry i don't understand...
Is that codes JavaScript or something else??
What is main class??

**Comment by thjaeckle** [comment]
@awslabspl that definitely has nothing to do with the question, thanks for the confusion.

@bear1004 you can "enhance" Ditto's API by using "live messages". Please have a look at e.g. the following documentation to get an inspiration: https://www.eclipse.org/ditto/advanced-data-by-pass.html
That however is a quite advanced topic and requires first some understanding of Ditto's [live messages](https://www.eclipse.org/ditto/basic-messages.html) and how to [receive](https://www.eclipse.org/ditto/basic-messages.html#receiving-messages) them with e.g. WebSockets or connections via brokers.

**Comment by bear1004** [comment]
@thjaeckle 

Can you tell me where in the code in "Ditto" stores the latest data in MongoDB?

**Comment by thjaeckle** [comment]
Sure - for the persistence of "things" this is here: https://github.com/eclipse/ditto/blob/master/things/service/src/main/java/org/eclipse/ditto/things/service/persistence/actors/ThingPersistenceActor.java

There are some abstractions however, you won't see any direct Mongo interactions there, you'll have to figure that out by yourself.

**Comment by bear1004** [comment]
@thjaeckle 

Currently, uploading ditto to Docker is like downloading a default image through an internet connection. 

https://github.com/eclipse/ditto/blob/master/deployment/docker/docker-compose.yml

I want to edit "https://github.com/eclipse/ditto/tree/master/things" code and upload the code to docker,

how do I do that?

**Comment by Yannic92** [comment]
You can't upload your docker images to the ditto docker hub repo.
What you can do is building your images locally and either use them there directly or you could upload them to any docker container registry that is under your control.

[here](https://github.com/eclipse/ditto#build-and-start-ditto-locally) you can read how to build docker images on your own.
So you could make your adjustments and then build the docker images.

**Comment by bear1004** [comment]
![image](https://user-images.githubusercontent.com/62101255/127766224-530a99c6-e94b-47eb-ab5e-8de1a52227eb.png)

**Comment by bear1004** [comment]
@Yannic92 

I encountered an error while performing that process.
![image](https://user-images.githubusercontent.com/62101255/127766236-de1b33da-1f51-4235-a533-237c98dd40c6.png)

My environment is as follows.
maven - 3.8.1
JDK - 16.0.2
OS - windows10

**Comment by bear1004** [comment]
@Yannic92 

I successfully built the ditto code I modified through "mvn clean intall".
![image](https://user-images.githubusercontent.com/62101255/127771170-4c485959-8b3e-4e9c-b9bb-bbedc30a386d.png)

The code I modified is just an example to see if it can be modified.

The code I modified is the code "https://github.com/eclipse/ditto/blob/master/internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/AbstractShardedPersistenceActor.java" that logs every time an things are modified.

line 521 : l.info("Successfully persisted Event <{}> w/ rev: <{}>.", event.getType(),  getRevisionNumber()); to  l.info("Successfully persisted Event !!!!!!!!!!!!!!!!!!!!!!!!! <{}> w/ rev: <{}>.", event.getType(),  getRevisionNumber());

What I modified is to add ! to see if the log is modified. but didn't work....

What I have done is as follows.
1. modifiend code
2. buiid that code "mav clean install" and "./build-images.sh" (question :  Is it right to insert the code from "./build-images.sh" into the .env? I didn't know what that command does.
3. I insert code from "./build-image.sh" into the .env
4. docker-compose up -d
5. start ditto

I couldn't see the results of my modifications....

can you help me....?

**Comment by bear1004** [comment]
@thjaeckle 

I added the following code to save past data in "https://github.com/eclipse/ditto/blob/master/things/service/src/main/java/org/eclipse/ditto/things/service/persistence/actors/strategies/events/FeaturePropertiesModifiedStrategy.java".

MongoClient mongoClient = new MongoClient("localhost", 27017);

But the moment I send data to ditto, docker_things_1 stops.

I do not know reason. 
can you help..??

**Comment by thjaeckle** [comment]
@bear1004 this is wrong in so many ways that I don't even know where to start.
You can't just open a connection to mongodb there and assume to insert data. 

We already invested a lot of our time in your questions and won't invest any more.

You are on your own when you want to fork and adjust the Ditto codebase. 

Best of luck.
