### ISSUE TITLE
Ditto doesn't accept the "access_token" of a Google OAuth2.0 authenticated user

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#114]
Currently we only support the "id_token".
We should however also support the "access_token" and then make a lookup at Google's "userinfo" API in order to find out the Google user-id.

As this is a HTTP request, we must cache the response for as long as the JWT session is valid.

**Comment by yufei-cai** [comment]
Any update on the issue?

**Comment by thjaeckle** [comment]
Not that I am aware of.

**Comment by thjaeckle** [comment]
I think in the meantime that this is out-of-scope for Ditto - when using Google's OAuth2.0, you can also work with the `id_token` instead of the `access_token`.
So closing this "oldie" ..
