### ISSUE TITLE
Any suggestion to reduce the connectivity memory usage?

### ISSUE THREAD

**Issue by aaron0609** [eclipse/ditto#1149]
I'm now using ditto 2.0.1 which deployed in K8s, with more than 200 devices connected to ditto via hono MQTT adaptor.
Recently I found that the connectivity run out of the memory every 4-6 hours.
I allocated 1GB ram to connectivity deployment.

I would like to know which kind of operations will increase the connectivity memory usage and how can we avoid it?
(I have a script which enable & dump the connection logs every 10s, not sure if that's related to the memory consuming)

**Comment by thjaeckle** [comment]
@aaron0609 you thing 1GB of ram is much?
We use 8GB for each connectivity instance and have multiple instances of the connectivity service running.

The "connection logs" feature is however quite memory hungry, so you might need more memory when using this.
Please however be aware that the "connection logs" are mainly intended for development purposes and that there are no guarantees that log-statements are 100% available and kept.

When you need a reliable logging I suggest to rely on the Ditto service logs: https://www.eclipse.org/ditto/installation-operating.html
So either grepping them from STDOUT or pushing them into a logstash/elasticsearch.
