### ISSUE TITLE
How to relieve cpu usage of gateway service ? 

### ISSUE THREAD

**Issue by nisus91** [eclipse/ditto#1155]
How to relieve cpu usage of gateway service ? 

The number of things are about 2200. And they are updated every 30seconds.
My Ditto's status is as follows.
Only the gateway service's usage exceeds 200. 
For reference, the number of CPU core is 32 and the size of RAM is 64G.

CONTAINER ID     |   NAME      |            CPU %      |         MEM USAGE / LIMIT    |  MEM %              
64b2fb938b92     |    root_nginx_1      |      8.26%          |      3.703MiB / 62.76GiB   |  0.01%   
b3486fff221b       |   root_gateway_1    |      **205.24**%    |         603.2MiB / 1GiB   |     58.91%
ed688fb24bd8     |     root_connectivity_1 |    6.75%          |      368.4MiB / 1GiB       |  35.97%
338f4e0101f3      |    root_things-search_1  |  78.18%        |       754.7MiB / 1GiB      |   73.70%
75016413785f      |    root_concierge_1     |   56.17%        |       584.8MiB / 1GiB       |  57.11%
bb5c7a5cb4be     |     root_things_1      |    88.12%         |      447.1MiB / 1GiB       |  43.66%
403156e6c836      |    root_policies_1    |     6.25%        |        403.3MiB / 1GiB       |  39.38%    
580ac4a38415      |    root_mongodb_1   |       14.34%   |            13.4GiB / 62.76GiB  |   21.35%
a8fa0bc03365      |    root_swagger-ui_1   |    0.00%     |           1.477MiB / 62.76GiB  |   0.00%

**Comment by thjaeckle** [comment]
That heavily depends on what you are doing with the gateway.
Do the devices send the updates via HTTP?
Do you use websocket or SSE connections? How many?
How do you authenticate HTTP requests?

**Comment by nisus91** [comment]
I've changed the connection method between devices and Ditto as Mr. Jaeckle recommeded.
I've used MQTT broker, mosquitto, in front of my Ditto.
`{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "id": "mqtt-connection-carpediem6",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://carpediem:cp2020!@182.252.135.201:1883",
            "sources": [{
                "addresses": ["ditto"],
                "authorizationContext": ["pre-authenticated:mqtt-connection"],
                "consumerCount": 1,
                "qos": 0,
                "filters": []
            }],
            "mappingContext": {
                "mappingEngine": "JavaScript",
                   ....
}`
As a result, the CPU usage of the connection service increased to more than 100%.

I wonder if there is any other way.

**Comment by nisus91** [comment]
I wonder if there is any other way.

**Comment by thjaeckle** [comment]
@nisus91 so what would be your expectation?
100% CPU usage just means that the process uses 1 CPU Core (from which you apparently have 32).

**Comment by nisus91** [comment]
I want  the high stability of Ditto.
High CPU usage causes the system to crash.

**Comment by Yannic92** [comment]
Regarding the logs you shared I don't see any error. Where did you get them from? Directly from the container?
I would expect at least some exception in the log before the container crashes. What makes you assume that the high CPU usage is the reason?

Regarding higher load: Is there a reason why you don't want to scale connectivity higher and also increase the clientCount of your MQTT connection? This is how to scale horizontally ditto if you think this could help.

**Comment by nisus91** [comment]
> Regarding the logs you shared I don't see any error. Where did you get them from? Directly from the container?
> I would expect at least some exception in the log before the container crashes. What makes you assume that the high CPU usage is the reason?

I got the log file from docker container with ("docker-compose logs connectivity > log_file ").
As you said, I tried to find error message from the log file. 
But I could't find the related error message. 
However, it is clear that the connectivity service was disappeared in docker service ( I checked it with "docker ps").
So I started to suspect the high load was the cause of the problem.

> 
> Regarding higher load: Is there a reason why you don't want to scale connectivity to multiple instances and also increase the clientCount of your MQTT connection? This is how to scale horizontally ditto if you think this could help.

Can you tell me how to use multiple instance and increase the clientCount of the MQTT?

**Comment by Yannic92** [comment]
> Can you tell me how to use multiple instance and increase the clientCount of the MQTT?

Feel free to check the docker documentation about multiple replicas with docker-compose: https://docs.docker.com/compose/compose-file/compose-file-v3/

Regarding the clientCount see our documentation for the connection model: https://www.eclipse.org/ditto/basic-connections.html#connection-model

But I would suggest to dig into the reason for the actual failure. Unfortunately without having some error logs, we can't help you with this.
