### ISSUE TITLE
how to fetch partial data from external sources

### ISSUE THREAD

**Issue by dberardo** [eclipse/ditto#1167]
Hi community,

i have came across the Ditto project and it sounds quite promising. 

Looking at the documentation i could figure out that Ditto's underlying persistency layer uses MongoDB. In our use case i have quite a lot of data coming from the field in form of "timeseries" data. To store this sensor data there are other database technologies that we use currently that are optimized for storage and query performance of such kind of timeseries data. 

Also, in our digital twin configuration we save some other twin-specific meta-data, such as pictures, multimedia files, compressed python pickle model files, etc. that do fit much better on a AWS S3 based object storage system than in MongoDB.

My question here is, is it possible to define some attributes (Features) of a Thing in Ditto, so that the data is actually retrieved by other sources, so that when the user queries property x of thing T, then T.x is actually starting a download stream on as "s3://" endpoints or even running a SQL query on another DB and collecting the results?

And more in particular: does Ditto support JDBC connectors to perform such kind of queries? This would enable Ditto to connect for example to a Presto backend and thus include support to much more data sources.

**Comment by thjaeckle** [comment]
Hi @dberardo 
That (serving files from S3) sounds similar to what is described here: https://www.eclipse.org/ditto/advanced-data-by-pass.html
Did you have a look on that?

You can e.g. send "live messages" via an HTTP endpoint in Ditto `POST /api/2/things/my:thing-1/inbox/messages/my-super-query` which can be either answered by one of your services or e.g. an AWS Lambda function - resulting in a by Ditto correlated HTTP response.
For an S3 integration that would make at most sense in my opinion. 

You could also try to configure a Ditto managed [HTTP connection](https://www.eclipse.org/ditto/connectivity-protocol-bindings-http.html) which does a "GET" request to a S3 bucket reacting on "live messages". That is however quite advanced and will require a good understanding of Ditto connections.

Ditto itself does not support connecting via JDBC to other databases and retrieving some data there.
That would also be possible with an own microservice processing "live messages" responding e.g. with data fetched from a JDBC query.

**Comment by dberardo-com** [comment]
thanks for the quick reply @thjaeckle 

i did indeed have a look at the page mentioned above yesterday night, and it does represent a workaround for REST based communication (which is OK sometimes, but we also use GraphQL in our use case, which does not accept redirects).

The workaround explained in the doc works for GET requests, but would it be possible to write/update values using the same method? Or is it possible for Ditto to forward the write request to the underlying microservice and "wait" for a commit/confirmation that the data has been properly edited before sending a 200/201 response to the client?

As for the S3 integration, i will have a look, especially because we prefer using MinIO as open source counterpart to S3 and thus have to see how lambdas would work there.

**Comment by thjaeckle** [comment]
> i did indeed have a look at the page mentioned above yesterday night, and it does represent a workaround for REST based communication (which is OK sometimes, but we also use GraphQL in our use case, which does not accept redirects).

Well, Ditto does provide a REST API .. so you won't be able to invoke a GraphQL API on Ditto's HTTP endpoints ;)

> The workaround explained in the doc works for GET requests, but would it be possible to write/update values using the same method? Or is it possible for Ditto to forward the write request to the underlying microservice and "wait" for a commit/confirmation that the data has been properly edited before sending a 200/201 response to the client?

Yes, that's exactly what it can do/does. The data you transmit e.g. in the `POST` request of the message is then available for the subscriber of that message, which can be:
* a WebSocket session
* a Ditto managed connection (e.g. calling a foreign HTTP endpoint providing the data as well as "POST" payload - using the response and the status code of the foreign HTTP endpoint as status and payload of the Ditto HTTP request)

> As for the S3 integration, i will have a look, especially because we prefer using MinIO as open source counterpart to S3 and thus have to see how lambdas would work there.

Using Lambda is not a requitement, you can also directly access the S3 bucket via HTTP I suppose.

**Comment by dberardo-com** [comment]
ok, so for the time being this issue could be closed i guess. I am currently still evaluating how Ditto could fit in our current use case and will try to make experiments for such kind of integrations later on.

I will probably post on this same issue if that is possible, as soon as i have updates. For the time being, if you can point me to any other piece of documentation / blog article, or similar, that could help me get a better understanding on how to integrate Ditto in existing Machine Learning / Big Data systems and how does it fit in a Digital Twin environment, that would be beneficial.

So far i have just had a look at the documentation and webinars online, but i could only find very specific technical details on the technology in there, not really on the way it integrates in existing architectures, or related use cases.

Vielen Dank aus Berlin
