### ISSUE TITLE
Provide a 'fn:replace' method

### ISSUE THREAD

**Issue by ctron** [eclipse/ditto#1170]
There should be an out of the box function for calling `String::replace(String,String)` using `fn:replace("from","to")`.

**Comment by thjaeckle** [comment]
Sounds useful, yes 👍

**Comment by thjaeckle** [comment]
Implementation hint: get inspiration e.g. from 
* [PipelineFunctionSubstringBefore](https://github.com/eclipse/ditto/blob/master/internal/models/placeholders/src/main/java/org/eclipse/ditto/internal/models/placeholders/PipelineFunctionSubstringBefore.java)
* [PipelineFunctionSubstringBeforeTest](https://github.com/eclipse/ditto/blob/master/internal/models/placeholders/src/test/java/org/eclipse/ditto/internal/models/placeholders/PipelineFunctionSubstringBeforeTest.java)

**Comment by thjaeckle** [comment]
Closed via PR #1173
