### ISSUE TITLE
Build Fails at Utils:Akka

### ISSUE THREAD

**Issue by ZeeChono** [eclipse/ditto#1220]
Hi! By following the _Building with Apache Maven_(https://www.eclipse.org/ditto/installation-building.html). After `mvn clean install` I get the following error:

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.4.0:compile (default) on project ditto-internal-utils-akka: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.4.0:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.4.0:compile: java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.wrapOutputStream(Ljava/io/OutputStream;)Ljava/io/OutputStream;

Can anyone help me?

**My java version:** 
java 11.0.12 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

**My maven version:**
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: C:\Program Files\apache-maven-3.8.2
Java version: 11.0.12, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.12
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by thjaeckle** [comment]
@ZeeChono seems like an issue of the used scala-maven-plugin: https://github.com/davidB/scala-maven-plugin
Maybe in combination with a new JVM - our Jenkins uses 11.0.2 which still works.

Could you try to update the scala-maven-plugin version to the currently latest one "4.5.4" and see if this fixes the build problem?

**Comment by thjaeckle** [comment]
You could also try to disable the "incremental compile" mode: https://davidb.github.io/scala-maven-plugin/example_incremental.html
By setting `recompileMode` to `all` ..

**Comment by ZeeChono** [comment]
@thjaeckle Thanks for helping me! The API incompatibility error is solved by changing the scala-maven-plugin version to "4.5.4". But then I got the: 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin: 3.0.0-M4:test(default-test) on project ditto-internal-utils-akka: There are test failures.

I got the ditto build successfully using the "-DskipTests" flag in the end. I guess this would not affect the function of the project? I'm new to the build tools, sorry for inconvenience if I asked some dumb questions. 

Thanks agian for help!

**Comment by thjaeckle** [comment]
@ZeeChono No, that won't affect the function of the project. However building the project is not required for simply using it.
When you build it yourself, I assume you want to modify the code? In that case you should run the tests in order to be sure not to break something.

**Comment by ZeeChono** [comment]
@thjaeckle OK I see. Indeed I modified some code but now there're some test failures. I will go and check what is wrong. Thank you for help!
