### ISSUE TITLE
Minimal json 1.9.5

### ISSUE THREAD

**Issue by wimjongman** [eclipse/ditto#123]
Hi, I see that you use minimal json 1.9.5. Can you point me to the CQ so that our project can piggyback and maybe get mj 1.9.5 in Orbit.

**Comment by thjaeckle** [comment]
Hi.
We currently only have a CQ for 0.9.4: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14463
As we still are in incubation and don't have a release yet, we still have "Type A" "IP Due Diligence Type".
That's why we didn't make a CQ yet for 0.9.5.
