### ISSUE TITLE
Consider allowing a dash (-) in the namespace

### ISSUE THREAD

**Issue by ctron** [eclipse/ditto#1231]
Currently Ditto does not allow to use a dash (`-`) as part of the namespace: https://www.eclipse.org/ditto/basic-namespaces-and-names.html

However, even in the example, DNS like names (which allows using dashes) are used:

* `org.eclipse.ditto`
* `com.google`

To my understanding, that rule came from the Java package naming, which also doesn't allow a dash, but underscores.

If that is the only reason, and there is no technical reason, I would ask to consider allowing dashes too. I don't think it violates the overall principal of IDs that Ditto follows:

> Due to the fact that those IDs often need to be set in the path of HTTP requests, we have restricted the set of allowed characters.

**Comment by thjaeckle** [comment]
We support this request and want to allow also using the dash in namespaces.
This change however will require a minor release, I suggest the upcoming 2.2.0 which is currently planned for end of this year.

**Comment by thjaeckle** [comment]
Fixed via #1234
