### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ashishagarwal7** [eclipse/ditto#1245]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:14 min
[INFO] Finished at: 2021-11-30T07:46:25Z
[INFO] Final Memory: 197M/1448M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "docker-build-image" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ditto-base-model: Compilation failure
[ERROR] /usr/src/mymaven/base/model/src/main/java/org/eclipse/ditto/base/model/acks/AbstractCommandAckRequestSetter.java:[89,29] incompatible types: bad return type in method reference
[ERROR]     ? extends C cannot be converted to C
[ERROR] 

I am getting the following compilation error:

**Comment by thjaeckle** [comment]
Which JDK are you using?

**Comment by ashishagarwal7** [comment]
openjdk version "11.0.11" 2021-04-20

**Comment by ashishagarwal7** [comment]
No, I didn't modify it.

**Comment by thjaeckle** [comment]
When you didn't modify the sources: why would you want to build Ditto in the first place?

Apart from that - sorry, no idea why this does not build on your machine - the current master builds successfully:
* on Jenkins: https://ci.eclipse.org/ditto/job/ditto-ci/
* on GitHub Actions: https://github.com/eclipse/ditto/actions/runs/1502652420

**Comment by ashishagarwal7** [comment]
> When you didn't modify the sources: why would you want to build Ditto in the first place?

I didn't get your question?

**Comment by thjaeckle** [comment]
> I didn't get your question?

Why do you need to build Ditto? You don't need to build it to use it - simply start the Docker images.
The only reason to build it is when you modified the code - which you didn't.

**Comment by ashishagarwal7** [comment]
Thanks now it is working
