### ISSUE TITLE
Ditto rejects kafka bootstrap host ending with dot

### ISSUE THREAD

**Issue by ctron** [eclipse/ditto#1247]
When configuring a Kafka source through the devops endpoint, Ditto reject a bootstrap server, which has a host name ending with a dot, as invalid.

Example: `foo.bar.baz.:9092`.

Also see: http://www.dns-sd.org/trailingdotsindomainnames.html

This feature comes in useful in a Kubernetes environment, as it specifies rather long list of search domains, which may not be necessary.

**Comment by thjaeckle** [comment]
Probably the defined pattern does not respect that:

https://github.com/eclipse/ditto/blob/master/connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/kafka/KafkaBootstrapServerSpecificConfig.java#L40-L43
