### ISSUE TITLE
Connectivity mapped messages not triggering twin event

### ISSUE THREAD

**Issue by tobias-zeptio** [eclipse/ditto#1263]
I have setup a AMQP 1.0 connection with a source and a target. The target is configured for the topic `"_/_/things/twin/events"`.

The issue is that changes made through the AMQP source mapper are not triggering these twin event to the target, while http PUT calls are. The AMQP mapper is using the `mapToDittoProtocolMsg` to multiple `buildDittoProtocolMsg` modify commands.

Is this intended behavior? I can't find anything about it in the documentation.

**Comment by geglock** [comment]
This is the intended way to prevent "loopbacks". Events are published to all others but not the original sender/source. Thus in you setup you would need two different managed connections: one with a source and the other with a target.

This concept is at least documented here: https://www.eclipse.org/ditto/basic-signals.html#communication-pattern

I would propose to close this issue.

**Comment by tobias-zeptio** [comment]
Ah, makes sense and is pretty clever. :)
