### ISSUE TITLE
Entity id used instead of entity name in the documentation

### ISSUE THREAD

**Issue by dimitar-dimitrow** [eclipse/ditto#1266]
Topic path documentation was changed to use entity name instead of id - #819. However it is missed here - 
https://www.eclipse.org/ditto/basic-placeholders.html#scope-rql-expressions-when-filtering-for-ditto-protocol-messages (see topic:full). Also it is a bit misleading here in the provided example - https://www.eclipse.org/ditto/basic-thing.html#example (see "thingId": "the.namespace:**theId**"), guess  something like **theName** will be more appropriate.

**Comment by thjaeckle** [comment]
I agree 👍
