### ISSUE TITLE
`time:now` is not available in header mapping

### ISSUE THREAD

**Issue by ctron** [eclipse/ditto#1291]
The documentation indicates that the placeholder `{{ time:now }}` is available for header mappings: https://www.eclipse.org/ditto/basic-placeholders.html#scope-connections

However, using this feature when creating and outbound connection, results in the following result:

```
[2022-01-24T12:52:09Z DEBUG drogue_cloud_ditto_registry_operator::ditto::client] Response: Object({
        "connectivity": Object({
            "ditto-connectivity-57545b9f8c-2q7dd": Object({
                "status": Number(
                    400,
                ),
                "error": String(
                    "connectivity:connection.configuration.invalid",
                ),
                "message": String(
                    "The placeholder 'time:now' could not be resolved.",
                ),
                "description": String(
                    "Some placeholders could not be resolved. Check the spelling of the placeholder and make sure all required headers are set.",
                ),
            }),
        }),
    })
```

**Comment by ctron** [comment]
It looks like this was introduced in 2.3, and I am still on 2.2.

What might be helpful is to add a "since" field in the documentation for things like that.

**Comment by thjaeckle** [comment]
Aah, that's what the "version" picker in the documentation is already for:
![image](https://user-images.githubusercontent.com/1331526/150794667-fece19ef-f620-4b83-b11b-563f7935c8f4.png)
