### ISSUE TITLE
Incorrect link to Release notes 2.3.2

### ISSUE THREAD

**Issue by desislava-marinova** [eclipse/ditto#1311]
The Release notes link in the https://github.com/eclipse/ditto/releases/tag/2.3.2 points to Release notes 2.2.2
![image](https://user-images.githubusercontent.com/32883994/153851063-7bae60ed-5ce4-40ed-9a0a-84c94a25607e.png)

**Comment by thjaeckle** [comment]
Thx, fixed 👍
