### ISSUE TITLE
function expression fn:substring-after returning incorrect data

### ISSUE THREAD

**Issue by PaulWojcik-TMMC** [eclipse/ditto#1345]
The following function fn:substring-after('node/')  applied to : "node/1234"

returns "ode/1234" instead of "1234"

Documentation states the following: 
Parses the result of the previous expression and passes along only the characters after the first occurrence of givenString.

**Comment by thjaeckle** [comment]
Thx @PaulWojcik-TMMC 
You are right - that is a bug indeed!

The substring-after assumes that the length of the "splitter" is 1, so it e.g. only expects a single `':'`.
That's wrong.

Same is probably also true for the `fn:substring-after()` function.
