### ISSUE TITLE
AMQP message reject  send from hono to ditto 

### ISSUE THREAD

**Issue by mhumoglu** [eclipse/ditto#137]
Hi All,

I connected between hono and ditto on AMQP bridge.

 But I cant send AMQP message ( add thing etc.)  from hono to ditto using hono.vertx.example.HonoTelemetrySender (I modifed json object).
I took following exception.
-------------------------------------------------------------------------------------------------------------------------------------------
amqp-bridge_1    | 2018-04-04 12:40:23,616 INFO  [ID:AMQP_NO_PREFIX:TelemetrySenderImpl-14] o.e.d.s.a.m.CommandProcessorActor akka://ditto-cluster/system/sharding/amqp-connection/28/honoverysecrethono/pa/amqpCommandProcessor-honoverysecrethono - Got DittoRuntimeException 'things:thing.notmodifiable' when command via AMQP was processed: The Thing with ID 'appstacle:xdk_14' could not be modified as the requester had insufficient permissions (WRITE is required).
-------------------------------------------------------------------------------------------------------------------------------------------

Policy information:
}
"entries": {
      "owner": {
        "subjects": {
          "nginx:ditto": {
            "type": "nginx basic auth user"
          }
        },
        "resources": {
          "thing:/": {
            "grant": ["READ", "WRITE","ADMINISTRATE"],
            "revoke": ["READ", "WRITE","ADMINISTRATE"]
          },
          "policy:/": {
            "grant": ["READ", "WRITE","ADMINISTRATE"],
            "revoke": []
          },
          "message:/": {
            "grant": ["READ", "WRITE","ADMINISTRATE"],
            "revoke": ["READ", "WRITE","ADMINISTRATE"]
          }
        }
      }
    },
	"modified" : true
}
-------------------------------------------------------------------------------------------------------------------------------------------
sender code :
messageSender.send(HonoExampleConstants.DEVICE_ID, null, "{\"topic\": \"appstacle/xdk_"+value+"/things/twin/commands/create/\",\"headers\": {},\"path\": \"/\",\"value\": {\"__schemaVersion\": 2,\"__lifecycle\": \"ACTIVE\",\"_revision\": 1,\"_namespace\": \"appstacle\",\"thingId\": \"appstacle:xdk_"+value+"\",\"policyId\": \"appstacle:policy_deneme14\",\"attributes\": {\"location\": {\"latitude\": 44.673856,\"longitude\": 8.261719}},\"features\": {\"accelerometer\": {\"properties\": {\"x\": 3.141,\"y\": 2.718, \"z\": 1,\"unit\": \"g\"}}}}}", "application/json",
            token, capacityAvail -> {
                capacityAvailableFuture.complete(null);
            }).map(delivery -> {
                nrMessageDeliverySucceeded.incrementAndGet();
                messageDeliveredFuture.complete(null);
                return (Void) null;
            }).otherwise(t -> {
                System.err.println("Could not send message: " + t.getMessage());
                nrMessageDeliveryFailed.incrementAndGet();
                result.completeExceptionally(t);
                return (Void) null;
            });

Regards.

**Comment by jokraehe** [comment]
Hi @mhumoglu 

the authorization subject "nginx:ditto" has no effective permission to WRITE a Thing using the Policy from your example. You are granting and revoking WRITE at the same time and a revoke is always considered stronger within ditto.
Assuming that "nginx:ditto" is configured as the authorization subject for the amqp connection, removing the revoked permissions on the thing:/ resource should fix it.

Regards,
Johannes

**Comment by jokraehe** [comment]
The Thing you want to create references a Policy with ID `appstacle:policy_deneme14` but the Policy you provided has another ID `appstacle:deneme2`. I think it's a typo and you should reference `appstacle:deneme2` in your Thing.

**Comment by mhumoglu** [comment]
I created new policy( appstacle:deneme2) for testing  two different policy but same json object.

**Telementry sender code :** 

messageSender.send(HonoExampleConstants.DEVICE_ID, null, "{"topic": "appstacle/xdk_"+value+"/things/twin/commands/create/","headers": {},"path": "/","value": {"__schemaVersion": 2,"__lifecycle": "ACTIVE","_revision": 1,"namespace": "appstacle","thingId": "appstacle:xdk"+value+"","policyId": "appstacle:deneme2","attributes": {"location": {"latitude": 44.673856,"longitude": 8.261719}},"features": {"accelerometer": {"properties": {"x": 3.141,"y": 2.718, "z": 1,"unit": "g"}}}}}", "application/json",
token, capacityAvail -> {
capacityAvailableFuture.complete(null);
}).map(delivery -> {
nrMessageDeliverySucceeded.incrementAndGet();
messageDeliveredFuture.complete(null);
return (Void) null;
}).otherwise(t -> {
System.err.println("Could not send message: " + t.getMessage());
nrMessageDeliveryFailed.incrementAndGet();
result.completeExceptionally(t);
return (Void) null;
});


policy : 

{"policyId":"appstacle:deneme2","entries":{"owner":{"subjects":{"nginx:ditto":{"type":"nginx basic auth user"}},"resources":{"policy:/":{"grant":["READ","WRITE"],"revoke":[]},"thing:/":{"grant":["READ","WRITE"],"revoke":[]},"message:/":{"grant":["READ","WRITE"],"revoke":[]}}},"observer":{"subjects":{"nginx:some-users":{"type":"a group of users"},"nginx:observer-client":{"type":"technical client"}},"resources":{"thing:/features/featureY":{"grant":["READ"],"revoke":[]},"thing:/features/featureX":{"grant":["READ"],"revoke":[]}}}}}

**Comment by jokraehe** [comment]
Which authorization subject did you configure in the amqp connection? `nginx:ditto`?

**Comment by mhumoglu** [comment]
I wrote ADMINISTRATE in authorization subject . I've written  "nginx:ditto" in authorization subject and it's running now.

Thank you for your interest

Regards
