### ISSUE TITLE
Get "iothub-connection-device-id" in Azure IoT Hub connection using AMQP 1.0

### ISSUE THREAD

**Issue by dimabarbul** [eclipse/ditto#1389]
I try to integrate Azure IoT Hub with Ditto, in particular I want to send telemetry from IoT Hub to Ditto.

I created following AMQP 1.0 connection:
```json
{
	"connectionStatus" : "open",
	"connectionType" : "amqp-10",
	"failoverEnabled" : true,
	"id" : "IoTHub-Ditto",
	"mappingDefinitions" : {
	   "javascript" : {
		  "mappingEngine" : "JavaScript",
		  "options" : {
			 "incomingScript" : "function mapToDittoProtocolMsg(\n    headers,\n    textPayload,\n    bytePayload,\n    contentType\n) { \nif (headers[\"opType\"]) { return null;}\nvar path = \"/features/telemetry\";\nvar  value = { \n      properties: { value : textPayload, contentType: contentType}\n};\nvar params = headers[\"device-id\"].split(\":\");\nif(params.length != 2) return null;\nvar namespace = params[0];\nvar deviceId = params[1];\n\nreturn Ditto.buildDittoProtocolMsg(\n        namespace ,\n        deviceId,\n        \"things\",\n        \"twin\",\n        \"commands\",\n        \"modify\",\n        path,\n        headers,\n        value\n    );\n}"
		  }
	   }
	},
	"sources" : [
	   {
		  "addresses" : [
			 "iothub-ehub-****/ConsumerGroups/$Default/Partitions/0",
			 "iothub-ehub-****/ConsumerGroups/$Default/Partitions/1"
		  ],
		  "authorizationContext" : [
			 "nginx:ditto"
		  ],
		  "enforcement" : {
			 "filters" : [
				"{{ thing:id }}"
			 ],
			 "input" : "{{ header:device-id }}"
		  },
		  "payloadMapping" : [
			 "javascript"
		  ]
	   }
	],
	"uri" : "amqps://service:KEY@eventhub-compatible-namespace.servicebus.windows.net:5671"
}
```

What it does - it saves incoming message along with its content type to feature named "telemetry". Another connection will then pick up this event and process it (currently it forwards the telemetry to event hub).
Azure IoT Hub provides property "iothub-connection-device-id" which contains device ID that sent the message. This property is provided as message annotation on AMQP connection.

The problem is that I do not see message annotations in headers in payload mapping script or "enforcement" section. That's why "device-id" was introduced using Azure IoT Hub message enrichment feature with value "$twin.tags.deviceId". But this is a workaround and requires creating tag on each device.

So, how can I get device ID in this connection from message annotations?

_Note: forwarding telemetry using Azure IoT Hub message routing feature is not an option as there will be other devices connected to Ditto not through IoT Hub._

**Comment by Yannic92** [comment]
Ditto does not support AMQP message annotations. Only properties and application properties are extracted and put into the available headers.

If you need support for message annotations, this would be a topic for a pull request that could be discussed.

If you want to have a look first: This is the place where the headers are extracted currently: https://github.com/eclipse/ditto/blob/efb76399396576ad8e322a415102d26d5e2ed60c/connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/amqp/AmqpConsumerActor.java#L484

**Comment by dimabarbul** [comment]
Thanks for quick and full response.
As the original question has been answered I think we can close the ticket.
