### ISSUE TITLE
docker-compose configuration

### ISSUE THREAD

**Issue by StefanoMagni66** [eclipse/ditto#140]
Using docker version 18.03.0-ce and docker-compose 1.21.00 the docker-compose.yml "command" configuration is not overwritten.
This cause a wrong startup sequence of services and crash of all ditto services.

The "command" line have to be replaced with "entrypoint" configuration:

command: sh -c "sleep 10; java -jar /starter.jar"
entrypoint: sh -c "sleep 15; java -jar /opt/ditto/starter.jar"

**Comment by thjaeckle** [comment]
Hi Stefano.

Thanks for reporting 👍 we will look into it.

**Comment by thjaeckle** [comment]
We fixed that in #143 
The wrong command was only working for images built via Maven, not the official published ones.
Thanks again for reporting
