### ISSUE TITLE
Search does not work for _metadata

### ISSUE THREAD

**Issue by demetz** [eclipse/ditto#1404]
For every datapoint we have in ditto, we also set an according `_metadata` to specify the pysical `unit` , for example:
```json
{
  "features":{
     "HeatMeter":{
        "properties":{
           "status":{
              "energy":0
          }
       }
    }
   },
  "_metadata":{
     "features":{
        "HeatMeter":{
             "properties":{
                  "status":{
                        "energy":{
                            "unit":"Wh"
                         }
                  }
              }
          }
      }
 }
}
```

I was now trying to search for all things where the metadata is not correctly specified:
```
    GET /api/2/search/things?filter=and(
      exists(features/HeatMeter/properties/status/energy),
      eq(_metadata/features/HeatMeter/properties/status/energy/unit,'Wh')
    )
```

I was expecting to find above thing, however no result was returned

**Comment by stmaute** [comment]
Hi @demetz, we are currently working on the metadata feature and will provide the search functionality with one of the next releases. At the moment Ditto does not support searching for metadata.
