### ISSUE TITLE
Gaining  the history changes of a thing

### ISSUE THREAD

**Issue by CabenJL** [eclipse/ditto#1502]
If we modify the state of one thing, how can we get  the information of the last time? Moreover, if we modify the state frequently, how can we gain the history changes in order to  analysis these data?

**Comment by thjaeckle** [comment]
Hi @CabenJL 
Currently, you can't - currently Ditto only provides the "most recent" state via its API.
The history is however available in the "event journal" / in the database.

We created issue #1498 in order to start a discussion on whether this would be useful and would be happy to get some feedback over there.
E.g. for which use-case you require history changes of a thing and what kind of information or API you would expect.

**Comment by CabenJL** [comment]
@thjaeckle Thanks for your replay! I will make efforts to share our ideas about this issue in #1498. Besides, I have noticed that we are able to gather logs for a running Ditto installation in  description of the link https://www.eclipse.org/ditto/installation-operating.html#logging, so could we gain the history changes from the log file? Maybe this can be one way to do it?

**Comment by thjaeckle** [comment]
> Besides, I have noticed that we are able to gather logs for a running Ditto installation in description of the link https://www.eclipse.org/ditto/installation-operating.html#logging, so could we gain the history changes from the log file? Maybe this can be one way to do it?

Not in a reliable way, no.
If this is an option, you could of course create a [connection](https://www.eclipse.org/ditto/basic-connections.html) to push out all (change) events to the twin to another system where to process the history .. e.g. to an HTTP endpoint or via an Apache Kafka.
That would be the most reliable way to get the "history".

**Comment by CabenJL** [comment]
@thjaeckle Thanks! We will try to share our ideas in issue #1498 in a few days, we are expecting one specific API that can help to gain the history data.

**Comment by hjccjugfcc** [comment]
Hello, we find that the historical data in ditto is queried in the things-journal table of the mongodb database in docker, but we also find that these historical data will be deleted every fixed time, and only the latest updated data is retained in the database. We want to know, can this fixed time be modified ? If it can be modified, where should it be modified ?
![d87589495a9a74b6750c8c7fc49ce02](https://user-images.githubusercontent.com/91953397/197982504-e0e41c60-53c2-4eb9-a73d-a45b499ea476.jpg)
![3c1461ac745bf28746bddc246d29132](https://user-images.githubusercontent.com/91953397/197982524-73223cb1-1550-4d9a-ba2a-34c747292328.jpg)
