### ISSUE TITLE
Gateway authentication fails while accessing APIs

### ISSUE THREAD

**Issue by ishwar25667** [eclipse/ditto#1507]
Hi @thjaeckle 

I have setup eclipse ditto at local using docker/docker-compose. Services seems to be up but when I try to access any API getting-

"Gateway authentication fails"

See more details-

 curl -X 'GET' \
>   'http://localhost:8080/api/2/whoami' \
>   -H 'accept: application/json' \
>   -H 'Authorization: Basic ZGl0dG86ZGl0dG8=' \
>   -H 'x-ditto-pre-authenticated: nginx:ditto'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136  100   136    0     0    510      0 --:--:-- --:--:-- --:--:--   521{"status":401,"error":"gateway:authentication.failed","message":"Unauthorized.","description":"Check if your credentials were correct."}

I am missing something? Please help here.

**Comment by thjaeckle** [comment]
You seem to have wrong line breaks in your curl statement .. works for me doing:
```bash
curl -X 'GET' 'http://localhost:8080/api/2/whoami' -H 'accept: application/json' -H 'Authorization: Basic ZGl0dG86ZGl0dG8='
```
