### ISSUE TITLE
Fix broken documentation links

### ISSUE THREAD

**Issue by kvico** [eclipse/ditto#152]
The following internal documentation links are broken:
```basic-connections.md``` 
* ```[Manage connections](/connectivity-manage-connections.html)``` 
* ```[Payload Mapping Documentation](/connectivity-mapping.html)```

```connectivity-manage-connections.md```:
* ```[payload mapping](/connectivity-mapping.html)```
* ```[Connections](/basic-connections.html)```

**Comment by thjaeckle** [comment]
Thanks for reporting, Vico .. we'll look into it

**Comment by thjaeckle** [comment]
Fixed it, thanks again 👍
