### ISSUE TITLE
Use Akka artery remoting as replacement for Netty 3.10

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#161]
We cannot use Netty 3.10 due to licensing issues (as mentioned in [CQ 16316](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16316)).
As Netty 3.10 is used by default by Akka and that won't change (as mentioned in [this Akka issue](https://github.com/akka/akka/issues/23733#issuecomment-340480247)) we have to use the UDP (or TCP)-based Aeron remoting as a replacement (which is stable in our used Akka version).

Netty 3.10 must then be excluded from our dependencies.

**Comment by thjaeckle** [comment]
Blocked by https://github.com/eclipse/openj9/issues/2000

**Comment by thjaeckle** [comment]
Also opened a ticket at Akka as they rely on the Hotspot JVM specific behavior of `String`:
https://github.com/akka/akka/issues/25161

Staying on Netty is not an option (due to the mentioned licensing issues), so if neither OpenJ9 nor Akka supports this in a way, we have no choice but to use OpenJDK + Hotspot JVM again.

**Comment by thjaeckle** [comment]
Waiting until Akka 2.5.14 which fixes our issue on OpenJ9.

**Comment by thjaeckle** [comment]
In order to use the new remoting we have to have a discussion first:
* what limits to we apply on Thing/Policy sizes? we have to have a limit and the bigger it is the more problems we get in remoting (e.g. because we have to "reserve" the native memory aeron remoting uses )
* I would vote for rather small limits (KiB vs. MiB)
** AWS IoT has a limit of 8 KiB per "shadow" (where 4 KiB is for desired and 4 KiB for actual state)
** Azure IoT Hub for example has a limit of 256 KiB per "message" device-to-cloud and 64 KiB per message cloud-to-device

as 256 KiB are already ~ 10.000 lines in a rather complex JSON genereated with [this tool](https://www.json-generator.com/) and I doubt that this makes sense for a digital twin in our scope, I would even limit it further

My proposal:
Thing/Policy size limit: **64 KiB**
Search response limit to get with one search request: **256 KiB**
Message size limit: **256 KiB**

**Comment by danielFesenmeyer** [comment]
Nice research 👍 I think your proposed limitations are a good compromise.

Just two remarks/questions (I'm not sure whether this is easily possible):
* Thing responses might actually have 2*64 KiB size, when the "_policy" fields is specified
* For search responses I would calculate the maximum response size based on the requested item count if possible (I think currently the maximum allowed item count is 200). I.e., max = (requested item count) * maxThingPayload. Where maxThingPayload might be 2*64 KiB if we support the "_policy" field selector for search.

**Comment by thjaeckle** [comment]
Indeed, you're right with the "_policy" field - when we enforce this limit, we would have to look into a Thing to create and check for the "_policy" field - if it is present, 2*64 KiB may be used.
When retrieving a Thing with "_policy" this should not be a problem as we would have to configure the max. cluster message size to a higher value in any case (e.g. to the proposed 256 KiB for messages).

Hm, the search is a problem - 200*2*64 KiB are 25 MiB.
To configure such a huge cluster message size would cost us a lot of memory to reserve.
Therefore I would rather report an error (something like "result set to large, please consider selecting only required fields or use a smaller page size") to the user when a search result gets bigger than 256 KiB.
This is a corner case - someone who has such big Things (64KiB ~ 2.500 lines in a complex JSON) has to do compromises IMHO.

**Comment by danielFesenmeyer** [comment]
I see. I actually do not yet know the config options of the new remoting. Limiting the search responses to 256 kiB and returning an appropriate error sounds ok if there is no simple other solution.

**Comment by yufei-cai** [comment]
We could stream search result inside the cluster (200 x 64 KiB messages instead of 1 x 25 MiB message).

It'd enable [JSON streaming](https://doc.akka.io/docs/akka-http/current/routing-dsl/source-streaming-support.html) for search queries with large amounts of results.

**Comment by thjaeckle** [comment]
Currently blocked by https://github.com/akka/akka/issues/25469

**Comment by danielFesenmeyer** [comment]
Status update: Akka 2.5.17 has been released last week: https://akka.io/blog/news/2018/09/27/akka-2.5.17-released
