### ISSUE TITLE
Ditto get twin with "_revision"

### ISSUE THREAD

**Issue by mhumoglu** [eclipse/ditto#174]
Hi All,

I want to get values of any twin with "_revision".

how can I do that ? or can this be ?

Regards 

Mhumoglu

**Comment by thjaeckle** [comment]
Only the twin has a twin-global "_revision" - the single values of the twin don't have a revision on their own.

At the HTTP-API you can simply query with the "fields" parameter for the revision, e.g.:
```
GET /api/2/things/your-namespace:your-id?fields=thingId,attributes,_revision
```

**Comment by mhumoglu** [comment]
I can't run the code below or similar codes( eq(_revision,54) )
As far as I understand
GET  /api/2/things/your-namespace:your-id?fields=_revision=51'

**Comment by thjaeckle** [comment]
Ah, you want to access the Twin in a specific `_revision`.
That is currently not possible, sorry.
You can only access the current version.

The `_revision` is only a marker for reading it only.

**Comment by mhumoglu** [comment]
Okay . Last a question :) does ditto has value of before update twin?

**Comment by thjaeckle** [comment]
No, unfortunately it does not provide that at an API level.
The historical/old values are in the persistence - but are not accessible via API.
