### ISSUE TITLE
error: Not supported platform found in manifest list

### ISSUE THREAD

**Issue by pankeshlinux** [eclipse/ditto#181]
Hi,

I have been firing `docker-compose up -d`.  I am facing the following error.  I am trying to install it on Ubuntu, virtual machine

![image](https://user-images.githubusercontent.com/1482917/41629642-a871038c-73f8-11e8-9046-9af092169ba7.png)

**Comment by pankeshlinux** [comment]
It seems that it is a mongodb and virtualbox problem. See this [report](https://github.com/docker-library/mongo/issues/232). I think in Readme file, we should explicitly mention that ditto may not be run on virtual machine ubuntu.

**Comment by thjaeckle** [comment]
closing due to inactivty, please re-open if the question is not answered
