### ISSUE TITLE
Problem While connecting Eclipse Ditto and Hono

### ISSUE THREAD

**Issue by shailesharya** [eclipse/ditto#212]
Hey There,
I'm trying to connect Eclipse Ditto and Hono but I'm getting following error
![2018-08-16 5](https://user-images.githubusercontent.com/41483772/44204756-a49e1500-a171-11e8-8107-d28f92135e04.png)
Can anyone help me with this?
Thanks.

**Comment by thjaeckle** [comment]
Hi.
You are absolutely right, we did not yet deploy out latest release from this week to our sandbox https://ditto.eclipse.org
Thank you for finding out that way :)
We just deployed the latest release in the sandbox which means you should now be able to create the connection.
Could you please try it out and give us feedback if it worked?

Regards
Thomas

**Comment by shailesharya** [comment]
![2018-08-16 9 _li](https://user-images.githubusercontent.com/41483772/44212795-f357a900-a189-11e8-89c6-adde064cdc4d.jpg)
It says connecting already created
thanks for your help, sir.

**Comment by shailesharya** [comment]
![2018-08-16 10](https://user-images.githubusercontent.com/41483772/44213920-87c30b00-a18c-11e8-8184-44bb24c9f88b.png)
![2018-08-16 11](https://user-images.githubusercontent.com/41483772/44213922-885ba180-a18c-11e8-9b25-f365881f98c0.png)

again it says invalid JSON format while creating payload mapping.

**Comment by thjaeckle** [comment]
probably because it is no valid JSON .. did you try as suggested validating the JSON on jsonlint.com ?

**Comment by shailesharya** [comment]
I did and it's valid and now I'm getting this
![screenshot 2](https://user-images.githubusercontent.com/41483772/44223236-a7fec400-a1a4-11e8-95da-5763f3c8dbf4.png)
I'm very close to connecting Hono and Ditto so will you please help me out?
HTTP 502 bad gateway means the server is down or what?
