### ISSUE TITLE
Connecting Eclipse Hono and Ditto

### ISSUE THREAD

**Issue by shailesharya** [eclipse/ditto#214]
Hey there,
I'm very close on connecting Eclipse Ditto and Hono the only thing left is making connection b/w hono and ditto but I'm having error says that HTTP 1.1 Bad Gateway
![screenshot 5](https://user-images.githubusercontent.com/41483772/44248521-9d761600-a208-11e8-87ab-a50a09261a51.png)
I'm having this issue while checking the status of the connection and also while opening the new connection using piggyback commands.
please help me out.
thank you.

**Comment by ffendt** [comment]
Hi there,

It seems as if the sandbox environment ran into memory issues which caused docker to kill some containers. I restarted the stack, so it shouldn't respond with 502 for now. 
Could you please try again and tell us if the connection to Hono still fails?

As for the memory issues: The sandbox environment has very limited resources to work with. We will investigate in how we can stabilize it.

**Comment by shailesharya** [comment]
Thanks for your help, sir.
It's working fine now.

**Comment by shailesharya** [comment]
Is there a way to connect Eclipse Hono and Ditto without using sandbox?
