### ISSUE TITLE
Documented docker-compose version is too low

### ISSUE THREAD

**Issue by yufei-cai** [eclipse/ditto#217]
[Documentation](https://github.com/eclipse/ditto/blob/4f87d4cd6c79aae437ea313f0e9520334bb57126/documentation/src/main/resources/pages/ditto/installation-running.md) says docker-compose v1.14 is enough, but the [compose file](https://github.com/eclipse/ditto/blob/4f87d4cd6c79aae437ea313f0e9520334bb57126/docker/docker-compose.yml) is version 2.4, which requires docker-compose 1.21.

**Comment by thjaeckle** [comment]
[README.md](https://github.com/eclipse/ditto/blob/master/README.md) already has it right
