### ISSUE TITLE
Add MQTT support

### ISSUE THREAD

**Issue by yufei-cai** [eclipse/ditto#220]
MQTT is a super popular IoT protocol, Ditto should definitely support it!

Interoperability with [Amazon IoT](https://aws.amazon.com/iot/) weren't half bad either.

**Comment by thjaeckle** [comment]
Can this be closed? Should be fixed by #224

**Comment by yufei-cai** [comment]
#224 does not interoperate with Amazon IoT due to lack of client certificate authentication.

**Comment by yufei-cai** [comment]
Fixed by #235.
