### ISSUE TITLE
Reconnect not working correctly for AMQP 0.9.1 Connections

### ISSUE THREAD

**Issue by ffendt** [eclipse/ditto#228]
When playing around with AMQP 0.9.1 Connections, i found a bug in the reconnect mechanisms of Ditto.

If the AMQP broker (to which a connection is pointing) is unreachable for a while, Ditto will try to reestablish the connection and finally succeed when the broker is reachable again. 
However, after the connection is established, consuming or publishing won't work for the connection until the service is restarted.

**Comment by jufickel-b** [comment]
Closed with PR https://github.com/eclipse/ditto/pull/230.
