### ISSUE TITLE
The server does not support the HTTP protocol version used in the request

### ISSUE THREAD

**Issue by shailesharya** [eclipse/ditto#254]
![screenshot 49](https://user-images.githubusercontent.com/41483772/46686522-2ceee280-cc16-11e8-8379-d948e1926f8e.png)
what does this mean when firing query?

**Comment by jokraehe** [comment]
I think the whitespaces in your URL is causing this error. Try http://localhost:8080/api/1/search/things...

**Comment by shailesharya** [comment]
done!!
thanks for your help.
