### ISSUE TITLE
Support for CBOR as a format describing Ditto Payload

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/ditto#255]
With the ditto protocol, the device would need to send as JSON format.
This is costly for typical devices.

It would be interesting for the Ditto format to be describable via CBOR (http://cbor.io/) so that devices have better opportunities to offer the ditto format directly from the device.

**Comment by geglock** [comment]
We could simply add support for it by providing access to a CBOR javascript library (like https://github.com/paroga/cbor-js) within the [payload mapping](https://www.eclipse.org/ditto/connectivity-mapping.html) in Ditto. What do you think about this?

**Comment by thjaeckle** [comment]
Also - keep in mind that devices typically do not connect to Ditto directly and should not be aware of Ditto at all.
Devices connect to a MQTT broker or to Hono for example, so using the payload mapping when consuming messages from those would be the way to go.

**Comment by zubairhamed** [comment]
@geglock  Yeah i think that might work. worth a try.

Z
