### ISSUE TITLE
Subject Id invalid during create thing on sandbox via websocket

### ISSUE THREAD

**Issue by wem** [eclipse/ditto#258]
We try to create a thing via websocket protocol binding on new sandbox installation. 
With the payload:
{
  "topic" : "com.example.iot/qemu_x86/things/twin/commands/create",
  "headers" : {
    "correlation-id" : "2215ea11-dbe5-413e-a783-24ec9c9f9619",
    "response-required" : true,
    "content-type" : "application/json",
    "auth-subjects" : [ "nginx:ditto" ],
    "version" : 2
  },
  "path" : "/",
  "value" : {
    "thingId" : "com.example.iot:qemu_x86",
    "features" : {
      "urn:oma:lwm2m:ext:1" : {
        "properties" : {
          "0" : 1,
          "1" : 30,
          "2" : 0,
          "3" : 0,
          "5" : 86400,
          "6" : false,
          "7" : "U"
        }
      },
      "urn:oma:lwm2m:ext:3303" : {
        "properties" : {
          "5601" : 25.0,
          "5602" : 25.0,
          "5603" : 0.0,
          "5700" : 25.0,
          "5604" : 0.0,
          "5701" : ""
        }
      },
      "urn:oma:lwm2m:ext:5" : {
        "properties" : {
          "1" : "",
          "9" : 2,
          "3" : 0,
          "5" : 0
        }
      },
      "urn:oma:lwm2m:ext:3" : {
        "properties" : {
          "0" : "Zephyr",
          "1" : "OMA-LWM2M Sample Client",
          "2" : "345000123",
          "3" : "1.0",
          "6_0" : 1,
          "6_1" : 5,
          "7_0" : 3800,
          "7_1" : 5000,
          "8_0" : 125,
          "8_1" : 900,
          "9" : 95,
          "10" : 15,
          "13" : 7932000,
          "16" : "U",
          "17" : "OMA-LWM2M Client",
          "18" : "1.0.1",
          "20" : 1,
          "21" : 25
        }
      }
    }
  }
}

We get the following error: 
{"topic":"unknown/unknown/things/twin/errors","headers":{"content-type":"application/vnd.eclipse.ditto+json"},"path":"/","value":{"status":400,"error":"policies:subjectid.invalid","message":"Subject ID 'ditto' is not valid!","description":"It must contain an issuer as prefix separated by a colon ':' from the actual subject"},"status":400}

I would be glad about any advice

**Comment by danielFesenmeyer** [comment]
How did you open the websocket? On path _/ws/1_ or _/ws/2_? It might happen when you opened it on path _/ws/1_.

**Comment by wem** [comment]
Hi
The problem is solved, but i don't know really why. I did connect to /ws/2 at anytime, but a day later it worked :)

Thanks for help in anyway.

**Comment by SaminaZahidFulda** [comment]
hi. Can you please share the complete code ?
