### ISSUE TITLE
Server Sent Events(SSEs) error

### ISSUE THREAD

**Issue by shailesharya** [eclipse/ditto#259]
hey there,
please anyone can tell what's wrong with this SSE
![screenshot 51](https://user-images.githubusercontent.com/41483772/46822178-67888480-cda8-11e8-8012-6b37a5b8da7d.png)
![screenshot 52](https://user-images.githubusercontent.com/41483772/46822185-6b1c0b80-cda8-11e8-9441-b2e3737beb16.png)
thanks

**Comment by jokraehe** [comment]
You have to authenticate the request. You can do it by specifying the withCredentials option like this `let source = new
  EventSource('http://localhost:8080/api/1/things?ids=org.eclipse.ditto:fancy-thing&fields=thingId,features/lamp', {
    withCredentials: true});`
You might run into issues serving the html directly from the filesystem. Try a small http server like https://www.npmjs.com/package/http-server.

**Comment by shailesharya** [comment]
source = new EventSource('http://localhost:8080/api/1/things?ids=org.eclipse.ditto:fancy-thing&fields=thingId,features/lamp', { withCredentials: true});
this worked!!
thanks for your help.
