### ISSUE TITLE
Provide APIs to apply merge updates to a thing without affecting existing parts

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/ditto#288]
Hi,

is there a way to update multiple parts of a twin/thing without affecting the entire thing using the ditto protocol?

example:
- sending an update to path "/" would mean:
a) overwriting parts which may not be desired to be update (e..g the vorto "definition")
b) updating static properties such as attribute

if i want to update say 10 datapoints on a thing, this would mean making 10 calls to the individual features. the updating client needs to know everything about the thing including all the meta information..

solution: maybe: its possible to send an array of commands for path and value instead of singular values?

Or is there anothe way to do so?

Z

**Comment by jufickel-b** [comment]
Hi Zubair,

You can locally update your Features and send them as a whole to .../<thing-id>/features. The same applies to Attributes. 

Kind regards

Jürgen

**Comment by zubairhamed** [comment]
Woudn't this wipe off any data which in this case don't want to? e.g. "definition"?
This would mean the "local update" would need additional meta information prior to the update, no?

**Comment by jufickel-b** [comment]
You are right, PUT overwrites all existing Features. Therefore you should GET them beforehand to have the most recent state before updating them. To avoid lost updates in case of several clients you could harness [ETags](https://www.eclipse.org/ditto/httpapi-concepts.html).

**Comment by zubairhamed** [comment]
Hi Juergen,

Thanks for the speedy replies.

Unfortunately doing a GET prior to a PUT all the time is not feasible at all.

1. If a device uses the DITTO protocol and it needs to update multiple sensor values (be it via Hono or directly to Ditto), doing a GET all the time is not feasible. 
2. If it isn't sending via Ditto and it sends over a few bytes of byte array which needs to be unpacked into multiple bytes, the Ditto Mapping engine doesn't allow doing a GET anyway prior to update. Additionally you can't use this to do multiple update calls either.
3. If using the Hono-Ditto bridge, this would mean the device would additionally need connectivity to IoT Things and apiTokens etc to do this.

So its much safer to allow the Ditto protocol to allow explicit update of multiple values in a single call.

Z

**Comment by Yannic92** [comment]
Hi Zubair,

unfortunately currently we don't support something like a PATCH request that allows to update a thing partially.
You're currently required to do multiple PUT requests (ModifyFeature/ModifyAttribute commands) to the respective Attributes/Features if a GET is not possible.
For Features you can even do a PUT request to /things/{thingId}/features/{featureId}/properties (ModifyFeatureProperties) or  /things/{thingId}/features/{featureId}/properties/{propertyPath} (ModifyFeatureProperty).

But I guess you're already aware of this and that's what you meant when you said 

> "if i want to update say 10 datapoints on a thing, this would mean making 10 calls to the individual features".

I'm sorry that I can't give you a more satisfying answer.

**Comment by thjaeckle** [comment]
Thanks Zubair for reporting.

We already thought about adding such a "PATCH" metaphor - or additionally support sending multiple Ditto commands aggregated in one message (which you also suggested - that would be easier, so we'll also track that in another issue).

We will use this issue for further discussion and tracking the feature.

Our thoughts were that we not only support this for the Ditto Protocol, but also for the HTTP-API.
That way you could do a HTTP PATCH request (e.g. with [JsonPatch](http://jsonpatch.com)) and only modify very selectively.

**Comment by moebigit** [comment]
Hello everybody

I have a similar use case where I would like to send telemetry messages to the hub in ditto format which then updates my thing but only the respective features of my thing.
For optimization I won't send all features with every message - only the ones that have changed, and I also don't want to send individual messages for each property change to keep the number of requests to a minimum.

In my case, either being able to merge my feature structure with the current Twin state would be helpful or being able to provide multiple "path/value"-combinations inside the ditto message.

**Comment by thjaeckle** [comment]
Sure, still a very valid feature request.
We currently more think about a new verb in the Ditto Protocol (we currently have: create, delete, modify, read): *merge*
That - differently than "modify" - would only update the parts which were specified in the payload and leave the other parts of the thing (or feature, property etc.) JSON intact.

At the HTTP API this could be a POST for *merge* instead of a PUT (for modify).

That would be easier to use than a JSON Patch or than specifying multiple path/value entries.
What do you think?

**Comment by BobClaerhout** [comment]
Hi all,
It looks like we are in need of this feature as well. Any updates on this?
Personally I'm in favor for the new verb in the Ditto Protocol and _merge_ seems like a perfect one!

**Comment by thjaeckle** [comment]
The feature definitely will be coming, it's "just" a question about prioritization and resources ;)

So I can't really say when this issue will be done.
Currently I don't see it in Ditto 1.1.0, if you want to start contributing on it, we could definitely support when problems arise :)

On a conceptual level it is quite clear how to add this to Ditto and there should be no major "roadblocks" when implementing.

For the implementation I see 2 options:
* either copy all `Modify*` command (maybe also event) classes to their `Merge*` counterpart classes
   * e.g.: `ModifyThing` ->copy-> `MergeThing`
   * add separate persistence strategies as well in `org.eclipse.ditto.services.things.persistence.actors.strategies.commands.ThingCommandStrategies`
   * add separate concierge enforcements
   * this would be very many changes towards LoC, duplicated unit tests, etc.
* or: make `Modify*` command (maybe also the event) classes aware of whether "replace" or "merge" semantics should be applied
   * also persistence strategies must make use of that differentiation
   * concierge enforcement should not be affected

I prefer the second one but am not yet sure if this will work everywhere.

**Comment by thjaeckle** [comment]
Currently planned for Ditto 1.2.0

**Comment by thjaeckle** [comment]
I would suggest for HTTP to use the `PATCH` verb and to implement [JSON Merge Patch RFC](https://tools.ietf.org/html/rfc7396) which is waaay easier than the mighty [JSON Patch](http://jsonpatch.com).
This article nails it IMO: https://apisyouwonthate.com/blog/put-vs-patch-vs-json-patch

**Comment by e-grigorov** [comment]
I checked the linked RFC document and would like to access some topics:
* I am curious how do you plan to address some of the limitations of JSON merge patch like null values?
* How do you envision the events? Currently, the events are somehow self-contained and easy to be consumed. I guess that the even consumer will continue to use them without merge complications, right?
* I guess that the merge will work in an atomic way. How many events can be produced from single merge request?

**Comment by stmaute** [comment]
Hi @e-grigorov,

i will try to answer your questions. 

> I am curious how do you plan to address some of the limitations of JSON merge patch like null values?

Regarding the `null` value we have implemented the spec in the RFC. This means that setting `null` for a key will delete this from the object.
The following example should clarify this:
Given the following example JSON document:
```
{
     "title": "Goodbye!",
     "author" : {
       "givenName" : "John",
       "familyName" : "Doe"
     },
     "tags":[ "example", "sample" ],
     "content": "This will be unchanged"
}
```
Applying the following PATCH   
PATCH /my/resource HTTP/1.1
Host: example.org
Content-Type: application/merge-patch+json
```
{
     "title": "Hello!",
     "phoneNumber": "+01-123-456-7890",
     "author": {
       "familyName": null
     },
     "tags": [ "example" ]
}
```
 The resulting JSON document would be:
```
 {
     "title": "Hello!",
     "author" : {
       "givenName" : "John"
     },
     "tags": [ "example" ],
     "content": "This will be unchanged",
     "phoneNumber": "+01-123-456-7890"
 }
```
I hope this makes it more clear how `null` values are handled.

> How do you envision the events? Currently, the events are somehow self-contained and easy to be consumed. I guess that the even consumer will continue to use them without merge complications, right?

There will be only one ThingMerged event emitted after the merge was successfully applied.
This event contains the path were the patch was applied and the json value.

> I guess that the merge will work in an atomic way. How many events can be produced from single merge request?

Yes each merge command will apply the value from the request to the thing in an atomic way. You can use [conditional-requests](https://www.eclipse.org/ditto/httpapi-concepts.html#conditional-requests) to ensure the order who commands are applied.
So for example it is possible to add/update/delete some attributes and add/update/delete one or more features within a single request.

If you have more questions regarding this feature please let us know.

**Comment by e-grigorov** [comment]
> I hope this makes it more clear how null values are handled.

Actually, the question was how this limitation is addressed i.e. how to set null value with JSON merge patch? Null is a valid Ditto property value and should be supported. Is there any way to set such value with JSON merge patch?

> This event contains the path were the patch was applied and the json value.

If we take a concrete example:
`"OutdoorTemperature": {"properties": {"value": 18}},
"IndoorTemperature": {"properties": {"value": 22}}`
i.e. there are two temperature features and we apply patch like:
`"OutdoorTemperature": {"properties": {"value": 15}},
"IndoorTemperature": {"properties": {"value": 24}}`
What is the expected event? How it looks like?

To be honest, I have a little fear that there is no modified event. It seems incompatible change because the existing applications cannot rely only on modified events any more. What do you think about this scenario: features will be modified without modified event?

**Comment by stmaute** [comment]
> Actually, the question was how this limitation is addressed i.e. how to set null value with JSON merge patch? Null is a valid Ditto property value and should be supported. Is there any way to set such value with JSON merge patch?

When applying the merge commands you have to set **Content-Type: application/merge-patch+json**.  This content-type indicates that `null` values will be handled to delete entries from things. 


For every merge command an ThingMerged event is emitted with the path of the thing which is added/updated/deleted and the value. So for every change an event is emitted.
