### ISSUE TITLE
Unable to install services dependencies

### ISSUE THREAD

**Issue by Gaurav047** [eclipse/ditto#305]
When I tried to install ditto on ubuntu 16.0 I got the following errors : 

[INFO] Eclipse Ditto :: Services .......................... FAILURE [  0.544 s]
[INFO] Eclipse Ditto :: Services :: Models ................ SKIPPED
[INFO] Eclipse Ditto :: Services :: Models :: Streaming ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils ................. SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Akka Utils ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Config Utils . SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Health Utils . SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Cluster Utils  SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: DevOps ....... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Metrics ...... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Tracing Utils  SKIPPED
[INFO] Eclipse Ditto :: Services :: Models :: Things ...... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Cache Utils .. SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Test Utils ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Persistence Utils SKIPPED
[INFO] Eclipse Ditto :: Services :: Base .................. SKIPPED
[INFO] Eclipse Ditto :: Services :: Models :: Concierge ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Concierge ............. SKIPPED
[INFO] Eclipse Ditto :: Services :: Concierge :: Batch .... SKIPPED
[INFO] Eclipse Ditto :: Services :: Models :: Policies .... SKIPPED
[INFO] Eclipse Ditto :: Services :: Models :: Things Search SKIPPED
[INFO] Eclipse Ditto :: Services :: Models :: Connectivity  SKIPPED
[INFO] Eclipse Ditto :: Services :: Concierge :: Util ..... SKIPPED
[INFO] Eclipse Ditto :: Services :: Concierge :: Cache .... SKIPPED
[INFO] Eclipse Ditto :: Services :: Concierge :: Enforcement SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Distributed Data SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Namespaces ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Concierge :: Starter .. SKIPPED
[INFO] Eclipse Ditto :: Services :: Connectivity .......... SKIPPED
[INFO] Eclipse Ditto :: Services :: Connectivity :: Util .. SKIPPED
[INFO] Eclipse Ditto :: Services :: Connectivity :: Mapping SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Protocol ..... SKIPPED
[INFO] Eclipse Ditto :: Services :: Connectivity :: Messaging SKIPPED
[INFO] Eclipse Ditto :: Services :: Connectivity :: Starter SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway ............... SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway :: Streaming .. SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway :: Util ....... SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway :: Security ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway :: Health ..... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: JWT .......... SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway :: Endpoints .. SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Aggregator ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway :: Proxy ...... SKIPPED
[INFO] Eclipse Ditto :: Services :: Gateway :: Starter .... SKIPPED
[INFO] Eclipse Ditto :: Services :: Policies .............. SKIPPED
[INFO] Eclipse Ditto :: Services :: Policies :: Util ...... SKIPPED
[INFO] Eclipse Ditto :: Services :: Utils :: Conditional Header Utils SKIPPED
[INFO] Eclipse Ditto :: Services :: Policies :: Persistence SKIPPED
[INFO] Eclipse Ditto :: Services :: Policies :: Starter ... SKIPPED
[INFO] Eclipse Ditto :: Services :: Things ................ SKIPPED
[INFO] Eclipse Ditto :: Services :: Things :: Util ........ SKIPPED
[INFO] Eclipse Ditto :: Services :: Things :: Persistence . SKIPPED
[INFO] Eclipse Ditto :: Services :: Things :: Starter ..... SKIPPED
[INFO] Eclipse Ditto :: Services :: Thing Search .......... SKIPPED
[INFO] Eclipse Ditto :: Services :: Thing Search :: Common  SKIPPED
[INFO] Eclipse Ditto :: Services :: Thing Search :: Persistence SKIPPED
[INFO] Eclipse Ditto :: Services :: Thing Search :: Updater Actors SKIPPED
[INFO] Eclipse Ditto :: Services :: Thing Search :: Starter SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:03 min
[INFO] Finished at: 2018-12-11T13:45:17+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.26.0:remove (docker-build-image) on project ditto-services: Cannot create docker access object : Cannot extract API version from server http://:2375 : URI does not specify a valid host name: http://:2375/version -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ditto-services

**Comment by thjaeckle** [comment]
Hi there.
Seems like you used the wrong params for building.

From the [README.md](README.md):
```
# if you have the docker daemon running with remote access enabled (e.g. in a Vagrant box or on localhost):
mvn clean install -Pdocker-build-image -Ddocker.daemon.hostname=<ip/host of your docker daemon>
# if you have the docker daemon running on your machine and you are running on Unix, you can also connect against the docker socket:
mvn clean install -Pdocker-build-image -Ddocker.daemon.url=unix:///var/run/docker.sock
```
Could you try that?

**Comment by Gaurav047** [comment]
Thanks for quick response , I tried the second one and installed ditto. :))
# if you have the docker daemon running on your machine and you are running on Unix, you can also connect against the docker socket:
mvn clean install -Pdocker-build-image -Ddocker.daemon.url=unix:///var/run/docker.sock

A few more bugs( maybe)  , 
as mentioned on this page : https://www.eclipse.org/ditto/installation-running.html

when I run the command : docker-compose up -d , first I got the following error 
.....................................
admin1@admin1-HP-EliteDesk-800-G1-TWR:~/ditto-master/deployment/docker$ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

................................

Now, I removed the    version : '2.4'   line from docker-compose.yml file and tried again but still it shows the following error

...............................
ERROR: Invalid interpolation format for "connectivity" option in service "services": "docker.io/eclipse/ditto-connectivity:${DITTO_VERSION:-latest}"
...............................

**Comment by thjaeckle** [comment]
Please update your docker-compose version.
As the README.md states, you need "at least version 1.22".

**Comment by Gaurav047** [comment]
Sure , I will try that
