### ISSUE TITLE
Enable google analytics in documentation's _config.yml

### ISSUE THREAD

**Issue by kartben** [eclipse/ditto#32]
Please include a google analytics tracker in the Ditto website and follow the instructions here https://wiki.eclipse.org/IoT/Community_metrics#Web_traffic to share access with Eclipse so  that the stats can be consolidated in our monthly reports.

Thanks!
Benjamin -

**Comment by thjaeckle** [comment]
Hi Benjamin.
I just did that - hopefully correctly .. :-)

**Comment by kartben** [comment]
I am not sure your layout files are correct. They seem to put the tracker at the very end of the page, just before </html>, whereas it should be the first item of the <head> afaik.

You may also want to switch to the more recent tracking code:


<script async src="https://www.googletagmanager.com/gtag/js?id={{site.google_analytics}}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{site.google_analytics}}');
</script>

**Comment by thjaeckle** [comment]
I think I had the permissoins in Analytics for the "eclipsefdn" user wrong.
Could you try again? I already see some statistics in the Analytics dashboard

**Comment by kartben** [comment]
works now, thanks!
