### ISSUE TITLE
Containers start to fail (Docker Compose)

### ISSUE THREAD

**Issue by sergiomanso** [eclipse/ditto#335]
I'm trying to install ditto 0.8.0 and after a while, containers start to fail. (Tried with docker 18.09 and 18.06 and several linux distros)

I increased the startup-timeout (IBM_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Dakka.remote.startup-timeout=60s) and docker-compose logs spit this:

https://pastebin.com/wc27z26x

**Comment by thjaeckle** [comment]
Hi.
Your logfile seems very normal - are you sure the containers failed / crashed?
From the logs it looks like a working Ditto cluster to me.

**Comment by sergiomanso** [comment]
If you check the log you can see that after stuff like this:

`policies_1       2019-02-14 17:20:38,382 ERROR [] a.m.c.b.i.HttpContactPointBootstrap akka://ditto-cluster@172.21.0.3:2551/system/bootstrapCoordinator/contactPointProbe-172.21.0.5-8558 - Probing [http://172.21.0.5:8558/bootstrap/seed-nodes] failed due to: Tcp command [Connect(172.21.0.5:8558,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused`

Containers will exit:

`docker_connectivity_1 exited with code 137`

**Comment by thjaeckle** [comment]
Only one container - `docker_connectivity_1` exits .. but strangely prints no other log messages. Maybe docker was not providing all the logs? Could you check again for its logs?

The `ERROR` messages are quite normal during bootstrap - as the ports are not available right from the beginning.

But all other containers instead of the one `docker_connectivity_1` start successfully.

**Comment by sergiomanso** [comment]
This is the full compose log, it's a bit weird.

I deployed ditto again and collected new logs. (sorry for the color codes, forgot the  --no-color option)
I'm trying to deploy it inside an OpenStack instance (If that's relevant). Ubuntu 18.04, Docker 18.09.2 and docker-compose 1.23.2 (Also tried Digital Ocean and AWS btw)

https://pastebin.com/ce3eVT7g

This time more containers have failed. The number of ct that fail in each deployment is random.

**Comment by Yannic92** [comment]
Could you try to downgrade to docker 18.09.1? We know about the security fix, but with docker 18.09.2 we experienced issues, too and need to investigate what the issue is.

**Comment by sergiomanso** [comment]
I tried with different versions of Docker before, didn't solved the problem.
When deploying Ditto 0.8.0 inside an instance/virtual machine, allocating more memory solved the problem. I increased the 256m to 512m (or more, is up to you) and seems to have solved the problem.
Thanks for your help guys

**Comment by Yannic92** [comment]
Thank you for letting us know @sergiomanso
