### ISSUE TITLE
Provide placeholder functions for connectivity placeholder mechanism

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#337]
In the connectivity microservice Ditto already makes use of placeholders, e.g. in order to determine a "target address" based on variables, e.g.:
```
{{ thing:id }}
{{ topic:full }}
{{ header:some-arbitrary-header }}
```

It would be very useful to also apply functions on these placeholders, e.g. in order to just select a substring of a variable, e.g.:
```
{{ thing:name | fn:substring-before('_') }}
```

Same applies for header mappings where placeholders may be used.

Current ideas for functions:
* substring-before
* substring-after
* default - provide a fallback value if for example a header was not set

**Comment by ffendt** [comment]
How about also adding a `lower` and a `upper` function that will convert the text to lower- and uppercase?

**Comment by thjaeckle** [comment]
Good idea, that should be easy :+1:
