### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by kuzuilker** [eclipse/ditto#340]
Hello,

I downloaded Ditto 0.8.0 release, compile it successfully.

I build Ditto with docker-compose up -d in ditto/deployment/docker path.

localhost:8080 page opened and works fine but;

-  localhost:8080/ws
-  localhost:8080/stats
-  localhost:8080/status
-  localhost:8080/devops       give 502 bad gateway error. 

I add the log file in attachment.

Thanks.

[log.zip](https://github.com/eclipse/ditto/files/2895780/log.zip)

**Comment by stmaute** [comment]
Hi

From the log file I can see that the Ditto service wasn't completely running. You have to wait at least a minute before you can send request.

You can use the localhost:8080/status/health route to verify that all Ditto services are up and running.

Can you try this again?

**Comment by kuzuilker** [comment]
Hello,

3 days ago, i install ubuntu 16.04 version and compile ditto and run it. It works successfully, but only docker file without compiling Ditto didn't work.

As a result Ditto up and running now. 

Thanks for your answer.

**Comment by stmaute** [comment]
We checked in the .env file in the ditto/deployment/docker directory by mistake. If you delete this file you can use the docker-compose file without building ditto. Because then the images from the Docker hub are used. We will fix this with with PR #344.
