### ISSUE TITLE
ERROR: manifest for eclipse/ditto-policies:0-SNAPSHOT not found

### ISSUE THREAD

**Issue by BobOntario** [eclipse/ditto#342]
When I run "docker-compose up -d", I got an error:

Pulling policies (docker.io/eclipse/ditto-policies:0-SNAPSHOT)...
ERROR: manifest for eclipse/ditto-policies:0-SNAPSHOT not found

Do you know how I can fix this porblem ? I used Ubuntu 16.04

**Comment by BobOntario** [comment]
![ditto](https://user-images.githubusercontent.com/27965673/53382042-dd991c80-3940-11e9-9879-110da78773c6.png)

**Comment by thjaeckle** [comment]
We unfortunately added/committed the `.env` file in the docker folder. That way by default the 0-Snapshot is used.
We should remove the file again and add it to gitignore

**Comment by stmaute** [comment]
I have fixed this in PR #344
