### ISSUE TITLE
Can't update the temp_sensor and altitude value by sending MQTT by paho

### ISSUE THREAD

**Issue by haijunjiang** [eclipse/ditto#345]
I have installed ditto, mosquttio, created the policy, octopus, connected ditto to mosquitto and finished the front-end web
followed by https://github.com/eclipse/ditto-examples/tree/master/mqtt-bidirectional

now I use Paho MQTT Utility to connect mosquitto and  publish data to the topic "/ditto-tutorial/my.test:octopus" (also try the topic "ditto-tutorial/my.test:octopus")

but the my.test:octopus can't update its temp_sensor and altitude value
Can anyone help me to find why? thinks!
![conn_to_mosquitto](https://user-images.githubusercontent.com/42160474/53788201-0e3e0f00-3f5c-11e9-9820-40b2b7b145d7.png)
![paho](https://user-images.githubusercontent.com/42160474/53788214-19913a80-3f5c-11e9-8eac-e86b34606685.png)
![web](https://user-images.githubusercontent.com/42160474/53788224-1e55ee80-3f5c-11e9-94e8-cc091475b3aa.png)

**Comment by thjaeckle** [comment]
Hi.
Could you please provide some log files? Did you have a look at them?

The logs from the "connectivity" service should have detailed information about whether the connection could be established and about processed messages.

**Comment by haijunjiang** [comment]
Thanks!
Problem has been solved.
I find there are sth error with thingId in connectivity log
![conn_log](https://user-images.githubusercontent.com/42160474/53851254-1f892900-3ff9-11e9-9bc2-ff91d0c1922d.png)
and then I change the thingId as octopus ( not my.test:octopus  and the topic is "ditto-tutorial/my.test:octopus")

![sent_mqtt](https://user-images.githubusercontent.com/42160474/53851360-70991d00-3ff9-11e9-81e7-71e2b96b7bf5.png)

and then it's ok
 
![ok](https://user-images.githubusercontent.com/42160474/53851388-84448380-3ff9-11e9-9685-53e882aaaff7.png)
