### ISSUE TITLE
Can't build ditto

### ISSUE THREAD

**Issue by BobOntario** [eclipse/ditto#346]
Just follow the instructions @ https://github.com/eclipse/ditto "Build and Start ditto" , got the following error, don't know why? appreciate any advice!

[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.11.0:cmp (default) on project ditto-utils-jsr305: Execution default of goal com.github.siom79.japicmp:japicmp-maven-plugin:0.11.0:cmp failed: Could not load 'java.lang.Object': java.lang.Object. Please make sure that all libraries have been added to the classpath (CLASSPATH=:/root/ditto/legal/target/ditto-legal-0-SNAPSHOT.jar:/root/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar:) or try the option '--ignore-missing-classes'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by haijunjiang** [comment]
Be sure that:
JDK 8 >= 1.8.0_92 (due to a bug in older versions of the JDK you’ll get a compile error),
and don't use openjdk.
![jdk](https://user-images.githubusercontent.com/42160474/53851638-3f6d1c80-3ffa-11e9-8513-eb857d2623b9.png)
