### ISSUE TITLE
gateway exited

### ISSUE THREAD

**Issue by haijunjiang** [eclipse/ditto#349]
When I start ditto using "docker-compuse -up -d "
the gateway_1 will exit soon with following logs
![gateway](https://user-images.githubusercontent.com/42160474/54011257-ccf06e00-41ac-11e9-9162-43e254027f57.png)

Can anyone tell why?
Thanks

**Comment by haijunjiang** [comment]
Finally I solved this problem by my own docker images

boyjiang/ditto-things-search:0-SNAPSHOT 
boyjiang/ditto-things:0-SNAPSHOT    
boyjiang/ditto-policies:0-SNAPSHOT  
boyjiang/ditto-gateway:0-SNAPSHOT 
boyjiang/ditto-connectivity:0-SNAPSHOT
boyjiang/ditto-concierge:0-SNAPSHOT

anyone who want use these images can pull the docker images from docker hub
docker pull boyjiang/ditto-things-search:0-SNAPSHOT 
------

and you need to modify the docker-compose.yml

replace all "docker.io/eclipse" with "boyjiang"
![docker-compose](https://user-images.githubusercontent.com/42160474/54014364-59a02980-41b7-11e9-9864-921ad901ab68.png)

then it will be ok

so there shoud be sth wrong with the eclipse/ditto docker images

**Comment by thjaeckle** [comment]
Hi.
Did you try to increase the memory limits in the docker-compose? If you have memory left on your machine, we would suggest to use 512m for each container.

**Comment by haijunjiang** [comment]
thanks
it really works.
