### ISSUE TITLE
Can ditto connect to mosquitto by username:password 

### ISSUE THREAD

**Issue by haijunjiang** [eclipse/ditto#361]
Hi, all!
I am setting  username and password as the authorization for mosquito broker.
I find ditto can work with ca certification but how can I connect mosquito by username and password?
Thanks.
![图片](https://user-images.githubusercontent.com/42160474/54733886-2c9c3f80-4bd7-11e9-8d1e-5e9da242dd9d.png)

**Comment by thjaeckle** [comment]
Hi.
Hm, this is indeed not documented - but: yes, it can.
Simply put the username and password in the `uri` field like for all uris ;)
`"uri": "ssl://my-user:my-password@test.mosquitto.org:8884"`

**Comment by haijunjiang** [comment]
Thanks， that really works.

**Comment by mfbatra** [comment]
> Hi.
> Hm, this is indeed not documented - but: yes, it can.
> Simply put the username and password in the `uri` field like for all uris ;)
> `"uri": "ssl://my-user:my-password@test.mosquitto.org:8884"`

If we have a client id as well with the username and pwd, Should we put it in the authorization context?
