### ISSUE TITLE
testConnection problem

### ISSUE THREAD

**Issue by BobOntario** [eclipse/ditto#368]
When I tried to test connection by using:

curl -X POST 'http://localhost:8080/devops/piggyback/connectivity?timeout=10000' -u 'devops:foobar'  -H 'Content-Type: application/json' -d '{
    "targetActorSelection": "/system/sharding/connection",
     "headers": {
      "aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:testConnection",
         "connection": {}
    }
 }'

I got this problem:

{"?":{"?":{"type":"devops.responses:errorResponse","status":400,"serviceName":null,"instance":null,"payload":{"status":400,"error":"json.field.missing","message":
"Error when parsing Json type 'connectivity.commands:testConnection': JSON did not include required </connectionType> field!","description":"Check if all
 required JSON fields were set."}}}}

Any ideas?

**Comment by thjaeckle** [comment]
Yes, you forgot the important part of the payload - everything below of "connection" ..
As the docs say:
    The content of the connection configuration object is specified in the [Connections section](https://www.eclipse.org/ditto/basic-connections.html).

There you must fill in all of the necessary connection info, e.g.:
* id
* name
* connectionType
* connectionStatus
* uri
* ...

**Comment by Yannic92** [comment]
@thjaeckle Maybe we should make it more clear in the provided JSON, that it cannot be used by just copy pasting it.
https://www.eclipse.org/ditto/connectivity-manage-connections.html#test-connection
shows exactly the JSON provided in this issue. I guess it's copy pasted from here.
```
{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
      "aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:testConnection",
        "connection": {}
    }
}
```

> "Analog to the createConnection command, it requires a full connection configuration in the piggyback command." 

says that the connection needs to be specified, but I suggest making it more clear by using an ellipsis in the connection JSON for the docs.

**Comment by thjaeckle** [comment]
Agreed :+1:

**Comment by BobOntario** [comment]
@Yannic92 You are right, I just copy/paste it :)  Do i need fill all of connection info under connection, or i can just fill few necessary ones? 

BTW, how can I know data from MQTT client have been mapped into ditto protocol ? whether these data will be stored in Mongo DB?  I mean live data?

**Comment by BobOntario** [comment]
I got this response for testConnection.  Does this mean the connection ok?

{"?":{"?":{"type":"connectivity.responses:testConnection","status":409,"connectionId":"mqtt-example-connection-123","testResult":"Connection was already created - no test possible"}}}root@ecs-8738-2:~#

**Comment by Yannic92** [comment]
As the status 409 (Conflict) indicates, this is not an OK (200) response.
The message states that the connection does already exist. 
So a connection with the same ID does already exist.
You can verify the configuration by sending a retrieve connection command and compare the connection with the one you'd like to create.

**Comment by BobOntario** [comment]
@Yannic92 thanks.

I checked my connection status and metrics, response with 200.  see below.  Octopus publishing messages are ok, I can see all message from MQTT Client through subscribe. But webapp provided in github can't see these Octopus messages, server send event works, count event 1 by 1.  my.test.octopus panel never change. I used command line to query, only can get one from Webapp saved. I never searched the messages from Octopus. I don't know why?  any advice?

![image](https://user-images.githubusercontent.com/27965673/55172719-dab46600-5150-11e9-8ac6-80e0ff9458ba.png)


![image](https://user-images.githubusercontent.com/27965673/55172775-f1f35380-5150-11e9-8503-bc4a7ad582a9.png)

**Comment by BobOntario** [comment]
@Yannic92   I tried testConnection again with following command and got a response **"null"**, which mean what?

curl -X POST 'http://localhost:8080/devops/piggyback/connectivity?timeout=10000' -u 'devops:foobar' -H 'Content-Type: application/json' -d '{

"targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:testConnection",
        "connection": {
            "id": "mqtt-example-connection-123",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://mqtt_ip:1883",
            "sources": [{
                "addresses": ["ditto-tutorial/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "ditto-tutorial/{{ thing:id }}",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }],
            "mappingContext": {
                "mappingEngine": "JavaScript",
                "options": {
                    "incomingScript": "function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload));const jsonData = JSON.parse(jsonString); const thingId = jsonData.thingId; const value = { temp_sensor: { properties: { value: jsonData.temp } },altitude:        {            properties:            {                value: jsonData.alt            }        }    };    return Ditto.buildDittoProtocolMsg('my.test', thingId, 'things', 'twin', 'commands', 'modify', '/features', headers, value);}"
                }
            }
        }
    }
}'

**Comment by Yannic92** [comment]
For questions about usage of ditto please use stackoverflow. Just tag your question with the "eclipse-ditto" tag and we'll be notified about it.

Furthermore please do not provide logs as images because it will force people to retype your logs if the want to search for something.

**Comment by BobOntario** [comment]
Sorry for making you confused. Comments have been taken.  Appreciate if you could help me out this issue!!!  Thanks

**Comment by thjaeckle** [comment]
Feel free to open an issue for non-questions (e.g. for a bug in Ditto).
