### ISSUE TITLE
Evaluate Ditto with Azure CosmosDB facade

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#376]
Azure CosmosDB provides a MongoDB facade: 
https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction

We would like to evaluate whether Ditto can be used with CosmosDB as in-place replacement of MongoDB.

The following services make "simple" use (create, delete, read with kind of "key-value-store" approach) of MongoDB:
* policies
* things
* concierge
* connectivity

The following service uses MongoDB for "advanced" topics (e.g. regex searches, complex filters, array indices, etc.):
* things-search

The goal is to evaluate
* whether the "simple" services work on CosmosDB
* whether the "advanced" services work on CosmosDB and potentially identify the parts where CosmosDB behaves differently than in MongoDB

**Comment by kaizimmerm** [comment]
I am currently running tests against CosmosDB for the "simple" use case. So far good results. I will keep you updated.

**Comment by thjaeckle** [comment]
@kaizimmerm can we close this by summing the results up in 1-2 sentences? :)

**Comment by kaizimmerm** [comment]
Sure!

The simple use case worked fine. I could not identify any issues. As expected, things-search did not work as search on CosmosDB works different then MongoDB and as a result would require code changes. In addition it might generate high service cost.
