### ISSUE TITLE
[website] Company logos

### ISSUE THREAD

**Issue by kartben** [eclipse/ditto#384]
FWIW the guidelines for Eclipse project websites is that company logos can be shown only for those companies that are members of the Eclipse Foundation, so you may not want to have the Aloxy logo

**Comment by thjaeckle** [comment]
As far as I understand the [handbook section](https://www.eclipse.org/projects/handbook/#pmi-company-logos) about that, that only applies for the "Who's Involved" page at the project's site.

For example the Vert.X start page also lists a lot of companies which are not Eclipse Foundation members:
http://vertx.io/whos_using/

**Comment by kartben** [comment]
Right but I'm not sure the Eclipse Vert.x webpage is compliant, for what it's worth :-)
See https://www.eclipse.org/lists/iot-pmc/msg04198.html - and @waynebeaton is definitely the one who'd know the definitive answer :)

**Comment by thjaeckle** [comment]
This has been resolved by the Eclipse foundation by https://github.com/eclipsefdn/iot.eclipse.org#project-adopters which Ditto implemented in #503
