### ISSUE TITLE
MQTT publish fails if no sources are configured

### ISSUE THREAD

**Issue by ffendt** [eclipse/ditto#387]
If using a MQTT connection that only has targets but no sources, publishing of events will fail with the following log entry:
Cannot handle <any event> signal as there is no MessageMappingProcessor available."

I think the reason lies in [MqttClientActor:186](https://github.com/eclipse/ditto/blob/6de44b443c5bc3530bbfa9a60b419cb1c1b45c5e/services/connectivity/messaging/src/main/java/org/eclipse/ditto/services/connectivity/messaging/mqtt/MqttClientActor.java#L186) which starts the MessageMappingProcessorActor only if the MQTT connection has sources. In my opinion the actor should be started after starting the publisher actor (in line 182) since the MessageMappingProcessorActor will use the publisher actor that is created in line 181.

**Comment by thjaeckle** [comment]
Fixed by #389
