### ISSUE TITLE
BadGateway error running locally on Docker for Windows

### ISSUE THREAD

**Issue by srberard** [eclipse/ditto#396]
Similar to issue #340 I'm getting a 502 Bad Gateway on everything except the static site and swagger UI.

I cloned the Ditto project, changed directories to `ditto/deployment/docker` and ran the following:
```docker-compose up -d ```

The main page at http://localhost:8080/ works fine, as does the Swagger UI.  However, if I try to do anything against the local Ditto instance I get a 502 Bad Gateway issue.  Similar to the other issue, the following pages result in 502 erros as well:
    localhost:8080/ws
    localhost:8080/stats
    localhost:8080/status

I'm using the pre-built images for 0.8.0.  I'm running Docker for Windows v2.0.0.3 (latest stable) on Windows 10 with Linux containers.  

I looked at the container status with `docker-compose ps` and saw that the Concierge service existed with an error 137.  I restarted services and tried again with the same result.  

Looking in the logs I didn't see anything that really stood out as the root cause.  I did see a number of these:
```
concierge_1      | 2019-05-02 16:50:02,374 ERROR [] a.m.c.b.i.HttpContactPointBootstrap akka://ditto-cluster@172.20.0.7:2551/system/bootstrapCoordinator/contactPointProbe-172.20.0.8-8558 - Probing [http://172.20.0.8:8558/bootstrap/seed-nodes] failed due to: Probing timeout of [http://172.20.0.8:8558]
concierge_1      | 2019-05-02 16:50:02,377 ERROR [] a.m.c.b.i.HttpContactPointBootstrap akka://ditto-cluster@172.20.0.7:2551/system/bootstrapCoordinator/contactPointProbe-172.20.0.8-8558 - Overdue of probing-failure-timeout, stop probing, signaling that it's failed
```
The above appears in several other services as well.

Any ideas on how to fix or further troubleshoot this?

**Comment by ffendt** [comment]
Hi srberard,

how much memory do you provide to docker in your Docker for Windows settings (see Advanced tab)? Too less memory might cause these issues when starting the containers. I have this setting on 10GB but I am also running some more containers. When only running Ditto you should probably be alright with less than that. If still one of the services fails starting (with the error log you provided), you can try to restart it manually (docker-compose restart <services>).

The 502 probably means that nginx can't contact the gateway service, so the important logs will probably be nginx (docker-compose logs nginx) and gateway (docker-compose logs gateway). Could you please have a look at them?

Best regards,
Florian

**Comment by srberard** [comment]
@ffendt thanks for the help.  Your memory suggestion worked.  I tried this on a machine with more memory and allocated 8GB to the VM.  Everything worked as expected.  Thanks!
