### ISSUE TITLE
Consumers of Azure Service Bus reconnect every couple minutes

### ISSUE THREAD

**Issue by yufei-cai** [eclipse/ditto#399]
## Context

1. Create an AMQP connection to Azure Service Bus with 1 source and no target.
2. Do not send any events to the Service Bus.

## Expected behavior

The connection stays open; AmqpClientActor replies "open" on `RetrieveConnectionStatus` command.

## Actual behavior

Live connection status in AmqpClientActor gets set to "closed" once every few minutes and then set to "open" again after about 10 seconds.

I tried the `specificConfig` below. They do not prevent the connections from closing themselves, nor do they change the interval at which the connections close themselves:

```
failoverEnabled = true
failoverEnabled = false
amqp.idleTimeout = 20000 (minimum value accepted by Qpid)
amqp.idleTimeout = 3600000
amqp.drainTimeout = 3600000
```

Live connection status continued to flicker after the Service Bus was deleted.

**Comment by yufei-cai** [comment]
@kaizimmerm Do you happen to know why this might happen?

**Comment by kaizimmerm** [comment]
Do you happen to have a log entry? Service Bus has its own idle timeouts but Qpid should log if the server shuts a link down with a reason. `amqp.idleTimeout` in the URL btw. is client side only. 

"_...every few minutes..._" is this constant? I would expect 10 minutes.

**Comment by yufei-cai** [comment]
```
08:46:54.538UTC
Subscribed Connection <...> to sources: [ConsumerData [address=garg, addressWithIndex=garg-0]]

09:05:05.058UTC
javax.jms.JMSException occurred: The link 'G2:1647380:qpid-jms:receiver:ID:9ebd63de-ec24-434f-8acb-cb5bcb7e689a:1:1:1:garg' is force detached by the broker due to errors occurred in consumer(link106418). Detach origin: InnerMessageReceiver was closed. TrackingId:50e533a30000001500019fb25ccff47e_G2_B4, SystemTracker:gargsb:Queue:garg, Timestamp:2019-05-06T09:05:05 [condition = amqp:link:detach-forced]
```
No interaction with Service Bus was logged between creation of the consumer and the force detachment.

**Comment by kaizimmerm** [comment]
Hmm, that is a longer timeframe that I would expect. 

Anyhow, have you configured `amqp.idleTimeout` on the client? It should not keep an idle connection open that long. So maybe `amqp.idleTimeout=120000` is a good starting point to avoid that the server is forced to shut it down.

**Comment by yufei-cai** [comment]
I want to keep the connection open 24/7 so that I know immediately when something gets pushed into the queue. AMQP 1.0 specification ss. 2.4.5 states that idle timeout is negotiated at connection open and heartbeats are sent at intervals half of the actual idle timeout. There should be no reason why I can't keep an idle connection open indefinitely.
> At Connection open each peer communicates the
maximum period between activity (frames) on the connection that it desires from its partner. The
open frame carries the idle-time-out field for this purpose. To avoid spurious time-outs, the value in
idle-time-out should be half the peer’s actual timeout threshold.
If a peer can not, for any reason support a proposed idle time-out, then it should close the connection
using a close frame with an error explaining why. There is no requirement for peers to support
arbitrarily short or long idle time-outs.
The use of idle time-outs is any addition to any network protocol level control. Implementations
should make use of TCP keep-alive wherever possible in order to be good citizens.
If a peer needs to satisfy the need to send traffic to prevent idle time-out, and has nothing to send,
it may send an empty frame, i.e. a frame consisting solely of a frame header, with no frame body.
This frame’s channel can be any valid channel up to channel-max, but is otherwise to be ignored.
Implementations SHOULD use channel 0 for empty frames, and MUST use channel 0 if channel-max
has not yet been negotiated (i.e. before an open frame has been received). Apart from this use, empty
frames have no meaning.

**Comment by kaizimmerm** [comment]
Well, I guess this is the wrong forum to discuss your requirement _"keep an idle connection open indefinitely"_  towards Azure Service Bus and I am for sure the wrong peer.

The issue is btw. discussed here as well https://github.com/Azure/azure-service-bus-java/issues/219#issuecomment-473009343 

However, based on your description it seems Ditto is handling this correctly by means of reopening the link. So, I cannot see an actual issue here.

**Comment by yufei-cai** [comment]
Good to know, thanks.
