### ISSUE TITLE
401 Unauthorized when Operating Ditto

### ISSUE THREAD

**Issue by aaron0609** [eclipse/ditto#419]
When testing devops commands in 0.9.0-m2, according to the document https://www.eclipse.org/ditto/installation-operating.html#devops-commands, I got the following error message when retrieving log levels:

/opt/ditto # wget -q -O - http://10.0.0.74:8080/devops/logging
wget: server returned error: HTTP/1.1 401 Unauthorized

And I tried the nginx user/password but doesn't work

**Comment by thjaeckle** [comment]
Hi there.

Ah, sorry - we still have the user/password for the "devops" resource not documented (only in the configuration files).
So please use:
* user: devops
* password: foobar

**Comment by aaron0609** [comment]
> Hi there.
> 
> Ah, sorry - we still have the user/password for the "devops" resource not documented (only in the configuration files).
> So please use:
> 
> * user: devops
> * password: foobar

Thanks now it works while getting log levels, but when I tried the CURD command to create a connection, it returns the error for me.
Here is my python code:
`import requests
import json

base_url = 'http://devops:foobar@<IP_ADDRESS>:<PORT>'
uri = '/devops/piggyback/connectivity'

_create = {
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
      "aggregate": False
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {}
    }
}

rsp = requests.post(base_url+uri,data=json.dumps(_create))

print rsp.status_code
print rsp.text`

And here is the error message I got:
{"?":{"?":{"type":"devops.responses:errorResponse","status":400,"serviceName":null,"instance":null,"payload":{"status":400,"error":"json.type.notparsable","message":"The JSON type 'connectivity.commands:createConnection' is not supported by registry 'JsonParsableCommandRegistry'.","description":"Check if you sent the JSON with the correct type."}}}}

**Comment by Felice-Copp56** [comment]
Hi, I have same problem when try to connect in the ditto Explorer Ui connections sections. I have tried devops foobar credentials
