### ISSUE TITLE
Broken link at Open Eclipse Ditto Feature web page.

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/ditto#424]
Broken link at Open Eclipse Ditto Feature web page.

Action:
Open Eclipse Ditto Feature page ( https://www.eclipse.org/ditto/basic-feature.html )

Scroll down to "Mapping Vorto function block elements"

Follow the link given in "A Vorto function block consists of different sections defining state and capabilities of a device." ( https://www.eclipse.org/vorto/documentation/appendix/functionblock-dsl-reference.html#function-block-dsl-semantics )

Result:
New web page opens with message "404 File not found".

**Comment by dguggemos** [comment]
Hi @andrew-from-pretoria,
thanks for reporting, we'll fix it.

**Comment by thjaeckle** [comment]
Fixed with #441 - removed deep links to Vorto
