### ISSUE TITLE
Broken link at "Connecting Eclipse Ditto to Eclipse Hono"

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/ditto#431]
Description:
Broken link to "Hono telemetry" on page "Connecting Eclipse Ditto to Eclipse Hono" 

Action:
1. Open https://www.eclipse.org/ditto/2018-05-02-connecting-ditto-hono.html
2.  Scroll to second paragraph:  "By doing so it is for example possible to receive Hono telemetry messages"
3. Click on link "...Hono telemetry"  < https://www.eclipse.org/hono/api/telemetry-api/ >

Expected: 
Description of Hono telemetry messages, particularly about “Northbound Operations".

Actual result:
Error 404, page not found.

**Comment by thjaeckle** [comment]
Fixed with #441 - removed deep links to Hono
