### ISSUE TITLE
'The supplied authentication is invalid' with custom devops user

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#443]
I've setup a Ditto-Instance as in the [deployment/docker](https://github.com/eclipse/ditto/tree/master/deployment/docker) part of the project and changed the devops password to a custom one which I hashed using `openssl passwd --quiet` and updated in `nginx-devops.htpasswd`.

Unfortunately I get the error message `The supplied authentication is invalid` this way when trying to access any `/devops` resource. When using a random username and/or password it returns a "401 Unauthorized".

My nginx.conf is as follows

```
   # devops
    location /devops {
      include nginx-cors.conf;

      auth_basic                    "Authentication required";
      auth_basic_user_file          nginx-devops.htpasswd;

      proxy_pass                    http://gateway:8080/devops;
      proxy_http_version            1.1;
      proxy_set_header              Host                $http_host;
      proxy_set_header              X-Real-IP           $remote_addr;
      proxy_set_header              X-Forwarded-For     $proxy_add_x_forwarded_for;
      proxy_set_header              X-Forwarded-User    $remote_user;
    }
```

EDIT:

Ok, well, I got closer to an answer. I took the nginx-devops config from the subfolder sandbox because I was searching for a way to work with the devops API and couldn't find something in the docs. Apparently I have to at least configure the same passwort in nginx as well as in the gateway-container through the environment variable `DEVOPS_PASSWORD`. 

I'm wondering if there is a security flaw to only use the gateways-service authorization without nginx?

Is there a reason why this is documented nowhere?

**Comment by w4tsn** [comment]
Ok, well, I found the answer. I took the nginx-devops config from the subfolder sandbox because I was searching for a way to work with the devops API and couldn't find something in the docs. Apparently I have to at least configure the same passwort in nginx as well as in the gateway-container through the environment variable `DEVOPS_PASSWORD`. 

I'm wondering if there is a security flaw to only use the gateways-service authorization without nginx?

Is there a reason why this is documented nowhere?

**Comment by thjaeckle** [comment]
Hi Alexander.

> I'm wondering if there is a security flaw to only use the gateways-service authorization without nginx?

Not at all - good question why we added the `nginx-devops.htpasswd` on the `/devops` route in nginx. 
Should not be necessary to include that one, sorry.

> Is there a reason why this is documented nowhere?

No good reason at all. ;)
The docker-compose of the sandbox is what it is: a sandbox setup which is not necessarily a perfect fit for usage in production.
And the documentation is also what it is: an OpenSource maintained documentation ;) - we will happily  accept PullRequests improving the doc.

We also use nginx in our productive environment in front of the Ditto gateway, but the configuration of that one is of course adjusted to the needs of our commercial offering. 
To answer your question: we also only configure the `DEVOPS_PASSWORD` env variable of the gateway.
