### ISSUE TITLE
ERROR message pattern bug

### ISSUE THREAD

**Issue by liuhu** [eclipse/ditto#447]
In `ImmutableThingFromCopyBuilder` class file , at `tryToParseModified` method.

``` java 
private static Instant tryToParseModified(final CharSequence dateTime) {
        try {
            return Instant.parse(dateTime);
        } catch (final DateTimeParseException e) {
            final String msgPattern ="The JSON object's field <{0>' is not in ISO-8601 format as expected!";
            throw JsonParseException.newBuilder()
                    .message(MessageFormat.format(msgPattern, Thing.JsonFields.MODIFIED.getPointer()))
                    .cause(e)
                    .build();
        }
    }
```
The message pattern `The JSON object's field <{0>' is not in ISO-8601` is wrong,   it is missing `}`

**Comment by thjaeckle** [comment]
Hi.
You mean this line?
https://github.com/eclipse/ditto/blob/master/model/things/src/main/java/org/eclipse/ditto/model/things/ImmutableThingFromCopyBuilder.java#L117

Looks good to me on master and in Ditto 0.9.0.

**Comment by liuhu** [comment]
Sorry. It is my mistake. I forge update local source.
