### ISSUE TITLE
MQTT thread leaks / pollution

### ISSUE THREAD

**Issue by ffendt** [eclipse/ditto#450]
With the introduction of #442 (Reconnecting feature for created connections), we can now observe thread leaks produced by our MQTT connections every time a connection to a remote system fails.

It looks like the used [akka/alpakka](https://github.com/akka/alpakka) mqtt client will try to disconnect / close the connection with its [eclipse/paho.mqtt.java](https://github.com/eclipse/paho.mqtt.java) client. The paho client will create several threads in which it will wait e.g. on the successful send of a disconnect message. The threads however will wait forever and stay alive in the JVM. Since we have no direct access to the client, we should start by removing akka/alpakka to have more control over what happens.

Since connections to MQTT brokers are defined by the user, we have to be highly flexible and need a client that will work well with disconnects, reconnects and use as few threads as possible.
As we can observe remaining threads if a disconnect or close is called on a disconnected / disconnecting paho client it might make sense to have a look at another client like e.g. [hivemq/hivemq-mqtt-client](https://github.com/hivemq/hivemq-mqtt-client). It would also provide an async and a reactive API which would fit much better into our code base.

**Comment by thjaeckle** [comment]
Created CQs for new hivemqtt-mqtt-client dependency:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20711
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20712
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20714
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20715
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20716
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20717

**Comment by thjaeckle** [comment]
All CQs were approved.

**Comment by thjaeckle** [comment]
Resolved by #487
