### ISSUE TITLE
SmartCoffeeApp.js:456 Uncaught TypeError: Cannot read property 'thing-id' of undefined     at DittoWebSocket.reply (SmartCoffeeApp.js:456)     at SmartCoffeeApp.onTurnOnWaterTankMessage (SmartCoffeeApp.js:273)     at HTMLButtonElement.$.click (SmartCoffeeApp.js:105)     at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)     at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)

### ISSUE THREAD

**Issue by SaminaZahidFulda** [eclipse/ditto#458]
How can I create thing with ditto WebSocket?
SmartCoffeeApp.js:456 Uncaught TypeError: Cannot read property 'thing-id' of undefined
    at DittoWebSocket.reply (SmartCoffeeApp.js:456)
    at SmartCoffeeApp.onTurnOnWaterTankMessage (SmartCoffeeApp.js:273)
    at HTMLButtonElement.$.click (SmartCoffeeApp.js:105)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)

**Comment by ffendt** [comment]
Hi @SaminaZahidFulda 

it would be nice if you could open this issue in the [ditto-examples](https://github.com/eclipse/ditto-examples) repository as this seems to be an issue with the example and not with Ditto itself.

Best regards
Florian

**Comment by SaminaZahidFulda** [comment]
I am trying to create Thing with WebSocket. But getting error.

**Comment by SaminaZahidFulda** [comment]
onMessage(message) {
      
        const data1 =  {
            "topic": "twin.othermo.de/:1aa1e46e-c1e9-45a2-a292-1571f8f0a210/things/live/commands/modify",
            "headers": {
                "correlation-id": "2215ea11-dbe5-413e-a783-24ec9c9f9619",
                "response-required": true,
                "content-type": "application/json",
                "auth-subjects": [
                    "nginx:demo1"
                ],
                "version": 2
            },
            "path": "/",
            "value": {
                "accelerometer": {
                    "properties": {
                        "x": 3.141,
                        "y": 2.718,
                        "z": 1,
                        "unit": "g"
                    }
                }
            }
        }
            const data = JSON.stringify(data1);
        this.logToConsole(`received: ${data}`);
        this.logReceiveToUI(data);

            try {
                const jsonMessage = JSON.parse(data);
                this.onJsonMessage(jsonMessage);
            } catch (err) {
                this.logToConsole(`error while handling message: ${err}`);
            }
        
    }

**Comment by ffendt** [comment]
Yes, I see that you get an error and you already posted it:
`SmartCoffeeApp.js:456 Uncaught TypeError: Cannot read property 'thing-id' of undefined
at DittoWebSocket.reply (SmartCoffeeApp.js:456)
at SmartCoffeeApp.onTurnOnWaterTankMessage (SmartCoffeeApp.js:273)
at HTMLButtonElement.$.click (SmartCoffeeApp.js:105)
at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)`

However, this is a javascript error in an example in ditto-example, so please post your issue in the ditto-examples repository. Also, your second code snippet does not seem to have any relation to your error log. Please add some more information on how this happened (and maybe a small reproducer) when opening an issue in the ditto-examples repository.

Thanks and regards
Florian
