### ISSUE TITLE
MQTT-Connector fails to connect if sources array is provided

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#474]
When running a PiggybackCommand to testConnection of a mqtt-connection with a sources array provided the connection does not work. Providing only the targets object however works.

The broker is configured with let's encrypt certificates and accepts connections over tcp. The client has granted readwrite on topic path `ditto/#`. Also testing to grant the ditto client readwrite on any topic.

How to reproduce
---

1. Setup Ditto 0.9.0
2. Setup a mosquitto broker with certificates for ditto user and configure ACL
3. Run piggybackCommand connectivity.command.testConnection with sources array provided

Use a config like this [mqtt-connection-sources-failure-config.txt](https://github.com/eclipse/ditto/files/3525398/mqtt-connection-sources-failure-config.txt) with the following as important bits:

```
"sources": [
    {
        "addresses": [
            "ditto/#"
        ],
        "authorizationContext": [
            "ditto:inbound-auth-subject"
        ],
        "qos": 0,
        "filters": []
    }
],
"targets": [
    {
        "address": "ditto/{{ thing:id }}",
        "topics": [
            "_/_/things/twin/events",
            "_/_/things/live/messages"
        ],
        "authorizationContext": [
            "ditto:outbound-auth-subject"
        ],
        "qos": 0
    }
]
```

What happens
---

The command returns

```json
{
    "?": {
        "?": {
            "type": "devops.responses:errorResponse",
            "status": 504,
            "serviceName": null,
            "instance": null,
            "payload": {
                "status": 504,
                "error": "connectivity:connection.failed",
                "message": "The Connection with ID 'my-broker' failed to connect.",
                "description": "Cause: Connection reset"
            }
        }
    }
}
```

whenever a sources array is provided. It does not matter if a `targets ` array is provided or not. If only providing the `targets` array however the connection works showing the connection is working in principle.

Following some logs that I get. First of both arrays provided, then only with the `sources` array.

[mqtt-connection-sources-failure.txt](https://github.com/eclipse/ditto/files/3525418/mqtt-connection-sources-failure.txt)
[mqtt-connection-sources-failure2.txt](https://github.com/eclipse/ditto/files/3525419/mqtt-connection-sources-failure2.txt)

What should happen
---

The connection should work for the configured sources when configured following the [documentation](https://www.eclipse.org/ditto/connectivity-protocol-bindings-mqtt.html).

About Environment
---

Mosquitto Broker with certificate based authentication over Port 8883/tcp and ACL configured. `readwrite` to user `ditto` and topic `ditto/#`.

The client cert is RSA 4096 bit.

The server configuration is like this:
[mosquitto-broker-config.txt](https://github.com/eclipse/ditto/files/3535255/mosquitto-broker-config.txt)

**Comment by dguggemos** [comment]
Hi @w4tsn, thanks for reporting! In general consuming messages (having one or more sources in your connection) from an MQTT broker works fine. So I assume this is some problem with your specific setup/broker. Which broker did you use in your tests? Unfortunately the only useful information in the Ditto logs is `<Connection lost (32109) - java.net.SocketException: Connection reset>`. Probably the remote side closed the connection for some reason. Does it work with simple authentication (username/pasword)? I will also try to reproduce this on my machine.

**Comment by w4tsn** [comment]
Unfortunately I cannot test password authentication in my setup since it is restricted by policies. I added a mosquitto broker configuration though.

Also strangely the publisher seems to work, so at least this part connects successfully. I'm also able to connect to the broker with the ditto user certificates from another client and subsribe to the ditto/# topic.

**Comment by w4tsn** [comment]
Ok, after some more testing it works and here are my findings as well as the solution in my case:

I tried cert-less auth against `test.mosquitto.org:1883` which worked. 

My problem was that I used the `tcp://` protocol with certificates. I'd have to use the `ssl://` instead of course. Hence the error `connection reset`.

A way to avoid this ambiguity is to infer the protocol from the request e.g. using `ssl://` when credentials are provided (and cert-type) and `tcp://` otherwise. Of course it should still accept a custom protocol. For downwards compatibility the uri string should be checked (what it already is) and if the protocol is not specified infer instead of sending back an error.

**Comment by dguggemos** [comment]
@w4tsn thanks for testing and sharing your findings. I also think that using `tcp://` together with certificates should result in an error when creating the connection. I cannot tell why this works for 'target only' connection. I will have a look into this...
And you are right that the docs need some improvements here. We are working on the MQTT integration anyway, so we will probably take care of this with #450.

**Comment by thjaeckle** [comment]
@dguggemos do we have that covered in #450 and may we close this issue?

**Comment by dguggemos** [comment]
I adjusted the validation of the connection to enforce a secure scheme if certificates are provided.
The docs part is still missing.

**Comment by thjaeckle** [comment]
as far as I have understood, this is resolved
