### ISSUE TITLE
Helm chart openshift

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/ditto#494]
Hi,

I've just tested the install of 1.0.0-M1a on Openshift. I'm installing it using the helm charts.
I have 1 remark about these helm charts and 1 issue:

- Remark: the documentation contains the namespace in the example scripts (https://github.com/eclipse/ditto/tree/master/deployment/helm) I would suggest removing the namespace specification. If you ommit it, it will be installed in the namespace you are currently which should be right most of the time. Right now, I have to adapt these commands to my needs.
- Issue: Both Nginx and Swagger-UI do not have enough permission in openshift. I had to add following specs before the pods started properly: 

> 
          securityContext:
            capabilities: {}
            runAsUser: 0

I don't know whether this is the proper way to fix it, but it works. Maybe somebody has another fix to get this to work.

**Comment by thjaeckle** [comment]
Hi @BobClaerhout 
Sounds both reasonable for me - but I'm not an expert on Helm charts ..
Could you provide a PR with that changes?

**Comment by thjaeckle** [comment]
resolved by #497
