### ISSUE TITLE
Provide pre-built docker images in public repository

### ISSUE THREAD

**Issue by crenz** [eclipse/ditto#5]
Please consider making docker images available e.g. on hub.docker.com for those that are interested to try out ditto, but do not want to set up a complete build environment for it.

**Comment by zantiu** [comment]
+1

**Comment by thjaeckle** [comment]
Sure, will do once we have the build process set up.

**Comment by thjaeckle** [comment]
Images are available for the [0.1.0-M1](https://github.com/eclipse/ditto/releases/tag/0.1.0-M1) release on Docker Hub.
