### ISSUE TITLE
Memory consumption raised in Version 1.0.0-M1a

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/ditto#502]
Hi we are noticing a huge difference in memory consumption between version 0.8.0 and version 1.0.0-M1a. Following screenshot is the consumption of version 0.8.0:
![image](https://user-images.githubusercontent.com/3315222/65890724-a80b5480-e3a3-11e9-9c31-31622831a94b.png)
Mongo uses most of the memory (which is about 4GB). In total, the ditto project uses about 7GB which result in a netto consumption of 3GB for the ditto components.
Following screenshots shows the memory consumprion of version 1.0.0-M1a:
![image](https://user-images.githubusercontent.com/3315222/65890859-e7d23c00-e3a3-11e9-8924-a92fe31ae57d.png)
Mongo uses only 130 MB of the memory in this case. In total, the ditto project uses about 20GB (after which our server was running out of memory and killed some processes). In the detailed overview below, you can find following memory consumptions:
- Gateway: 4GB
- Connectivity: 2.21GB
- Things: 1.97GB
- ... (some other services are also using double the amount of memory but these are the most important ones.

Did anyone else notice this as well? Is it possible we made a configuration error?
After the services restarted, the memory consumption came down but slowly increases again.

**Comment by Yannic92** [comment]
Uh, that doesn't sound good. Sounds much like a memory leak. Would it be possible to get a heap dump when memory consumption is very high? Would highly appreciate this.
Thank you very much for this finding!

**Comment by thjaeckle** [comment]
Hi Bob.
What do you use mainly in the Ditto gateway?
HTTP requests or Websockets? And when you use Websockets: mainly for getting data in or getting data out (events/notifications)?
That way we hopefully can better identify where to look.

And with which Java memory settings (Xmx, Xms) do you run the Ditto services?

**Comment by BobClaerhout** [comment]
> Would it be possible to get a heap dump when memory consumption is very high? Would highly appreciate this.

Both jmap and jcmd are not available in the container. Any hints on how to get this dump from within the container?

> What do you use mainly in the Ditto gateway?

Mainly (if not only) HTTP requests.

> And with which Java memory settings (Xmx, Xms) do you run the Ditto services?

These are the settnigs we currently use: `-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError`

Currently, the concierge is also using 4.6 GB of memory which makes me believe this might be an issue in some base component... Current top usage:
![image](https://user-images.githubusercontent.com/3315222/65947185-071aa900-e438-11e9-8531-001895538c00.png)

**Comment by ffendt** [comment]
Hi there,

basically getting a core dump should work the following way:
```bash
# get the container id & open a terminal in it
docker exec -it $theContainerId /bin/sh

# find out the PID of the java service:
ps aux 

# and kill with signal 6 - that will cause a coredump to be written into the container
kill -s 6 $thePIDOfTheJavaProcess

# the docker container will now be stopped - but its data can still be accessed
mkdir tmp/
docker cp $theContainerId:/ tmp/
```

**Comment by BobClaerhout** [comment]
The ditto dump is available here: https://transfer.sh/ytZ0k/ditto-dump.tar.gz (14 days)

**Comment by yufei-cai** [comment]
Thanks, we will take a look.

**Comment by yufei-cai** [comment]
@BobClaerhout The core dump file is about 16 GB. All heap objects take up ~450 MB, among which only ~100MB are reachable. There is no memory limit placed on the JVM process. Chances are the JVM thinks it has more memory than available on your server. MongoDB was probably experiencing a similar situation. It uses as much memory as it can for throughput.

If this is the issue, setting the JVM arguments
```
-XX:MaxRAMPercentage=3
-XX:InitialRAMPercentage=1
```
or
```
-Xms256m -Xmx512m
```
on the server with 20GB RAM should keep memory use at a reasonable level.

Which deployment did you use?

**Comment by thjaeckle** [comment]
Bob mentioned to already have `-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40` configured.
Maybe the docker container has no limits and uses the host OS memory settings?
Could be that an updated JDK in the Ditto image calculates the memory differently which caused the JVM process to "reserve" more memory.

**Comment by BobClaerhout** [comment]
@yufei-cai, @thjaeckle, thanks for the assistance. I changed the `-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40` to `-Xms256m -Xmx512m` and the memory usage graph reacted as follows:
![image](https://user-images.githubusercontent.com/3315222/66025701-64c1fa80-e4f7-11e9-99ac-6735de7acdbc.png)
The issue seems to be ressolved.
I am using the images from docker hub (1.0.0-M1a) and using the helm charts (from the master branch) to deploy. The environment variable is coming from the Helm chart:
```
   - name: IBM_JAVA_OPTIONS
     value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError"
```
I suggest changing the environment variable.

**Comment by thjaeckle** [comment]
I would suggest limiting the memory of the docker container in the helm chart
