### ISSUE TITLE
Multi-tenancy with OpenID Connect JWT claims

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#509]
Now that ditto has support for OpenID Connect, the so called multi-tenancy, or in other words the possibility to grant/restrict the right to create things in all of ditto, could be handled in a general way by using configurable claims.

Context
---

Currently every authenticated party in ditto has the basic rights to create things and hence has basic access to every namespace. There is currently no enforcement / check on access-rights for namespaces.

This is due to the fact that ditto does not implement any concept for authorization on a tenant level.

A way to get this implemented is now given due to the introduction of the OpenID Connect feature. An OpenID Connect provider like keycloak is used, to handle authorization contexts and access-right-management in a central place. In order for applications to work with the set access-rights from the OIDC provider, the used token for authentication may also contain authorization context in the form of claims, that provide more context on the authenticated user.

These claims can be used to implement a configurable authorization for the tenant level, handing the management to the OIDC provider while avoiding the management of policies on a tenant level.

Implementation
---

The factory `org.eclipse.ditto.services.concierge.starter.proxy.DefaultEnforcerActorFactory` could be a starting point to implement such a feature.

I'm not completely fit in developing java applications, but it'd be a nice exercise on the other hand.

**Comment by jokraehe** [comment]
Hi @w4tsn 
as stated on gitter, we plan to enhance the configuration of the oidc integration to support arbitrary claims for authorization. I have created a separate issue #512 for this.
I'm not entirely sure what your idea is to implement multi-tenancy to authorize users. Do you want to be able to configure subjects on a service level which are authorized to create things?

**Comment by w4tsn** [comment]
In contrast to the way the claims shall be used in #512 to enhance how subjects work in policies, this issue is about the possibility to use the used provider or the received claims, groups and/or roles in the jwt, to match this against the namespace, hance restricting the ability to create things everywhere to only a defined set.

I'm not quite sure yet, if it's just a matter of matching the provider to a namespace or if it's better to have information from the jwt like groups or roles (or any other assigned attribute) be the data to be used for the distinction. Using information provided by the OIDC provider in the JWT to see which namespace a user is eligible to add things to would enable a broad range of different infrastructures to integrate ditto on this level with existing authz management.

**Comment by JulianFeinauer** [comment]
@w4tsn this is a very interesting idea. But I'm not sure that I fully get your suggestion. Would it fit your suggestion, if initially, one could map one claim as "namespace" mapping (probably via REGEX). So that a user is only allowed to create things in a namespace that maps its "allowed_namespaces" claim (if it is set).

**Comment by w4tsn** [comment]
@JulianFeinauer yes, I think that would be a reasonable start. There are different ways one could think of segregating tenants via e.g. keycloak. You could use groups, one realm per tenant or just arbitrary claims. I think the latter like you suggested is the most configurable, which covers a lot of use-cases. Having the ability to configure this to use groups or realm names instead would be a quality of life enhancement if the architecture is designed around these concepts, since then have one field less to configure / touch.

The basic functionality to read and use arbitrary claims from a token is shared with #512 .

**Comment by thjaeckle** [comment]
This now is supported via #1251 
Therefore closing this issue. Please open another one if something is still missing.
