### ISSUE TITLE
Inconsistencies between things-service and search-index because of data which is too long to be indexed

### ISSUE THREAD

**Issue by danielFesenmeyer** [eclipse/ditto#51]
MongoDB has a limit of 1024 bytes per index entry: https://docs.mongodb.com/manual/reference/limits/#indexes
In the search-db, we create lots of index entries (e.g. for attributes). In things-db we do not create such indexes, because we do not need extensive search functionality there.
If a thing-event (or whole thing in case of sync) contains a single value which is too big to index, the whole update-operation of the search-updater will fail. This leads to data inconsistencies.

Therefore, we should truncate values which exceed the MongoDB limit.

**Comment by ffendt** [comment]
I think this issue was fixed in #38. Too long values are now truncated in the search-db.
