### ISSUE TITLE
Comprehensive AMQP 1.0 support for Ditto command responses

### ISSUE THREAD

**Issue by yufei-cai** [eclipse/ditto#540]
After #525, AMQP properties from Connectivity are retained in Ditto headers. However, further changes are necessary to use those properties to deliver Ditto command responses back to an AMQP broker via connectivity.

1. Header mapping: Currently no header mapping is possible for command responses, making it awkward to set response AMQP properties different from those of the incoming command.

2. Property/application property distinction: AMQP 1.0 permits application properties with the same name as an AMQP property. Ditto has no customization whether a header is written into properties or application properties, but that customization is important to meet the expectation of brokers.

**Comment by thjaeckle** [comment]
Hm, it's not only about AMQP 1.0 headers, is it?
Shouldn't be the title more generic as this affects all connectivity types as well?

Sure, the AMQP "properties vs. application properties" is also a topic which should be addressed.

**Comment by yufei-cai** [comment]
Response header mapping is relevant for RabbitMQ connectivity. It is useful for Kafka and HTTP connections, but those do not support sources for incoming commands yet.
