### ISSUE TITLE
Add POST things with specified namespace to HTTP API

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#550]
When using a custom namespaces there is currently no way to get things in a namespace with uuid generated. In this case the client has to generate the uuid itself.

I propose a new option for the `POST /things` endpoint, `namespace` so one can create new things via `POST /things?namespace=my.cool.namespace`

**Comment by thjaeckle** [comment]
Sounds good to me :+1:

**Comment by thjaeckle** [comment]
Hi @Pranshu-G 
Sure, a start would be:
* POST /things is handled here: https://github.com/eclipse/ditto/blob/f52c275b8888f10ce3d685d1a7154a2ccb263875/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/things/ThingsRoute.java#L174
* so in this method you could add another optional parameter "namespace": https://github.com/eclipse/ditto/blob/f52c275b8888f10ce3d685d1a7154a2ccb263875/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/things/ThingsRoute.java#L287-L301
* inside there `ThingBuilder.generateRandomTypedThing()` is used: https://github.com/eclipse/ditto/blob/f52c275b8888f10ce3d685d1a7154a2ccb263875/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/things/ThingsRoute.java#L318
* this would need an alternative, e.g. an overloaded `ThingBuilder.generateRandomTypedThingId(final CharSequence namespace)` which would create a UUID with a provided namespace
* and this would have to be used in the mentioned handling of "POST" requests

For connections in Ditto, this would also be required - but let's first get started with the easy part, the HTTP endpoint.
