### ISSUE TITLE
Can Ditto be deployed in Kubernetes ?

### ISSUE THREAD

**Issue by BobOntario** [eclipse/ditto#552]
Just want to know if Ditto can be deployed in K8S (not minikube)? Whether I can create eclipse-ditto-0.9.0.tgz from folder deployment/helm/eclipse-ditto? Is there any doc to introduce the Ditto deployment in k8S ?

**Comment by Yannic92** [comment]
Since minikube is just a one-node kubernetes cluster, yes it can.
You could choose to deploy via Helm or via kubernetes descriptor files.
See https://github.com/eclipse/ditto/tree/master/deployment

**Comment by BobOntario** [comment]
Thanks.  I saw kubernetes and helm require minikube. I don't want to use minikube, but regular kubernete that provided by the vendor, like AWS
