### ISSUE TITLE
Provide basic Grafana dashboards as starting point

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#558]
In order to set up a monitoring for Eclipse Ditto, we would like to provide some basic Grafana dashboards which we will maintain as part of the Ditto codebase.

E.g. those could be:
- GarbageCollection metrics of all services
- Roundtrip times to MongoDB (as measured by akka-persistence-mongo plugin)
- JVM metrics (all we get from the default MBeans like thread count, etc.)
- "Hot" entities count: how many Things/Policies are currently loaded into memory

**Comment by JulianFeinauer** [comment]
As we are currently setting up our monitoring of our Ditto instances via prometheus we could help in this area. My colleague Marco will setup some boards this week and could share them here as initial setup. WDYT?

**Comment by thjaeckle** [comment]
Done.
Grafana dashboards are here: https://github.com/eclipse/ditto/tree/master/deployment/operations/grafana-dashboards

**Comment by HusoBey21** [comment]
How to send datas by time interval via Ditto to Grafana or Prometheus?Can you help me?That is urgent.
