### ISSUE TITLE
Feature: Ditto External Authentication

### ISSUE THREAD

**Issue by rpahli** [eclipse/ditto#560]
We are currently started using ditto with JWT authentication. As there is no header support for the javascript websocket client and ditto also only maps the sub claim to authorization subjects we want to use a proxy in front of ditto to authenticate the users. But there is currently no option to pass information like authorization subjects to ditto.
Therefore, we want to implement a new authentication provider which can handle the header information send from the proxy.

Would a PR ok for you?

**Comment by thjaeckle** [comment]
Hi.

In fact there is an option to do that already.
The header "x-ditto-dummy-auth" may contain a pre authenticated subject eg injected by a nging proxy server.
While this was originally intended for development, the header name is still strange.
See also the nginx configuration on how to use it:
https://github.com/eclipse/ditto/blob/master/deployment/docker/nginx.conf

Could you check if that is sufficient for you?

Would be great if you could provide a better header name (maybe while still keeping the old one for compatability) via PR together with some documentation. 😉
