### ISSUE TITLE
Enrich outgoing events/messages with additional fields from Thing

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#561]
Currently, whenever a [change notification](https://www.eclipse.org/ditto/basic-changenotifications.html) / event is published (e.g. via WebSocket or the connectivity - AMQP, MQTT, Kafka, HTTP), only the actually changed values are contained in that published event.

So e.g. when only a temperature is updated (this is the Ditto Protocol message):
```json
{
  "topic": "org.eclipse.ditto/my-fancy-car/things/twin/commands/modify",
  "path": "/features/temperature/properties/status/value",
  "value": 23.5
}
```
Then a change event will only include exactly that information, as Ditto Protocol message:
```json
{
  "topic": "org.eclipse.ditto/my-fancy-car/things/twin/events/modified",
  "path": "/features/temperature/properties/status/value",
  "value": 23.5
}
```

There are however cases when there should be more information added to that event, e.g. when some additional metadata is needed when the event is processed.

In such cases it would of course work to do a HTTP GET on the Ditto HTTP API in order to fetch that additional information, but that causes additional roundtrips and additional latency which could be avoided.

So we would like to add the possibility to specify a further [field selector](https://www.eclipse.org/ditto/httpapi-concepts.html#with-field-selector) of additional thing data to select for all channels we send change notifications on:
* WebSocket
* Server Sent Events (SSEs)
* all connectivity types (AMQP, MQTT, ...)

For WebSocket that could e.g. look like:
```
START-SEND-EVENTS?extraFields=attributes,features/location
```

The actual change should/could be "merged" with the additionally selected fields, so the resulting Ditto Protocol events could look like:
```json
{
"topic": "org.eclipse.ditto/my-fancy-car/things/twin/events/modified",
"path": "/features/temperature/properties/status/value",
"value": 23.5,
"extra": {
  "attributes": {
    "manufacturer": "ACME corp"
  },
  "features": {
    "location": { 
      "longitude": 42.123,
      "latitude": 3.54
    }
  }
}
}
```

Messages and live commands/events should also be able to be enriched.

**Comment by thjaeckle** [comment]
One additional idea in order to prevent many remoting roundtrips in the Ditto cluster:

We could cache Things at the Ditto "edges" (gateway, connectivity services).
Apply a similar approach to the policy cache in concierge:
* use the Caffeine cache + cache loader in order to load non resolved Things
* the Caffeine cache has to be scoped to a single connection or session
   * scoped to an "auth subject" and configured `additionalFields`
* for the first event, when the "enhanced Thing" is not yet in the cache:
   * load the Thing with `additionalFields` via concierge
   * save the result in the cache
   * enhance the data from the event
   * the cache entry needs to be aware of the Thing revision
* for all following events:
   * check if the revision number of the event is the expected "next one" compared to the cached Thing
      * if yes: 
         * all data is available, no further "retrieve" required --> enhance the fields from the cache
         * do also update the cached Thing with the data from the event
         * increse revision number by 1
      * if no: 
         * apparently the connection/session missed an event
         * remove the cache entry and load it again via cache loader

For the "happy path" case (which should happen >99% of the time), only very few additional roundtrips are required.

Ditto needs some more memory consumption at the edges which should however be much better than additional cluster roundtrips.

Only problem with that approach:
* Policy changes might cause that the enriched Thing is not seen the way it should be 
   * that could be fixed by subscribing also for Policy of the Thing's Policy
   * additionally the cache entry could be evicted after a fix amount of time

**Comment by w4tsn** [comment]
This is a wonderful new feature - I'm currently caching things on the micro-service level to get meta information such as the definition field when processing incoming messages based on information from the model. This would make it much more easier!

**Comment by thjaeckle** [comment]
Cool, nice to hear that :)

**Comment by BobClaerhout** [comment]
Nice feature! We are looking forward to this as well!
