### ISSUE TITLE
Extend Ditto Protocol to support searching for things

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#575]
The [Ditto Protocol](https://www.eclipse.org/ditto/protocol-overview.html) currently supports CRUD operations on things, but not yet [searching for things](https://www.eclipse.org/ditto/basic-search.html).

We need to enhance the Ditto Protocol in order to enable searching via the various [bindings](https://www.eclipse.org/ditto/protocol-bindings.html) (WebSocket, AMQP1.0) and also in the Ditto Java client which makes use of the Ditto Protocol.

**Comment by yufei-cai** [comment]
@ottlukas and other potential stakeholders: We are starting development on a Ditto protocol extension for the search function. The current idea is to start a finite or infinite (reactive) stream of search results on request over any asynchronous channel (Websocket, AMQP or MQTT). Feel free to comment how you want the API to look like, on the protocol level or for the Ditto java and javascript clients.
