### ISSUE TITLE
Wording in documentation "list of properties"?

### ISSUE THREAD

**Issue by boaks** [eclipse/ditto#579]
According [Feature properties](https://www.eclipse.org/ditto/basic-feature.html#feature-properties) `The data related to Features is managed in form of a list of properties.`

The properties seems to be named, so isn't that rather a map?

**Comment by thjaeckle** [comment]
It's not a list in the sense of a Json array, correct.
So one could argue that the docs should speak about a "named list" of properties.

Contributions are welcome.
