### ISSUE TITLE
Support consuming messages from Apache Kafka in Ditto connections

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#586]
Currently Ditto can only [publish](https://www.eclipse.org/ditto/connectivity-protocol-bindings-kafka2.html) messages towards Apache Kafka, but cannot consume from Kafka.

In many architectures Apache Kafka is used at the edge (e.g. as mentioned [here](www.kai-waehner.de/blog/2020/01/01/apache-kafka-edge-computing-industrial-iot-retailing-logistics/)) which would require Device messages also be consumed via Ditto Connection "sources".

**Comment by kaiwaehner** [comment]
Looking forward to this feature.

As soon as available, I will build a demo and use this is a lightweight but scalable solution for a Digital Twin architecture (relates to my Digital Twin architectures discussed here: https://www.kai-waehner.de/blog/2020/03/25/architectures-digital-twin-digital-thread-apache-kafka-iot-platforms-machine-learning/)

**Comment by kaiwaehner** [comment]
Looking forward to this feature.

As soon as available, I will build a demo and use this is a lightweight but scalable solution for a Digital Twin architecture 
(relates to my [Digital Twin architectures with Apache Kafka](https://www.kai-waehner.de/blog/2020/03/25/architectures-digital-twin-digital-thread-apache-kafka-iot-platforms-machine-learning/))

**Comment by memelet** [comment]
Can someone leave a hint as to where in the codebase this would be added?

**Comment by thjaeckle** [comment]
@memelet that would have to be added to the following package:
https://github.com/eclipse/ditto/tree/master/services/connectivity/messaging/src/main/java/org/eclipse/ditto/services/connectivity/messaging/kafka

There we need:
* a `KafkaConsumerActor` extending `BaseConsumerActor`
* this consumer must be started in `KafkaClientActor.startConsumerActors(ClientConnected)` (protected class to be overwritten)
* have to think about consumer offset management (where and how to persist offsets)

The existing consumers for other protocols should give a good example on what needs to be implemented in the consumer:
* [AmqpConsumerActor](https://github.com/eclipse/ditto/blob/master/services/connectivity/messaging/src/main/java/org/eclipse/ditto/services/connectivity/messaging/amqp/AmqpConsumerActor.java)
* [RabbitMQConsumerActor](https://github.com/eclipse/ditto/blob/master/services/connectivity/messaging/src/main/java/org/eclipse/ditto/services/connectivity/messaging/rabbitmq/RabbitMQConsumerActor.java)
* [AbstractMqttConsumerActor](https://github.com/eclipse/ditto/blob/master/services/connectivity/messaging/src/main/java/org/eclipse/ditto/services/connectivity/messaging/mqtt/hivemq/AbstractMqttConsumerActor.java)

The Ditto team has the Kafka consumer topic on its short- to mid-term agenda - as Eclipse Hono now also supports Kafka since the just released version 1.6, that will be the future of connecting Ditto and Hono.

I am however not yet sure if the Kafka consumer will make it in the upcoming Ditto 2.0 release (which we target for March/April).

Are you planning to start working on the Kafka consumer @memelet or is a time horizon of 2-3 months until the Ditto committers start to work on that sufficient for you?

**Comment by memelet** [comment]
@thjaeckle The 2-3 month range is probably fine for us. But we need to do some spikes to see how ditto will handle our loads. We ingest a many MB\s across thousands of industrial devices. Right now we persist that data in bulk and publish some of it live for clients via activemq over websockets. That data also flows into various streaming pipelines, of which some output would be routed back to ditto. 

Could be that we will to filter/downsample/denounce some of the data before it hits ditto.

**Comment by memelet** [comment]
@thjaeckle  Why would you need to manage offsets? That should be handled by kafka and stored back in the kafka cluster (assuming the consumer group remains constant).

**Comment by rajkraleti** [comment]
Hello All, 

I have tried integration of Ditto with Apache Kafka by publishing the Ditto Protocol format messages in Kafka & Created a connection to apache Kafka from using Ditto connections as a source(consumer side) , How ever Ditto is not reading any messages , Where can I debug this by checking logs or something , Can we have an example or demonstration for Apache Kafka Integration with eclipse Ditto.
