### ISSUE TITLE
Connecting Locally running Ditto with Locally running Hono(Helm based deployment)

### ISSUE THREAD

**Issue by writetoatulkumar** [eclipse/ditto#591]
sudo curl -i -X POST http://$REGISTRY_IP:28080/v1/tenants
_**Then creating variable and storing my id of tenant in it**_
export MY_TENANT=335280ce-13c0-470b-9bd4-0f8743d17fea

curl -i -X POST http://$REGISTRY_IP:28080/v1/devices/$MY_TENANT
**_then creating variable and storing my id of device in it_**
export MY_DEVICE=85545803-0bf7-4e76-83dd-5fb075d8500f

export MY_PWD=my-pwd
curl -i -X PUT -H "content-type: application/json" --data-binary '[{
"type": "hashed-password",
"auth-id": "'$MY_DEVICE'",
"secrets": [{
"pwd-plain": "'$MY_PWD'"
}]
}]' http://$REGISTRY_IP:28080/v1/credentials/$MY_TENANT/$MY_DEVICE

export AMQP_NETWORK_IP=$(sudo kubectl get service hono-dispatch-router-ext --
output='jsonpath={.status.loadBalancer.ingress[0].ip}' -n hono)

_**I didnot started the consumer Downstream Application**_

curl -X POST -i -u ditto:foobar -H 'Content-Type: application/json' -d '{
"targetActorSelection": "/system/sharding/connection",
"headers": {
"aggregate": false
},
"piggybackCommand": {
"type": "connectivity.commands:testConnection",
"connection": {
"id": "hono-sandbox-connection-1",
"connectionType": "amqp-10",
"connectionStatus": "open",
"uri": "amqp://consumer%40HONO:verysecret@$AMQP_NETWORK_IP:15672",
"failoverEnabled": true,
"sources": [{
"addresses": [
"telemetry/$MY_TENANT",
"event/$MY_TENANT"
],
"authorizationContext": ["nginx:demo5"]
}]
}
}
}' https://localhost:8080/devops/piggyback/connectivity?timeout=8000
Enter host password for user '-u':
***on localhost:8080 my ditto is running***

**_Errors:_**
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by JulianFeinauer** [comment]
Could you do a `echo $AMQP_NETWORK_IP` after the command `export AMQP_NETWORK_IP=$(sudo kubectl get service hono-dispatch-router-ext --
output='jsonpath={.status.loadBalancer.ingress[0].ip}' -n hono)`, what does it show?

**Comment by thjaeckle** [comment]
The hostname in the URL of the curl request is wrong:
https://$MY_TENANT/devops/piggyback/connectivity?timeout=8000

Pretty sure that the variable resolves to a uuid which is no valid hostname.

**Comment by writetoatulkumar** [comment]
> Could you do a `echo $AMQP_NETWORK_IP` after the command `export AMQP_NETWORK_IP=$(sudo kubectl get service hono-dispatch-router-ext -- output='jsonpath={.status.loadBalancer.ingress[0].ip}' -n hono)`, what does it show?

echo $AMQP_NETWORK_IP
10.96.209.251

**Comment by writetoatulkumar** [comment]
> The hostname in the URL of the curl request is wrong:
> https://$MY_TENANT/devops/piggyback/connectivity?timeout=8000
> 
> Pretty sure that the variable resolves to a uuid which is no valid hostname.

then what could be the probable solutions?

**Comment by writetoatulkumar** [comment]
> The hostname in the URL of the curl request is wrong:
> https://$MY_TENANT/devops/piggyback/connectivity?timeout=8000
> 
> Pretty sure that the variable resolves to a uuid which is no valid hostname.

i tried to use the host where ditto is installed i.e. localhost:8080

it gave me the error:
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by thjaeckle** [comment]
> it gave me the error:
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

You don't have a technical background regarding http and web services, do you? 
Use http instead of https.

I'll close this "issue" as we don't want to use github issues for very basic understanding questions. 
Please use stackoverflow for that.

**Comment by writetoatulkumar** [comment]
HTTP/1.1 401 Unauthorized
Server: nginx/1.13.12
Date: Mon, 13 Jan 2020 06:09:59 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 38
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
WWW-Authenticate: Basic realm="DITTO-DEVOPS",charset=UTF-8
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Authorization,Cache-Control,Content-Type,Content-Length,DNT,If-Match,If-Modified-Since,If-None-Match,Keep-Alive,Origin,User-Agent,X-Requested-With
