### ISSUE TITLE
Test “Command & Control” feature failed

### ISSUE THREAD

**Issue by aaron0609** [eclipse/ditto#593]
I'm following the steps in [Using Eclipse Hono's Command&Control with Eclipse Ditto](https://www.eclipse.org/ditto/2018-12-05-example-command-and-control.html)
But I'm not using the sandbox. I created the tenant "gz" with device-id "gz:teapot" in hono while I created a new thing with namespace "gz" & thing-id "teapot" using my default ditto nginx user.

Then I created the connection as the following:
`_create = {
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
      "aggregate": "false"
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "id": connection_id,
            "connectionType": "amqp-10",
            "connectionStatus": "open",
            "failoverEnabled": True,
            "uri": "amqps://hono:*******@hono-messaging.*******.com:5671",
            "sources": [
                {
                    "addresses": [
                        "control/{}/replies".format(tenant_id)
                    ],
                    "authorizationContext": [
                        "nginx:ditto"
                    ],
                    "headerMapping": {
                        "correation-id": "{{ header:correlation-id }}",
                        "status": "{{ header:status }}",
                        "content-type": "{{ header:content-type }}"
                    }
                }
            ],
            "targets": [{
                "address": "control/{0}/{{ thing:name }}".format(tenant_id),
                "authorizationContext": [
                     "nginx:ditto"
                    ],
                "topics": ["_/_/things/live/messages"],
                "headerMapping": {
                     "message-id": "{{ header:correlation-id }}",
                     "reply-to": "control/gz/replies",                                                                                                                            
                   }                                                                                                                                                                                  
                }]                                                                                                                                                                                    
            } 
        }
    }`

Then I started the [Signal availability of device](https://www.eclipse.org/ditto/2018-12-05-example-command-and-control.html#signal-availability-of-device) and send the message using the following command:
`curl -i -X POST 'https://ditto-test.*******.com/api/2/things/gz:teapot/inbox/messages/brew?timeout=60' \
     -u ditto:****** \
     -H 'x-correlation-id: command-and-control' \
     -d '{"targetTemperature":85}'`
Finally I see the error:
`{
  "status": 503,
  "message": "Failed to send message: Timed out waiting for credit to send Message",
  "description": "Sending the message to an external system failed, please check if your connection is configured properly and the target system is available and consuming messages.",
  "error": "connectivity:message.sending.failed"
}`

I checked the document but found nothing about this error, do you have any idea on this?

**Comment by thjaeckle** [comment]
`Failed to send message: Timed out waiting for credit to send Message`
This is an error produced by Eclipse Hono or the AMQP 1.0 network Hono is using.

That happens when there is no device connected to Hono subscribed for receiving commands.
Did you subscribe our device via MQTT to Hono commands?

**Comment by thjaeckle** [comment]
Closing due to: no more input on that ..
