### ISSUE TITLE
Overloaded protocol adapter methods put live signals in the TWIN channel

### ISSUE THREAD

**Issue by yufei-cai** [eclipse/ditto#599]
These methods produce twin signals even when given a live signal as argument:
```
ProtocolAdapter#toAdaptable(Event)
ProtocolAdapter#toAdaptable(Command)
```
There may be more. This is not intuitive.

Propose to deprecate the overloaded methods and leave only
```
ProtocolAdapter#toAdaptable(Signal)
```
All other `toAdaptable` methods should simply delegate to this method. `ProtocolAdapter#toAdaptable(Signal)` does put signals in the correct channel.

What do you guys think?

**Comment by jufickel-b** [comment]
IMHO we should have a deeper look at the interface. The implementation has many chains of 'instanceof' checks which indicates possible abstraction failure.
