### ISSUE TITLE
Add "definitions" field to Ditto features pointing to Vorto functionblocks

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#60]
First step towards Eclipse Vorto integration:
* add an optional field "definitions" in features aside of "properties" containing a list of string identifiers targeting Vorto Functionblocks

Format:
```json
"features": {
  "my-lamp": {
    "definition": [ "org.eclipse.example:Lamp:1.0.0" ],
    "properties": {
      ....
    }
  }
}
```

**Comment by jufickel-b** [comment]
Added definition to Feature, see [Feature Definition](https://www.eclipse.org/ditto/basic-feature.html#feature-definition).
