### ISSUE TITLE
Add devOps api function to get a list of all configured connections

### ISSUE THREAD

**Issue by patrickse** [eclipse/ditto#605]
According to @thjaeckle there´s currently no way to use the API to list all the configured connections. The only way to get an overview is querying the connectivity mongodb.

I think, adding a new devOps command to list all configured connections would make the whole connectiviy-api more feature complete and makes ditto connections management a lot easier.

Maybe something like this...

```json
{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
      "aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:listConnections"
    }
}
```

The response could contain an array of elements with the following properties:
 - connectionId
 - connectionStatus
 - createdOn

That is probably enough to identify the configured connections at the moment.

**Comment by Yannic92** [comment]
I suggest to name this command "connectivity.commands:retrieveConnections" to match the name of RetrieveThings for example.

Regarding the content of the response I'd either put only connectionIds in the response or the full JSON of all connections.

The latter would result in a big message, which could be a problem because of the maximum message size in the ditto cluster.

Put these selected fields in the response seems a bit randomly chosen to me.

Would it be enough for your use case to get a list of all connection IDs which you could then retrieve one by one?

**Comment by patrickse** [comment]
I am fine with the name of the command :) good point to reuse the naming scheme. 

And I am pretty sure returning the complete connections details during `retrieveConnections` will make things much more complicated. ;) 

Returning just the `connectionId` is ok for me. 👍

**Comment by thjaeckle** [comment]
@Yannic92 I'm not sure if `retrieveConnections` would lead to confusions as `retrieveThings` requires a list of IDs passed in and as a result you get the actual payload of the ThingIDs you asked for.

So maybe intentionally choosing another term like
* listConnectionIds
* findConnectionIds
etc. could be beneficial.

**Comment by Yannic92** [comment]
@thjaeckle Valid point. RetrieveAttributes, RetrieveFeatures, RetrieveThings are all commands that receive something based on a given information.
I'm don't want to pedantic about naming, just one last suggestion is `RetrieveAllConnectionIds`.
It is consistent with the "Retrieve"-naming scheme and it indicates that it contains all existing connection IDs.

**Comment by thjaeckle** [comment]
When implementing this, getting all "connection IDs" should be queried by using the Akka persistene read journal `readJournal.currentPersistenceIds();`, see:
https://doc.akka.io/docs/akka/2.5.30/persistence-query.html#persistenceidsquery-and-currentpersistenceidsquery

The new `RetrieveAllConnectionIds` command should be handled by e.g. a new actor in the "connectivity" service.
