### ISSUE TITLE
Error: Cannot start service swagger-ui when attempting to start Ditto

### ISSUE THREAD

**Issue by stfnp** [eclipse/ditto#628]
Trying to run Ditto by following the instructions in the readme gives me the following error:

    ditto-master\deployment\docker> docker-compose up -d
    Removing docker_swagger-ui_1
    docker_policies_1 is up-to-date
    Recreating be117b1f9e95_docker_swagger-ui_1 ...
    docker_mongodb_1 is up-to-date
    docker_concierge_1 is up-to-date
    docker_things-search_1 is up-to-date
    docker_things_1 is up-to-date
    docker_connectivity_1 is up-to-date
    Recreating be117b1f9e95_docker_swagger-ui_1 ... error                                                                        
    ERROR: for be117b1f9e95_docker_swagger-ui_1  Cannot start service swagger-ui: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/uC/192.168.180.250/Home/Software/ditto-master/deployment/docker/swagger3-index.html\\\" to rootfs \\\"/var/lib/docker/overlay2/2363352a028798b840a06d1a598fbd429e6adc0e3e643b631baef82ac3c96cff/merged\\\" at \\\"/var/lib/docker/overlay2/2363352a028798b840a06d1a598fbd429e6adc0e3e643b631baef82ac3c96cff/merged/usr/share/nginx/html/index.html\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

    ERROR: for swagger-ui  Cannot start service swagger-ui: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/uC/192.168.180.250/Home/Software/ditto-master/deployment/docker/swagger3-index.html\\\" to rootfs \\\"/var/lib/docker/overlay2/2363352a028798b840a06d1a598fbd429e6adc0e3e643b631baef82ac3c96cff/merged\\\" at \\\"/var/lib/docker/overlay2/2363352a028798b840a06d1a598fbd429e6adc0e3e643b631baef82ac3c96cff/merged/usr/share/nginx/html/index.html\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
    ERROR: Encountered errors while bringing up the project.

I tried the Ditto 1.0.0 release as well as the current master branch with the same result. I'm running Windows 10 with Docker version 19.03.5 and docker-compose version 1.25.4.

Any ideas what could be wrong here?

**Comment by thjaeckle** [comment]
Hi.
Is your Docker for windows configured to share drives?
I don't use Docker for windows any longer but as far as I remember you can/must configure to e.g. Share your C drive with Docker.

If that doesn't help: the swagger ui isn't mandatory, so you could remove it from the Docker Compose file.

**Comment by stfnp** [comment]
You're right, putting the files on a local drive and sharing them with Docker solved the problem. They were on a network drive before. Thank you very much for your help!
