### ISSUE TITLE
502-BadGateway

### ISSUE THREAD

**Issue by danielanghell** [eclipse/ditto#651]
Hello,

     I have instantiated the Ditto system on my Linux virtual machine but every time I reboot this machine and try to use the localhost:8080/api/2 feature ( for example to search for things ), I get 502 Bad Gateway error. This happens almost every single time. Sometimes it works just to restart the ngninx container, but in the majority of the cases it doesn't work at all. I was wondering if there is any issue regarding the system, or if it's built this way to keep on working without restarting it. 

P.S.: My type of network adapter using VirtualBox is bridged adapter, if this information might help you.

**Comment by thjaeckle** [comment]
How did you start Ditto?
With `docker-compose`?

I think better suited for an automatically restarting "service" like Ditto is a Kubernetes based deployment with a local minikube.

Please be aware that this might however also not work as you intend it to - Ditto is intended to run as (cloud) service 24/7 - the start mechanisms we provide e.g. with `docker-compose` are meant to make it easy to start Ditto for local development.

**Comment by danielanghell** [comment]
I started it with docker-compose indeed. I might try starting it with Kubernetes. Thank you for advice!
