### ISSUE TITLE
Responses should not decide whether they're required

### ISSUE THREAD

**Issue by Yannic92** [eclipse/ditto#677]
Right now responses to messages are dropped if they have a response-required header set to false.

This can be found [here](https://github.com/eclipse/ditto/blob/57a6f85b3e63c377c08f363e49d45703ea72216f/services/connectivity/messaging/src/main/java/org/eclipse/ditto/services/connectivity/messaging/MessageMappingProcessorActor.java#L593).

In my opinion it does not make sense for a response to decide whether it is required or not.
Only the initial requester knows if a response is required. Therefore the filtering of required responses should not be made based on response headers.

This behaviour already lead to a bug, because ditto client did set response-required to false for responses because they were sent without a response consumer (which is totally valid because we don't want to have a response to the response).

**Comment by thjaeckle** [comment]
Fixed via #734
