### ISSUE TITLE
Support for policy wildcard in message:/features

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#685]
It is possible to assign READ and WRITE permissions for /inbox and /outbox on a thing level or specific feature level. From the documentation however it seems that a wildcard of the form `message:/features/*/inbox` is not possible.

For a use-case I'd like to enforce the usage of message:/features/*/inbox instead of message:/inbox, but I don't care about the actual feature in the policy and I don't want to write down every possible feature there is in the policy. I require the full feature / property path in the message because of the metadata it contains.

**Comment by dguggemos** [comment]
Actually we also have the very same task in our backlog, but currently no plans to implement it.

**Comment by thjaeckle** [comment]
I'll close this in favor of #708 where the wildcard in policies should also be supported not only for the `message:` resource but also for the `thing:` resource.
