### ISSUE TITLE
Additional x.y container release tag

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#690]
Just as an idea useful for a certain container update pattern it could be useful to additionally publish a tag on the container registry (docker hub) of the form x.y for every z release (x.y.z).

Example:

There is a tag for 1.1.0. If now a version 1.1.1 is pushed, two tags are published: 1.1.1 and latest with this image. If there would be another tag 1.1, which is always updated when there is a release for 1.1.x then one could pin to that version and automatically receive all hotfix/maintenance updates without touching the configuration. This is a useful container update pattern I like to use ;)

**Comment by thjaeckle** [comment]
Yes, that's indeed a good idea 👍

**Comment by thjaeckle** [comment]
@w4tsn the just built 1.1.2 release is now on Docker Hub and tagged with:
* 1.1.2
* 1.1
* 1
* latest

See: https://hub.docker.com/r/eclipse/ditto-things/tags?page=1&ordering=last_updated
