### ISSUE TITLE
DLL files detected in docker images

### ISSUE THREAD

**Issue by aaron0609** [eclipse/ditto#691]
I retrieved the jar files from official docker images eclipse/ditto-XXXX:1.1.0 and made a Sonatype scan based on Ditto components, but from the Sonatype report, it seems the jar file contains some windows dll files which is marked as "Policy Violations".

- jffi-1.2.dll

- lmdbjava-native-windows-x86_64.dll

Are these “dll” components really necessary for Ditto? Or is there any way to resolve that issue to pass the Sonatype check?

**Comment by thjaeckle** [comment]
Hi @aaron0609 

The DDL files are part of 2 transitive dependencies, jffi and lmbdjava which Ditto relies on.
The jar files of those include native libraries for various operating systems.

The "allinone" jars of Ditto are ["shaded"](https://maven.apache.org/plugins/maven-shade-plugin/) jars extracting all used jars, so the native libraries also appear in them.
