### ISSUE TITLE
"Create new Thing" operation returns wrong "Thing ID"

### ISSUE THREAD

**Issue by ctron** [eclipse/ditto#707]
Executing the "create new thing" operation from API v2 (`POST /things`), providing the default example content, using the Swagger UI, returns:

~~~json
{
  "thingId": ":304cd223-fca7-491a-8dc0-53fe271d478e",
  "policyId": ":304cd223-fca7-491a-8dc0-53fe271d478e",
  "definition": "com.acme:coffeebrewer:0.1.0",
  "attributes": {
    "manufacturer": "ACME demo corp.",
    "location": "Berlin, main floor",
    "serialno": "42",
    "model": "Speaking coffee machine"
  },
  "features": {
    "coffee-brewer": {
      "definition": [
        "com.acme:coffeebrewer:0.1.0"
      ],
      "properties": {
        "brewed-coffees": 0
      }
    },
    "water-tank": {
      "properties": {
        "configuration": {
          "smartMode": true,
          "brewingTemp": 87,
          "tempToHold": 44,
          "timeoutSeconds": 6000
        },
        "status": {
          "waterAmount": 731,
          "temperature": 44
        }
      }
    }
  }
}
~~~

I would expect the thing ID to be `304cd223-fca7-491a-8dc0-53fe271d478e`, however that is not accepted by calls to the other APIs.

**Comment by thjaeckle** [comment]
I think you missed the colon before the ID.
The `POST` endpoint will always create a thingId (a UUID in an empty namespace, thus `:<UUID>`).

A `thingId` in Ditto always consists of thing "namespace" and "name" separated with a colon, however the namespace may be empty:
https://www.eclipse.org/ditto/basic-namespaces-and-names.html

**Comment by ctron** [comment]
Yes … that was indeed the case :facepalm: … PEBKAC :grin: Sorry for that.
