### ISSUE TITLE
Is there a secure way to share devops account with multi ditto users?

### ISSUE THREAD

**Issue by tiexinyang** [eclipse/ditto#719]
As we know devops user can operate ditto connections, but it seems there could be only one devops user available in ditto cluster
Is there a proper way to share devops account among multi ditto users without affecting each other?

**Comment by thjaeckle** [comment]
Yes, there is only one devops (or admin) user in Ditto and this user has very broad rights using the [DevOps commands](https://www.eclipse.org/ditto/installation-operating.html#devops-commands).

What do you mean with "share devops account among multi ditto users without affecting each other"?
Sharing that account basically means that each one can administer the Ditto installation (e.g. creating/modifying connections but also accessing things/policies, etc.).

**Comment by tiexinyang** [comment]
> Yes, there is only one devops (or admin) user in Ditto and this user has very broad rights using the [DevOps commands](https://www.eclipse.org/ditto/installation-operating.html#devops-commands).
> 
> What do you mean with "share devops account among multi ditto users without affecting each other"?
> Sharing that account basically means that each one can administer the Ditto installation (e.g. creating/modifying connections but also accessing things/policies, etc.).

Yes the situation is I would like to make each user has full access to his own resources, including creating & managing their own connections, without the risk of affecting others' connections(e.g. User a cannot delete connection which is created by user B)
Well it seems not possible right now, unless creating another ditto cluster for dedicated user.

**Comment by thjaeckle** [comment]
Yes, unfortunately that's not possible as Ditto is intended to be run under a "single tenant".
Multi tenancy is one of the commercial features of the commercial offering based on Ditto, the [Bosch IoT Things](https://developer.bosch-iot-suite.com/service/things/) service.

**Comment by JulianFeinauer** [comment]
@thjaeckle if this question is allowed... how do you model the multi tenancy in Bosch IoT Suite? Multiple instances in the background or an Extension of Ditto with native implementation?

**Comment by thjaeckle** [comment]
@JulianFeinauer you may ;)
It is a single instance with native, closed source, enhancements for multi tenant management.
