### ISSUE TITLE
Can Ditto connect to mosquitto by username:password with tcp url ?

### ISSUE THREAD

**Issue by vu-nhan** [eclipse/ditto#764]
Hi all

I try do connect Ditto with Mosquitto with the basic authentication.

But Ditto can not connect to Mosquitto, here's my json config.

 "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "id": "my id",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://username:password@my-ip:my-port",
            .....
        }
    }

Thank you.

**Comment by thjaeckle** [comment]
Yes, Ditto can connect via plain TCP to an MQTT broker.
What's the error message you encounter?
Did you check the logs of the `connectivity` service for further information?
