### ISSUE TITLE
Connectivity service does not consume message after reconnect to AMQP (0.9.1) 

### ISSUE THREAD

**Issue by qthuy** [eclipse/ditto#770]
Ditto connectivity service does not consume message after reconnect to AMQP (0.9.1).

Ditto version: 1.1.3
AMQP: rabbitmq:3.8.5
Environment: kubernetes 1.14

Step to reproduce:
1. Configure ditto connectivity service to consume from AMQP.
2. Confirm that ditto can consume and process ditto message from AMQP.
3. Delete rabbitmq cluster PODs (simulate rolling upgrade on rabbitmq).
4. Confirm that rabbitmq cluster re-created ok.
5. Confirm that ditto connectivity service re-connect to AMQP ok.
6. Send ditto message on AMQP.
7. Expect ditto connectivity service to consume and process the message, but it does not until I restart the ditto connectivity POD.

I collected log for ditto connectivity service below.
[ditto-connectivity.log](https://github.com/eclipse/ditto/files/5120169/ditto-connectivity.log)

**Comment by thjaeckle** [comment]
Thank you for your bug report.

From the logs, do I understand correctly that:
* you have 2 AMQP 0.9.1 connections 
   * `rabbit-ditto-connection-source-3` with both sources (consuming from RabbitMQ) and targets (publishing to RabbitMQ)?
   * `rabbit-ditto-connection-target-3` only with a target (publishing to RabbitMQ)?
* the connectiond are successfully re-established
   `2020-08-24 22:24:15,222 INFO  ... Established RMQ connection: amqp://ditto-user@172.20.204.247:5672/`
* however neither consuming messages (via the sources) or publishing messages (via the targets) works?

**Comment by qthuy** [comment]
I setup rabbit-ditto-connection-source-3 as source only (send message to ditto) and rabbit-ditto-connection-target-3 as target only (get notifications from ditto).

Yes, connectivity service stop consuming message from rabbit-ditto-connection-source-3 with this bug. I usually only get notification after I send a modify message to ditto using rabbit-ditto-connection-source-3, so not sure if ditto still continue to send to rabbit-ditto-connection-target-3 or not.

rabbit-ditto-connection-source-3:

{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
        "aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:modifyConnection",
        "connection": {
            "id": "rabbit-ditto-connection-source-3",
            "connectionType": "amqp-091",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "amqp://ditto-user:xyz@external-components-rabbitmq-ha.external-components.svc.cluster.local:5672",
            "sources": [
                {
                    "addresses": [
                        "ditto-source"
                    ],
                    "authorizationContext": ["nginx:ditto"]
                }
            ]
        }
    }
}

rabbit-ditto-connection-target-3:
{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
        "aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:modifyConnection",
        "connection": {
            "id": "rabbit-ditto-connection-target-3",
            "connectionType": "amqp-091",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "amqp://ditto-user:xyz@external-components-rabbitmq-ha.external-components.svc.cluster.local:5672",
            "targets": [
                {
                    "address": "ditto-target/msg",
                    "topics": [
                        "_/_/things/twin/events",
                        "_/_/things/live/messages",
                        "_/_/things/live/commands",
                        "_/_/things/live/events"
                    ],
                    "authorizationContext": ["nginx:ditto"]
                }
            ]
        }
    }
}

**Comment by thjaeckle** [comment]
Thanks, I'll have a look on it.

**Comment by thjaeckle** [comment]
Will be fixed in Ditto 1.2.0 which we build today.
@qthuy would be great, if you could verify that your problem is solved with Ditto 1.2.0

**Comment by qthuy** [comment]
Will do, thank you for the quick response.

**Comment by qthuy** [comment]
Confirmed that Ditto 1.2.0 fixed this issue.

**Comment by thjaeckle** [comment]
@qthuy do you use Ditto for commercial purposes? It would be great then to show your adoption of it via the https://iot.eclipse.org/adopters/ page.

**Comment by qthuy** [comment]
We are currently evaluating Ditto in our product. Will add my company to the adopters page once we finalize on Ditto.
