### ISSUE TITLE
Logging might cause NPE

### ISSUE THREAD

**Issue by jufickel-b** [eclipse/ditto#773]
`ThingCommandEnforcement` uses a `DittoDiagnosticLoggingAdapter`.
As all of Ditto's loggers, this logger is not thread-safe. However, `ThingCommandEnforcement` happens to access the logger in parallel. This leads to a `NullPointerException` where in `DittoDiagnosticLoggingAdapter` the correlation ID is made a String.

A first, defensive, approach to circumvent that NPE is to not call `toString` on the correlation ID but passing it down to LogUtil as CharSequence. Furthermore, `ThingCommandEnforcement` should not use its parent's logger but its own (which should be a `DittoLogger`).
Both measures do not remedy the problem of tangled correlation IDs due to parallel calls to logger. To address this it would be necessary to introduce a synchronized wrapper for `DittoLogger` and `DittoDiagnosticLoggingAdapter` which could be used where needed.

**Comment by thjaeckle** [comment]
> introduce a synchronized wrapper

Veto, I think that is performance wise a really bad idea. Better to have some wrongly correlated log-statements then IMO.

**Comment by jufickel-b** [comment]
Veto is veto.

How about a new type like `ThreadSafeDittoLogger` which differs from the already existing `DittoLogger` in a way that it only provides the `withCorrelationId` methods as well as the `discardCorrelationId` method.

An immutable implementation of that type could return a new logger instance for each of those methods which guarantees thread safety.

Furthermore a different type with an obvious name might prevent unnecessary usage.
