### ISSUE TITLE
Make is possible to delete metadata from a thing

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#779]
With #680 it is possible to put/set arbitrary metadata to a digital twin (thing).
It however is not possible to delete a once set metadata - it is only possible to e.g. set the metadata's value to `null`.

In scenarios where deletion is favorable it would be good to make deletion possible.

The syntax of deletion could look like, as an additional header "delete-metadata":
```
delete-metadata:
[
  "issuedAt"
]
```

**Comment by jufickel-b** [comment]
As the header names for metadata now contain verbs, this is a nice approach IMHO.
