### ISSUE TITLE
Putting _metadata while creating a Thing does not work

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#801]
When creating a thing, the "put-metadata" is not considered in order to put metadata.
This only works when updating an already existing thing.

To reproduce:

# Create Thing via HTTP

```
PUT https://ditto.eclipse.org/api/2/things/org.eclipse.ditto:metadata-test-2
Header:
put-metadata: [{"key": "*/creator", "value": "TJ the great"}]
```

# Retrieve metadata

```
GET https://ditto.eclipse.org/api/2/things/org.eclipse.ditto:metadata-test-2?fields=thingId,attributes,_metadata
```

## Result

```json
{
    "thingId": "org.eclipse.ditto:metadata-test-2",
    "attributes": {
        "foo": 42
    }
```

## Expected Result

```json
{
    "thingId": "org.eclipse.ditto:metadata-test-2",
    "attributes": {
        "foo": 42
    },
    "_metadata": {
        "thingId": {
            "creator": "TJ the great"
        },
        "policyId": {
            "creator": "TJ the great"
        },
        "attributes": {
            "foo": {
                "creator": "TJ the great"
            }
        }
    }
}
```

**Comment by thjaeckle** [comment]
Also observed behavior which is still not as desired:

When updating e.g. only a single attribute "x" of a Thing and specifying e.g. `"put-metadata"` to apply to put a metadata to all affected leaves with `"key`": `"*/foo"

Not only the attibute "x" is updated with that new "foo" metadata, but all JSON leaves in the existing Thing, also "thingId", etc.

**Comment by jufickel-b** [comment]
Fixed with PR https://github.com/eclipse/ditto/pull/813
