### ISSUE TITLE
How do I filter by key values if I do not know the exact spelling of the key?

### ISSUE THREAD

**Issue by oscarfh** [eclipse/ditto#818]
In [the search API](https://www.eclipse.org/ditto/http-api-doc.html?urls.primaryName=Ditto%20API%20v2#/Things-Search/get_search_things), I read

> The search is case sensitive. In case you don't know how exactly the spelling of the namespace, name, attribute, feature etc. is, use the like notation for filtering

that leads me to think that I can do something like this

`eq(like(attributes/location.*),"kitchen")`

To retrieve all things in which there is an attribute that starts with `location` and has a value `kitchen`.

Is my interpretation correct? If yes, how can I build such a query? I am getting 400's errors for all alternatives I am trying.

**Comment by thjaeckle** [comment]
Sorry, that is currently not possible, you have to know the attribute names.
`like` is only usable for values.
Also, [the RQL syntax](https://github.com/persvr/rql) does not even provide the possibility to do this AFAIK.
