### ISSUE TITLE
mqtt connection with username and password

### ISSUE THREAD

**Issue by vicanfon** [eclipse/ditto#834]
I want to establish a connection to an MQTT broker that requires a username and password.
Is this type of connection supported by ditto?

I can only see in the documentation the CERT-based authentication.

Thanks,

**Comment by thjaeckle** [comment]
Hi @vicanfon 

Yes, it is .. it seems not to be documented very well however :(

Just use the username and password as part of the connection URI, e.g.:
```
tpc://user:password@localhost:1883
```

If you want to improve the documentation, we would really appreciate a PullRequest adding this to the docs:
* for MQTT 3.1.1: https://github.com/eclipse/ditto/blob/master/documentation/src/main/resources/pages/ditto/connectivity-protocol-bindings-mqtt.md
* for MQTT 5: https://github.com/eclipse/ditto/blob/master/documentation/src/main/resources/pages/ditto/connectivity-protocol-bindings-mqtt5.md
