### ISSUE TITLE
docker containers excited with code 255

### ISSUE THREAD

**Issue by silence3322** [eclipse/ditto#842]
policies_1       | 2020-10-15 04:04:07,854 WARN  [] a.r.a.Association Association(akka://ditto-cluster) - Association to [akka://ditto-cluster@172.18.0.8:2551] with UID [-4534051078360594105] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote ActorSystem must be restarted to recover from this situation. Reason: Cluster member removed, previous status [Down]
policies_1       | 2020-10-15 04:04:07,868 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:07,974 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,045 WARN  [] a.r.a.Association Association(akka://ditto-cluster) - Association to [akka://ditto-cluster@172.18.0.6:2551] with UID [2407170556327880823] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote ActorSystem must be restarted to recover from this situation. Reason: Cluster member removed, previous status [Down]
policies_1       | 2020-10-15 04:04:08,054 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,063 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,242 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,314 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,430 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,454 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,552 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:08,620 INFO  [] a.c.ClusterGossip akka://ditto-cluster@172.18.0.3:2551/system/cluster/core/daemon - Cluster Node [akka://ditto-cluster@172.18.0.3:2551] - Ignoring received gossip from unknown [UniqueAddress(akka://ditto-cluster@172.18.0.7:2551,-8127987181220488590)]
policies_1       | 2020-10-15 04:04:16,834 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.6:2551], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
policies_1       | 2020-10-15 04:04:16,836 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.6:2551], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:07,802 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.7:2551], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:08,467 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.8:2551], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:08,717 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.9:2551], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:11,398 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.8:2551], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:11,662 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.6:2551], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:11,777 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster@172.18.0.5:2551/system/remoting-terminator - Shutting down remote daemon.
things_1         | 2020-10-15 04:04:12,007 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster@172.18.0.5:2551/system/remoting-terminator - Remote daemon shut down; proceeding with flushing remote transports.
things_1         | 2020-10-15 04:04:12,563 ERROR [] a.r.a.Association Association(akka://ditto-cluster) - Outbound message stream to [akka://ditto-cluster@172.18.0.9:2551] failed after shutdown. 
things_1         | akka.remote.artery.Association$OutboundStreamStopQuarantinedSignal$: 
things_1         | 2020-10-15 04:04:12,563 ERROR [] a.r.a.Association Association(akka://ditto-cluster) - Outbound message stream to [akka://ditto-cluster@172.18.0.9:2551] failed after shutdown. 
things_1         | akka.remote.artery.Association$OutboundStreamStopQuarantinedSignal$: 
things_1         | 2020-10-15 04:04:12,810 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.3:2551], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:12,929 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.3:2551], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:13,050 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.6:2551], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:13,267 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.8:2551], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things_1         | 2020-10-15 04:04:13,584 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster@172.18.0.5:2551/system/remoting-terminator - Remoting shut down.
docker_things_1 exited with code 255
things-search_1  | 2020-10-15 04:04:30,320 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.3:2551], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things-search_1  | 2020-10-15 04:04:30,381 WARN  [] a.s.Materializer akka.stream.Log(akka://ditto-cluster/system/Materializers/StreamSupervisor-1) - [outbound connection to [akka://ditto-cluster@172.18.0.3:2551], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
things-search_1  | 2020-10-15 04:04:30,466 INFO  [] a.r.RemoteActorRefProvider$RemotingTerminator akka://ditto-cluster@172.18.0.6:2551/system/remoting-terminator - Remoting shut down.
mongodb_1        | 2020-10-15T04:04:30.594+0200 I NETWORK  [conn13] end connection 172.18.0.6:55554 (6 connections now open)
mongodb_1        | 2020-10-15T04:04:30.595+0200 I NETWORK  [conn11] end connection 172.18.0.6:55550 (5 connections now open)
mongodb_1        | 2020-10-15T04:04:30.596+0200 I NETWORK  [conn9] end connection 172.18.0.6:55520 (4 connections now open)
docker_things-search_1 exited with code 255

**Comment by silence3322** [comment]
Anybody can help me?  By the way, i started ditto with docker-compose,and i have rose the limited memory to 768m, if it's helpful.

**Comment by thjaeckle** [comment]
The Ditto cluster nodes might get to few CPU power in order to quickly form the cluster.
How many CPUs do you have/give the Docker daemon?

If less than 4, try the following command instead for starting Ditto:
```
docker-compose start mongodb; sleep 30; docker-compose start policies things; sleep 60; docker-compose start concierge; sleep 60; docker-compose start things-search; sleep 60; docker-compose start connectivity; sleep 60; docker-compose up -d
```

**Comment by silence3322** [comment]
> 
> 
> The Ditto cluster nodes might get to few CPU power in order to quickly form the cluster.
> How many CPUs do you have/give the Docker daemon?
> 
> If less than 4, try the following command instead for starting Ditto:
> 
> ```
> docker-compose start mongodb; sleep 30; docker-compose start policies things; sleep 60; docker-compose start concierge; sleep 60; docker-compose start things-search; sleep 60; docker-compose start connectivity; sleep 60; docker-compose up -d
> ```

I applied your method, now it does work. Thank you so much 💯 !
