### ISSUE TITLE
Web Socket Error. Unexpected server response: 401

### ISSUE THREAD

**Issue by silence3322** [eclipse/ditto#845]
I can not link to the service  through ws://localhost:8080/ws/1 or ws://localhost:8080/ws/2.
Then i tested the web socket service by a tool named wscat and got an error like below:

root@raspberry:/home# wscat -c ws://localhost:8080/ws/2
error: Unexpected server response: 401

How can i fix it?

**Comment by thjaeckle** [comment]
Apply authentication .. e.g. by using `ws://ditto:ditto@localhost:8080/ws/2`

For additional questions, please use Stackoverflow and the "eclipse-ditto" tag instead, GitHub issues are meant for tracking problems/bugs/features and not for trivial questions.
