### ISSUE TITLE
put-metadata on a thing's root does not work

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#886]
I tried to use put-metadata on a thing update (PUT) to write a series of metadata on different features and properties but it did not work.

What I did
---

I retrieved the whole thing first via GET, then added based on it's contents and a model a series of put-metadata header entries and finally pushed the whole thing back to ditto. The metadata entries had keys beginning at the things root like this `/features/lamp/properties/status/active` and values of arbitrary json. 

What happened
---

The metadata was not written. An empty `_metadata` object appeared in the thing. After this I tried to do this on the properties and properties/<specific-property> level which resulted in a deeper `_metadata` object but with empty leafs. Turned out I still used the full paths in the keys where I should have used relative ones. Didn't tried to update the keys because I already decomposed everything into single requests for all properties with metadata keys now being just one level and values being primitive.

Expectation
---

The metadata should have been written. I expect if I PUT a whole thing and provide a put-metadata header with like 20 different entries, everyone with a property path from the root to the property as the key that the value, either primitive or arbitrary json, is written.

/kind bug

**Comment by thjaeckle** [comment]
@w4tsn I can't reproduce, could you please provide e.g. a reproducer with the cURL commands you executed?

What I did:
## Create Thing
```sh
curl --location --request PUT 'https://ditto.eclipse.org/api/2/things/org.eclipse.ditto.tjaeckle:test-3' \
--header 'Content-Type: application/json' \
--header 'put-metadata: [{"key": "/attributes/foo/bar","value":true},{"key": "/features/temp/properties/status/value/creator","value":"Thomas"}]' \
--header 'Authorization: Basic ZGl0dG86ZGl0dG8=' \
--data '{}'
```

## Modify existing Thing setting metadata

```sh
curl --location --request PUT 'https://ditto.eclipse.org/api/2/things/org.eclipse.ditto.tjaeckle:test-3' \
--header 'Content-Type: application/json' \
--header 'put-metadata: [{"key": "/attributes/foo/bar","value":true},{"key": "/features/temp/properties/status/value/creator","value":"Thomas"}]' \
--header 'Authorization: Basic ZGl0dG86ZGl0dG8=' \
--data '{
    "thingId": "org.eclipse.ditto.tjaeckle:test-3",
    "policyId": "org.eclipse.ditto.tjaeckle:test-3",
    "attributes": {
        "foo": 42
    },
    "features": {
        "temp": {
            "properties": {
                "status": {
                    "value": 42.23
                }
            }
        }
    }
}'
```

## Get the Thing with metadata

```sh
curl --location --request GET 'https://ditto.eclipse.org/api/2/things/org.eclipse.ditto.tjaeckle:test-3?fields=thingId,attributes,features,_metadata' \
--header 'Content-Type: application/json' \
--header 'put-metadata: [{"key": "/attributes/foo/bar","value":true},{"key": "/features/temp/properties/status/value/creator","value":"Thomas"}]' \
--header 'Authorization: Basic ZGl0dG86ZGl0dG8='
```

results in:
```json
{
  "thingId": "org.eclipse.ditto.tjaeckle:test-3",
  "attributes": {
    "foo": 42
  },
  "features": {
    "temp": {
      "properties": {
        "status": {
          "value": 42.23
        }
      }
    }
  },
  "_metadata": {
    "attributes": {
      "foo": {
        "bar": true
      }
    },
    "features": {
      "temp": {
        "properties": {
          "status": {
            "value": {
              "creator": "Thomas"
            }
          }
        }
      }
    }
  }
}
```

**Comment by w4tsn** [comment]
@thjaeckle the only difference I can spot is that I used arbitrary json objects as my values in the metadata entries. I wanted to set four different metadata key/value pairs at once. Maybe I should just split that up :thinking: 

Apart from that I'll prepare a reproducer next week.

**Comment by yufei-cai** [comment]
@w4tsn any update?

**Comment by w4tsn** [comment]
I tried to reproduce this with the following on the current eclipseprojects.io sandbox with Ditto 2.0.1

```
curl --location --request PUT 'https://ditto.eclipseprojects.io/api/2/things/org.eclipse.ditto.w4tsn:issue-886' \
--header 'Content-Type: application/json' \
--header 'put-metadata: [{"key":"/attributes","value":{"foo":{"bar":true}}},{"key":"/features","value":{"temp":{"properties":{"status":{"value":{"creator": "Alex", "foo": "bar"},"value2":{"creator": "Alex", "foo": "bar2"}}}}}}]' \
--header 'Authorization: Basic ZGl0dG86ZGl0dG8=' \
--data '{
    "thingId": "org.eclipse.ditto.w4tsn:issue-886",
    "policyId": "org.eclipse.ditto.w4tsn:issue-886",
    "attributes": {
        "foo": 42
    },
    "features": {
        "temp": {
            "properties": {
                "status": {
                    "value": 42.23,
                    "value2": 73
                }
            }
        }
    }
}'
```

This indeed works as expected. The thing with metadata looks like this:

```
{
    "thingId": "org.eclipse.ditto.w4tsn:issue-886",
    "attributes": {
        "foo": 42
    },
    "features": {
        "temp": {
            "properties": {
                "status": {
                    "value": 42.23,
                    "value2": 73
                }
            }
        }
    },
    "_metadata": {
        "attributes": {
            "foo": {
                "bar": true
            }
        },
        "features": {
            "temp": {
                "properties": {
                    "status": {
                        "value": {
                            "creator": "Alex",
                            "foo": "bar"
                        },
                        "value2": {
                            "creator": "Alex",
                            "foo": "bar2"
                        }
                    }
                }
            }
        }
    }
}
```

I tried this on my current Ditto 1.5.x Stack (wasn't able to upgrade yet) and it seems to be broken there. No metadata created if using a complex json object as value and a simple key. I'm working around this by splitting up the bigger json object value and flattening it so I get an array with key/value pairs for every leaf.

I guess this is fixed in recent ditto so I'll close this with the knowledge that this problem goes away once I manage to upgrade the cluster.
