### ISSUE TITLE
Support receiving cloud events using HTTP endpoint

### ISSUE THREAD

**Issue by ctron** [eclipse/ditto#889]
I think it makes sense for Ditto to support receiving Ditto Protocol JSON messages also via [Cloud Events](https://cloudevents.io/).

While cloud events provide bindings for Kafka, MQTT, … they also have an [HTTP endpoint binding](https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md), which can easily be used in the combination with [Knative](https://knative.dev/). So it would be possible, to easily map incoming messages from any [Knative eventing source](https://knative.dev/docs/eventing/), to Ditto, acting as a Knative eventing sink.

The payload of these events would be expected to be "Ditto Protocol payload (JSON)".

I would be volunteering to work on this.

**Comment by thjaeckle** [comment]
Cool 👍 
As discussed in Gitter.IM we would appreciate such a contribution.
Implementation hints:
* HTTP handling in Ditto is done with [Akka HTTP](https://doc.akka.io/docs/akka-http/current/index.html)
* the Ditto service responsible for terminating HTTP requests is the [gateway service](https://www.eclipse.org/ditto/architecture-services-gateway.html), see also the [architecture](https://www.eclipse.org/ditto/architecture-overview.html)
* [`RootRoute.buildApiSubRoutes(RequestContext, DittoHeaders)`](https://github.com/eclipse/ditto/blob/master/services/gateway/endpoints/src/main/java/org/eclipse/ditto/services/gateway/endpoints/routes/RootRoute.java#L264) would be the place to add a new top-level route below `/api/2/`

Regarding naming and verb of the new endpoint I would suggest:
* using `POST` as verb
* regarding the "noun":
** I am not yet sure .. `/events` for example would not fit IMO as Ditto Protocol JSON messages are not always events, but also commands
** `/protocolMessages` could be an option, however I would like to prevent using camel case or a dash in the endpoint
** maybe `/signals` as all Ditto Protocol JSON messages represent Signals: https://www.eclipse.org/ditto/basic-signals.html

**Comment by thjaeckle** [comment]
I would close this as the basic functionality is available via #895
