### ISSUE TITLE
Add Openshift Template for ditto

### ISSUE THREAD

**Issue by marziman** [eclipse/ditto#89]
It would be great to have the possibility to make ditto run in openshift/kubernetes. As fas as I can see docker-compose is used. It might makes sense to provide a yaml template for kubernetes/openshift like e.g. Kapua.

**Comment by marziman** [comment]
Just to let you know: I can support to „convert“ it from docker compose notation to openshift yaml with the tool called kompose. But doing it natively in a openshift template might be the preffered approach.

**Comment by thjaeckle** [comment]
Sure, that would be great.
As we are not yet using openshift/kubernetes ourselves we would appreciate some help here, we are noobs in this area 😉

**Comment by marziman** [comment]
Hi @thjaeckle,

I will soon make a PR with k8/OpenShift ressources for ditto. Sorry been a bit busy.
But soon to come ..
