### ISSUE TITLE
Command and control (Hono integration) leads to error: dead letters encountered

### ISSUE THREAD

**Issue by mariolpantunes** [eclipse/ditto#900]
We deployed a Ditto and connected it with our Hono broker.
The devices from Hono are registered on the Ditto, and for each tenant, there is an incoming mapping function and the corresponding command and control connection.
The command and control connection is working as expected, except the reply from the command.

Some times the reply is not delivered and the logs show this error:

> 2020-11-27 16:40:58,994 INFO  [] a.a.LocalActorRef akka://ditto-cluster/user/$H/ackr0-command-and-control - Message [org.eclipse.ditto.signals.commands.messages.SendThingMessageResponse] from Actor[akka://ditto-cluster@172.21.0.9:2551/system/sharding/connection/16/hono-command-control-drtenant3/pa/$a/c1/amqpConsumerActor-0-control%2Fdrtenant3%2Freplies-03/$l#-1871092360] to Actor[akka://ditto-cluster/user/$H/ackr0-command-and-control#-150707102] was not delivered. [12] dead letters encountered, of which 1 were not logged. The counter will be reset now. If this is not an expected behavior then Actor[akka://ditto-cluster/user/$H/ackr0-command-and-control#-150707102] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by thjaeckle** [comment]
Hi @mariolpantunes 
Could you please provide some more information:
* how does the configured connection to Hono look like (complete JSON would be best)?
* do I understand you scenario correctly?
   * you invoke a message via Ditto's HTTP API which should be sent to a device connected to Hono? 
   * the device responds accordingly, but the device's response is not correlated in Ditto?
* how does the reply message from the device then look like?

**Comment by mariolpantunes** [comment]
Hi @thjaeckle, I will provide the required information:

1. Here is a sample of the JSON used to create a connection:

`{'targetActorSelection': '/system/sharding/connection',
        'headers': {'aggregate': False},
        'piggybackCommand': {
            'type': 'connectivity.commands:createConnection',
            'connection': {
               'id': connection_id,
               'connectionType': 'amqp-10',
               'connectionStatus': 'open',
               'uri': uri,
               'failoverEnabled': True,
               'sources': [{
                   'addresses': ['control/tenant/replies'],
                   'authorizationContext': ['nginx:tenant'],
                   'headerMapping': {
                     'correlation-id': '{{ header:correlation-id }}',
                     'status': '{{ header:status }}',
                     'content-type': '{{ header:content-type }}'
                   }
                 }
               ],
               'targets': [{
                   'address': 'control/tenant/{{ thing:name }}',
                   'authorizationContext': ['nginx:tenant'],
                   'topics':['_/_/things/live/messages'],
                   'headerMapping': {
                     'message-id': '{{ header:correlation-id }}',
                     'subject': '{{ topic:subject }}',
                     'content-type': 'application/vnd.eclipse.ditto+json',
                     'reply-to': 'control/tenant/replies'
                   }
                 }
               ]
             }
           }
        }`

2. Yes, that is the scenario.
3. Sample from the reply message:
`{'topic': 'drtenant3/drdummy/things/live/messages/command', 'headers': {'content-type': 'application/json', 'correlation-id': 'command-and-control'}, 'path': '/inbox/messages/command', 'value': {'status': '200 OK'}, 'status': 200}
`

**Comment by thjaeckle** [comment]
And how long does the device need in order to respond to the Ditto message with a response? 
Looks like a timeout could be the problem (default timeout for POST /messages in Ditto is 10 seconds).

**Comment by mariolpantunes** [comment]
The reply is almost instantaneous.
The device is a dummy sensor.

**Comment by thjaeckle** [comment]
I think I am still missing some context:
* do you set an explicit "timeout" when sending the message via `POST /messages`?
* do you re-use the "correlation-id" `"command-and-control"`? you cannot do this - the correlation-ids have to be unique (at least in a timeframe of 1 minute)
* is there the possibility that the dummy sensor answers several times to one single message?

**Comment by mariolpantunes** [comment]
I will reply to each one of the topics:
1. We define a timeout in the POST message of 60 seconds

2. Maybe that is the issue, we are using the correlation-id command and control for everything. I will try different strings. Based on the examples I thought it was mandatory to be command and control.

3. It only replies once.

**Comment by mariolpantunes** [comment]
I tried to change the correlation id (random string generated with python) on the POST message (the dummy_sensor reads replies to the same correlation id).
However, the issue still remains.

This is the code that I use for the command:

`def get_random_string(length):
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str


def send_command(args, command, timeout=60):
    headers = {'x-correlation-id': get_random_string(8)}
    params = (('timeout', timeout),)
    #command = {'rate': args.r}
    url = '{}/api/2/things/{}:{}/inbox/messages/command'.format(args.u, args.t, args.d)

    data = json.dumps(command)

    t = time.time_ns()
    response = requests.post(url=url, headers=headers, params=params, data=data, auth=(args.t, args.p))
    
    logger.info('%d,%f',command['id'],t)
    logger.debug(response)
    logger.info(response.text)`

This is the code that replies to the command:

`def on_message(client, userdata, msg):
    t = time.time_ns()
    logger.info(msg.payload)
    incoming = json.loads(msg.payload)
    topic = incoming['topic']
    path = incoming['path']
    value = incoming['value']
    correlation_id = incoming['headers']['correlation-id']

    data = json.loads(base64.b64decode(value))
    logger.debug('On message {}'.format(data))
    global rate
    rate = data['rate']

    logger.info('%d,%f', data['id'], t)
    
    reply_topic = 'control///res/013command-and-controlreplies/200'
    msg = {'topic': topic,
        'headers': {'content-type': 'application/json',
        'correlation-id': correlation_id},
        'path': path,
        'value': {'status': '200 OK'},
        'status': 200}
    print(msg)
    client.publish(reply_topic, json.dumps(msg), qos=0)
    return`

**Comment by thjaeckle** [comment]
`... reply_topic = 'control///res/013command-and-controlreplies ...` 

That is wrong, via Hono MQTT, you need to reply on the topic with the actual `req-id`, you can't use a static value here, see also:
https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#sending-a-response-to-a-command-authenticated-device

Which example did you use in order to build your setup on? Seems like there are some things in there which can be misunderstood ;)

**Comment by mariolpantunes** [comment]
Thanks for the reply, I do not found req-id within the headers of the message.
From here do I read the req-id?

I used this tutorial: https://www.eclipse.org/ditto/2018-12-05-example-command-and-control.html

**Comment by mariolpantunes** [comment]
Based on your comment I have updated the function that replies to the command:
`def on_message(client, userdata, msg):
    t = time.time_ns()
    logger.info('Incoming topic: %s', msg.topic)
    #logger.info(msg.payload)
    incoming = json.loads(msg.payload)
    topic = incoming['topic']
    path = incoming['path']
    value = incoming['value']
    correlation_id = incoming['headers']['correlation-id']

    data = json.loads(base64.b64decode(value))
    logger.debug('On message {}'.format(data))
    global rate
    rate = data['rate']

    #logger.info('%d,%f', data['id'], t)
    
    #reply_topic = 'control///res/013command-and-controlreplies/200'
    req_id = msg.topic.split('/')[4]
    reply_topic = 'command///res/{}/200'.format(req_id)
    
    #msg = {'topic': topic,
    #    'headers': {'content-type': 'application/json',
    #    'correlation-id': correlation_id},
    #    'path': path,
    #    'value': {'status': '200 OK'},
    #    'status': 200}
    #print(msg)
    logger.info('Topic %s', reply_topic)
    
    msg={'status': 200}
    logger.info(msg)
    client.publish(reply_topic, json.dumps(msg), qos=0)
    return`

But the code does not work as well, the error is bellow:

`2020-12-04 18:55:07,581 INFO  [wofaxcfx] o.e.d.s.g.s.a.p.PreAuthenticatedAuthenticationProvider  - Pre-authentication has been applied resulting in AuthorizationContext <ImmutableAuthorizationContext [type=pre-authenticated-http, authorizationSubjects=[nginx:drtenant3]]>.
2020-12-04 18:55:07,584 INFO  [wofaxcfx] o.e.d.s.m.c.a.ConciergeForwarderActor akka://ditto-cluster/user/gatewayRoot/conciergeForwarder - Forwarding signal with ID <drtenant3:drdummy> and type <messages.commands:thingMessage> to concierge enforcer
2020-12-04 18:55:07,584 INFO  [wofaxcfx] o.e.d.s.m.a.AcknowledgementAggregatorActor akka://ditto-cluster/user/$Gi/ackr0-wofaxcfx - Starting to wait for all requested acknowledgements <[live-response]> for a maximum duration of <PT1M>.
2020-12-04 18:55:11,587 INFO  [mespbdtu] o.e.d.s.m.a.AcknowledgementAggregatorActor akka://ditto-cluster/user/$Fi/ackr0-mespbdtu - Timed out waiting for all requested acknowledgements, completing Acknowledgements with timeouts...
2020-12-04 18:55:11,587 INFO  [mespbdtu] o.e.d.s.g.e.a.HttpRequestActor akka://ditto-cluster/user/$Fi - Got <ReceiveTimeout> when a response was expected after timeout <PT1M>.
2020-12-04 18:55:11,588 INFO  [mespbdtu] o.e.d.s.g.e.a.HttpRequestActor akka://ditto-cluster/user/$Fi - DittoRuntimeException <gateway:command.timeout>: <The Command reached the specified timeout of 60,000ms.>.
2020-12-04 18:55:11,588 INFO  [mespbdtu] o.e.d.s.g.e.d.RequestResultLoggingDirective  - StatusCode of request POST '/api/2/things/drtenant3:drdummy/inbox/messages/command?timeout=60' was: 408
2020-12-04 18:55:11,588 INFO  [] a.a.RepointableActorRef akka://ditto-cluster/user/$Fi - Message [org.eclipse.ditto.signals.commands.things.ThingErrorResponse] to Actor[akka://ditto-cluster/user/$Fi#1343860784] was not delivered. [5] dead letters encountered. If this is not an expected behavior then Actor[akka://ditto-cluster/user/$Fi#1343860784] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
2020-12-04 18:55:11,588 WARN  [mespbdtu] o.e.d.s.g.e.d.RequestTimeoutHandlingDirective  - Encountered slow HTTP request which took over <1000> ms: <60025> ms!
`

**Comment by thjaeckle** [comment]
> ```#msg = {'topic': topic,
> #    'headers': {'content-type': 'application/json',
> #    'correlation-id': correlation_id},
> #    'path': path,
> #    'value': {'status': '200 OK'},
> #    'status': 200}
> #print(msg)
> logger.info('Topic %s', reply_topic)
> 
> msg={'status': 200}
> ```

Why did you change the response format?
Please change back to the commented out `msg`  and you should be good.

**Comment by thjaeckle** [comment]
Glad to hear that you solved it 👍 
Yes, the Hono topics changed before 1.0 was released, so the blogpost from 2018 is probably also outdated.

The most up-to-date documentation on the Hono-Ditto integration is located in the IoT Packages project:
https://www.eclipse.org/packages/packages/cloud2edge/tour/
