### ISSUE TITLE
Docs on Protocol/Create+Modify still use ACL concept

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#930]
In the current version of the docs on Ditto Protocol e.g. for Thing Creation the description still uses ACL to describe the auth context. This should be updated to policies. *Using this issue to remind me.*

https://www.eclipse.org/ditto/protocol-specification-things-create-or-modify.html

**Comment by thjaeckle** [comment]
Fixed with upcoming Ditto 2.0 changes.
