### ISSUE TITLE
AMQP 1.0 message interpreted as JMS

### ISSUE THREAD

**Issue by tobias-zeptio** [eclipse/ditto#935]
When I publish a message using the rhea library to a Artemis broker, ditto receives the message but interprets it as JMS.
```
Received JmsMessage from AMQP 1.0: JmsObjectMessageFacade { org.apache.qpid.jms.provider.amqp.message.AmqpJmsObjectMessageFacade@e00d9d45 } with Properties: java.util.Collections$3@c79393a3 and AckType 1
Received message at 'iot.hdt.in' of unsupported type (org.apache.qpid.jms.message.JmsObjectMessage) with headers: {to=iot.hdt.in, absolute-expiry-time=1610104746153}
Received message from AMQP 1.0 with externalMessageHeaders: {absolute-expiry-time=1610104746153, to=iot.hdt.in}
Received message from AMQP 1.0 with payload: binary
``` 
This results in both payload, headers and content-type to be null in the `mapToDittoProtocolMsg` payload mapper.
Is there any way to configure the connection to interpret the message as AMQP?
I have set `"connectionType": "amqp-10"`.

**Comment by ffendt** [comment]
Hi there,
`JmsMessage` is the correct datatype used by the AMQP client Ditto uses (qpid).

The signature of the mapper method is:
```
function mapToDittoProtocolMsg(
  headers,
  textPayload,
  bytePayload,
  contentType
)
```
Is `bytePayload` null in your case? Does the message have content? Can you send an arbitrary header with your message (or maybe just a known header like `content-type`) and verify if it is listed in the log line "Received message from AMQP 1.0 with externalMessageHeaders"?

**Comment by tobias-zeptio** [comment]
Oh, I see. So it will always say JmsMessage from AMQP 1.0? If, I think that's a bit confusing. But maybe it's just me...

I was sending a javascript object using rhea, expecting it to convert that to JSON. But maybe it doesn't. After converting the object to a string and sending that as the message it worked.

Still confused about the message format and why headers and contentType was null.

**Comment by thjaeckle** [comment]
> If, I think that's a bit confusing. But maybe it's just me...

Indeed - however, this is the concept of the used [Qpid AMQP 1.0 client](https://qpid.apache.org/components/jms/index.html) which is unfortunately the only usable AMQP 1.0 client for Java.
This client "wraps" the AMQP 1.0 interaction via JMS API, so the Ditto codebase has no other option than using JMS API which could lead to confusion in e.g. logs.
