### ISSUE TITLE
Merging "extraFields" with modified events did use the data from "extra" to overwrite actually changed data from the event

### ISSUE THREAD

**Issue by raujonas** [eclipse/ditto#947]
Hello. I have a question about using the "extraFields" parameter together with server sent events.

Let's say I want to retrieve all attributes and all features together with the changed data. I specified the event source and the extraFields like this:
```
let eventSourceInitDict = { headers: { Authorization: `Bearer ${tokenResponse.access_token}` }, withCredentials: true };
let es = new EventSource(environment.dittoUrl + '/things?extraFields=features,attributes', eventSourceInitDict);
```

For testing I used the example thing from the documentation which looks like this at the beginning:
```json
{
    "thingId": "org.eclipse.ditto:my-coffeebrewer",
    "policyId": "org.eclipse.ditto:my-coffeebrewer",
    "definition": "com.acme:coffeebrewer:0.1.0",
    "attributes": {
        "manufacturer": "ACME demo corp.",
        "location": "Berlin, main floor",
        "serialno": "42",
        "model": "Speaking coffee machine"
    },
    "features": {
        "coffee-brewer": {
            "properties": {
                "brewed-coffees": 0
            }
        },
        "water-tank": {
            "properties": {
                "configuration": {
                    "smartMode": true
                }
            }
        }
    }
}
```

In the next step I updated the attribute "manufacturer" to the value "ACME demo corp. test test test". I received all features from the server sent event like expected. However, there's only the updated attribute included and not the other ones:
```json
{
  "thingId": "org.eclipse.ditto:my-coffeebrewer",
  "attributes": {
    "manufacturer": "ACME demo corp. test test test"
  },
  "features": {
    "coffee-brewer": {
      "properties": {
        "brewed-coffees": 0
      }
    },
    "water-tank": {
      "properties": {
        "configuration": {
          "smartMode": true
        }
      }
    }
  }
}
```

The same thing happens if I try to update a feature instead. If I try to update the feature "coffee-brewer" to 
```json
{
  "properties": {
    "brewed-coffees": 100
  }
}
```
then all attributes are included but the other features are missing, I receive the following from the sse:
```json
{
  "thingId": "org.eclipse.ditto:my-coffeebrewer",
  "attributes": {
    "manufacturer": "ACME demo corp. test test test",
    "location": "Berlin, main floor",
    "serialno": "42",
    "model": "Speaking coffee machine"
  },
  "features": {
    "coffee-brewer": {
      "properties": {
        "brewed-coffees": 100
      }
    }
  }
}
```

I'm aware that it might not be the best idea to return all features and attributes on every change of the thing, but my question is, is this the expected behaviour when all features and attributes are included in the extraFields like this: `/things?extraFields=features,attributes` or did I miss something here to retrieve the missing attributes and features in this case?

I don't know if I've missed something crucial here and any clarification is very appreciated. Thank you very much!

Final thing looks like this:

```json
{
    "thingId": "org.eclipse.ditto:my-coffeebrewer",
    "policyId": "org.eclipse.ditto:my-coffeebrewer",
    "definition": "com.acme:coffeebrewer:0.1.0",
    "attributes": {
        "manufacturer": "ACME demo corp. test test test",
        "location": "Berlin, main floor",
        "serialno": "42",
        "model": "Speaking coffee machine"
    },
    "features": {
        "coffee-brewer": {
            "properties": {
                "brewed-coffees": 100
            }
        },
        "water-tank": {
            "properties": {
                "configuration": {
                    "smartMode": true
                }
            }
        }
    }
}
```

**Comment by ffendt** [comment]
Hi @raujonas,

thank you very much for taking the time to create a detailed explanation for your finding 👍. This looks like a bug to me. The SSE message you receive should be returned in the outcome you expected. I.e. an update on a single attribute should return all attributes when registered using `extraFields=attributes`.

We're currently focusing on getting Ditto 2.0.0 ready for a release. I don't know if we'll be tackle this bug early enough to get it in there.
