### ISSUE TITLE
Connection Target Error 

### ISSUE THREAD

**Issue by Geonjae-Joo** [eclipse/ditto#971]
Hi, I was using eclipse iot Package v0.1.2 (which includes ditto:1.3, hono:1.3.19) and all functions worked fine.
In order to use "desiredProperties" I upgraded the version to 0.1.3 ( ditto:1.5.1, hono: 1.4.21),
Then I got a problem sending out "command" to device via hono as below. 

Connection Log:
target successfully dispatched, filtered and mapped, but can not publish

![image](https://user-images.githubusercontent.com/62494715/108167579-3f0fb280-7139-11eb-8d79-843695530a7f.png)

Connection:

![image](https://user-images.githubusercontent.com/62494715/108167882-bc3b2780-7139-11eb-8bf9-59b01095b772.png)

Pleas help me out,

**Comment by thjaeckle** [comment]
@Geonjae-Joo the message "timed out waiting for credit to send Message" normally indicates that in Hono currently the device is not connected / subscribed to receive commands.
Are you sure that a device with the deviceId `Xavier-1` is connected via Hono and subscribed for commands?

**Comment by Geonjae-Joo** [comment]
Oh I am sorry I posted wrong log

![image](https://user-images.githubusercontent.com/62494715/108171129-6917a380-713e-11eb-86f3-b8ce4a5d08da.png)

This is the error.

**Comment by thjaeckle** [comment]
@Geonjae-Joo did you verify that Hono is consuming messages and the amqp 10 network is working correctly?
I don't see how this connection problem would be related to Ditto.

**Comment by Geonjae-Joo** [comment]
@thjaeckle Yeap, I am sure the codes are working on version eclipse-iot 0.1.2 (which includes ditto:1.3, hono:1.3.19) package.
I tried ( ditto:1.5.1, hono: 1.3.19), but it shows the same error as above. I have no idea what is wrong. Do you have any suggestion I can try to solve this error?

**Comment by Geonjae-Joo** [comment]
This  is my connection command by the way.


curl -i -X POST -u devops:${DITTO_DEVOPS_PWD} -H 'Content-Type: application/json' --data '{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:createConnection",
    "connection": {
      "id": "hono-connection-for-'"${HONO_TENANT}"'",
      "connectionType": "amqp-10",
      "connectionStatus": "open",
      "uri": "amqp://consumer%40HONO:verysecret@'"${RELEASE}"'-dispatch-router-ext:15672",
      "failoverEnabled": true,
      "sources": [
        {
          "addresses": [
            "telemetry/'"${HONO_TENANT}"'",
            "event/'"${HONO_TENANT}"'"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "enforcement": {
            "input": "{{ header:device_id }}",
            "filters": [
              "{{ entity:id }}"
            ]
          },
          "headerMapping": {
            "hono-device-id": "{{ header:device_id }}",
            "content-type": "{{ header:content-type }}"
          },
          "replyTarget": {
            "enabled": true,
            "address": "{{ header:reply-to }}",
            "headerMapping": {
              "to": "command/'"${HONO_TENANT}"'/{{ header:hono-device-id }}",
              "subject": "{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response",
              "correlation-id": "{{ header:correlation-id }}",
              "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}"
            },
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          },
          "acknowledgementRequests": {
            "includes": [],
            "filter": "fn:filter(header:qos,'"'"'ne'"'"','"'"'0'"'"')"
          }
        },
        {
          "addresses": [
            "command_response/'"${HONO_TENANT}"'/replies"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "headerMapping": {
            "content-type": "{{ header:content-type }}",
            "correlation-id": "{{ header:correlation-id }}",
            "status": "{{ header:status }}"
          },
          "replyTarget": {
            "enabled": false,
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          }
        }
      ],
     "targets": [
        {
          "address": "command/'"${HONO_TENANT}"'",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/live/commands",
            "_/_/things/live/messages"
          ],
          "headerMapping": {
            "to": "command/'"${HONO_TENANT}"'/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}",
            "reply-to": "{{ fn:default('"'"'command_response/'"${HONO_TENANT}"'/replies'"'"') | fn:filter(header:response-required,'"'"'ne'"'"','"'"'false'"'"') }}"
          }
        },
        {
          "address": "command/'"${HONO_TENANT}"'",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/twin/events",
            "_/_/things/live/events"
          ],
          "headerMapping": {
            "to": "command/'"${HONO_TENANT}"'/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}"
          }
        }
      ]
    }
  }
}' http://${DITTO_API_IP}:${DITTO_API_PORT_HTTP}/devops/piggyback/connectivity

**Comment by thjaeckle** [comment]
> @thjaeckle Yeap, I am sure the codes are working on version eclipse-iot 0.1.2 (which includes ditto:1.3, hono:1.3.19) package.

That's not what I asked .. are you sure that all AMQP and Hono containers are up and running?

One more thing to try out: do you have the same problem if you start a new cluster instead of updating an old one?

**Comment by Geonjae-Joo** [comment]
![image](https://user-images.githubusercontent.com/62494715/108960647-92de4680-76b9-11eb-8678-ee3c97c06a15.png)

They are up and running well, and I double checked Device Registry in Hono and AMQP Network service url. 
I deleted the cluster and installed it several times. Got the same problem.

**Comment by thjaeckle** [comment]
Does the other direction - sending telemetry + events from the device - work?

**Comment by Geonjae-Joo** [comment]
Yeap, working fine.

**Comment by thjaeckle** [comment]
In your first configuration screenshot you have in the target "headerMapping":
```json
"to": "command/'"${HONO_TENANT}"'/{{ thing:name }}",
```

In the configuration you pasted inline today you have:
```json
"to": "command/'"${HONO_TENANT}"'/{{ thing:id }}",
```

So which of those is it?
And most important: which device-id has the device created in Hono? This must match the last part in the `"to"` field.

**Comment by Geonjae-Joo** [comment]
Oh, I changed Hono Device registry in order to try both of them.

**Comment by Geonjae-Joo** [comment]
now it is thing:name

HONO Device= Xavier-1
Ditto thing= keti:Xavier-1

**Comment by Geonjae-Joo** [comment]
Hono registry:
 tenant: 
![image](https://user-images.githubusercontent.com/62494715/108963356-56ace500-76bd-11eb-8c25-6f1b75f40abf.png)
device:
![image](https://user-images.githubusercontent.com/62494715/108963391-62001080-76bd-11eb-9344-d8e2be9e2ded.png)
credential:
![image](https://user-images.githubusercontent.com/62494715/108963438-6f1cff80-76bd-11eb-9b87-e2d53f88f275.png)


Ditto:
policy:
![image](https://user-images.githubusercontent.com/62494715/108963502-865bed00-76bd-11eb-9b89-e4d4b122af1c.png)
thing:
![image](https://user-images.githubusercontent.com/62494715/108963531-9378dc00-76bd-11eb-95f7-e56765ceea59.png)

**Comment by thjaeckle** [comment]
And just to make sure: the device consumes commands, e.g. by subscribing to Hono's correct MQTT "command" topic?
https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#receiving-commands-authenticated-device

**Comment by Geonjae-Joo** [comment]
Yeap, it worked just fine with the previous version 
![image](https://user-images.githubusercontent.com/62494715/108964479-dbe4c980-76be-11eb-8637-4ee53061202c.png)

**Comment by thjaeckle** [comment]
Please try out one more thing - reading the connection and therefore checking if all bash variables have successfully been resolved:
```bash
curl -i -X POST -u devops:${DITTO_DEVOPS_PWD} -H 'Content-Type: application/json' --data '{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:retrieveConnection",
    "connectionId": "hono-connection-for-'"${HONO_TENANT}"'"
  }
}' http://${DITTO_API_IP}:${DITTO_API_PORT_HTTP}/devops/piggyback/connectivity
```

**Comment by Geonjae-Joo** [comment]
I tried on three different Computer and 
{"?":{"?":{"type":"connectivity.responses:retrieveConnection","status":200,"connection":{"id":"hono-connection-for-keti-tenant-0","name":null,"connectionType":"amqp-10","connectionStatus":"open","uri":"amqp://consumer%40HONO:verysecret@c2e-dispatch-router-ext:15672","sources":[{"addresses":["telemetry/keti-tenant-0","event/keti-tenant-0"],"consumerCount":1,"authorizationContext":["pre-authenticated:hono-connection"],"enforcement":{"input":"{{ header:device_id }}","filters":["{{ entity:id }}"]},"acknowledgementRequests":{"includes":[],"filter":"fn:filter(header:qos,'ne','0')"},"headerMapping":{"hono-device-id":"{{ header:device_id }}","content-type":"{{ header:content-type }}"},"replyTarget":{"address":"{{ header:reply-to }}","headerMapping":{"content-type":"{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}","to":"command/keti-tenant-0/{{ header:hono-device-id }}","subject":"{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response","correlation-id":"{{ header:correlation-id }}"},"expectedResponseTypes":["error","response"],"enabled":true}},{"addresses":["command_response/keti-tenant-0/replies"],"consumerCount":1,"authorizationContext":["pre-authenticated:hono-connection"],"headerMapping":{"content-type":"{{ header:content-type }}","correlation-id":"{{ header:correlation-id }}","status":"{{ header:status }}"},"replyTarget":{"enabled":false}}],"targets":[{"address":"command/keti-tenant-0","topics":["_/_/things/live/commands","_/_/things/live/messages"],"authorizationContext":["pre-authenticated:hono-connection"],"headerMapping":{"content-type":"{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}","to":"command/keti-tenant-0/{{ thing:id }}","reply-to":"{{ fn:default('command_response/keti-tenant-0/replies') | fn:filter(header:response-required,'ne','false') }}","subject":"{{ header:subject | fn:default(topic:action-subject) }}","correlation-id":"{{ header:correlation-id }}"}},{"address":"command/keti-tenant-0","topics":["_/_/things/twin/events","_/_/things/live/events"],"authorizationContext":["pre-authenticated:hono-connection"],"headerMapping":{"content-type":"{{ header:content-type | fn:default('application/vnd.eclipse.ditto+json') }}","to":"command/keti-tenant-0/{{ thing:id }}","subject":"{{ header:subject | fn:default(topic:action-subject) }}","correlation-id":"{{ header:correlation-id }}"}}],"clientCount":1,"failoverEnabled":true,"validateCertificates":true,"processorPoolSize":5,"tags":[]}}}}

**Comment by Geonjae-Joo** [comment]
Yes, It looks same with my  connection creation

**Comment by Geonjae-Joo** [comment]
![Uploading image.png…]()

**Comment by Geonjae-Joo** [comment]
![image](https://user-images.githubusercontent.com/62494715/108966073-1485a280-76c1-11eb-9903-67248e0c09fa.png)

**Comment by thjaeckle** [comment]
Connection looks all good from Ditto side 👍 
Please use [markdown code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) in the future to not loose any information (e.g. the underscores were lost in your snippet).

You could activate debug logging in Ditto by setting the environment variable `LOG_LEVEL_APPLICATION` to `DEBUG` on the `connectivity` service - maybe you get some more insight on why sending the message to Hono fails. But I fear that you get the same information as you already have: "Delivery failed. Released by receiver".

I suggest to ask the Hono or the Packages project for help.

**Comment by Geonjae-Joo** [comment]
![image](https://user-images.githubusercontent.com/62494715/108966176-35e68e80-76c1-11eb-99b1-1d95ca649a3d.png)

**Comment by Geonjae-Joo** [comment]
@thjaeckle  Thank you so much for helping. I will update the post as soon as I figure it out!

**Comment by Geonjae-Joo** [comment]
https://github.com/eclipse/packages/issues/202
