### ISSUE TITLE
Support managed connection via SSH tunnel 

### ISSUE THREAD

**Issue by dguggemos** [eclipse/ditto#985]
Add support for connecting to an external system from Ditto via an SSH tunnel.

**Comment by thjaeckle** [comment]
Created CQs for "sshd" library to be used for this (clealydefined score is only 72):
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23086
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23087
